### ISSUE TITLE
请问有关闭打字音功能嘛

### ISSUE THREAD

**Issue by SteveBlackHumor** [fcitx5-android/fcitx5-android#105]
我手机的打字提示音比较尖，于是在设置里翻找了一会，找到了关闭震动等等，但似乎没有关闭打字音的选项。

**Comment by rocka** [comment]
我很好奇打字提示音是什么样的，因为根本没有写过这种功能

**Comment by SteveBlackHumor** [comment]
类似iOS键盘打字的时候，会有哒的一声，代表你按下了一个键。一加氧OS在点击到一些可选项的时候，比如一个app，一个菜单选项，或是打字的时候，都会有一个提示音，滴的一声，这几种操作音效一样。trime 和 GBoard 都有单独关闭打字时音效的选项（但不会关闭 选择app 或 菜单选项 的声音）看来fcitx-android 应该没有这个关闭选项😂

**Comment by rocka** [comment]
https://github.com/fcitx5-android/fcitx5-android/commit/e7c0e6507c8d13e5badb7c7ca034218c7ae91eb7 添加了关闭系统按键音的选项
