### ISSUE TITLE
物理键盘用的候选词界面 / Candidates view for physical keyboard

### ISSUE THREAD

**Issue by gmg137** [fcitx5-android/fcitx5-android#106]
你好，我是用的华为matepad+官方键盘套，使用键盘输入时没有任何反应，希望可以适配一下，十分感谢。

**Comment by rocka** [comment]
目前没有对物理键盘做输入界面上的适配，使用物理键盘时不要隐藏虚拟键盘。

**Comment by gmg137** [comment]
谢谢，这样可以使用了。。。。话说有计划适配物理键盘吗?

**Comment by rocka** [comment]
要问有没有计划，那肯定会说有；但什么时候能实现就是另外一个问题了。

**Comment by yzgpk2002** [comment]
横屏把键盘高设为10%，勉强可用。

**Comment by gbcgYaNg** [comment]
> 要问有没有计划，那肯定会说有；但什么时候能实现就是另外一个问题了。

开发者大佬你好，请问近期有计划实现这个功能吗？我看这个需求已经置顶很长一段时间了，还蛮期待的。😘
