### ISSUE TITLE
输入"；"，有快速输入提示，需要二次输入确认

### ISSUE THREAD

**Issue by lililiwuming** [fcitx5-android/fcitx5-android#108]
![Screenshot_20220904_051041_com brave browser_edit_870835020670245](https://user-images.githubusercontent.com/62045515/188287846-944cf892-ea4a-4fea-aff4-4e1635a4a771.jpg)
如何取消这个提示？

**Comment by rocka** [comment]
在拼音设置里把快速输入触发键删掉就行了，因为现在还没有写改快捷键的界面，需要自己改配置文件。

具体位置是 /Android/data/org.fcitx.fcitx5.android/config/conf/pinyin.conf （也可以直接在 Documents UI 里面找到 "Fcitx5 for Android/config/conf/pinyin.conf"），把 `QuickPhraseKey=semicolon` 改成 `QuickPhraseKey=` ，然后重载配置就好了
