### ISSUE TITLE
希望有九宫格布局，提高中文输入速度

### ISSUE THREAD

**Issue by iminto** [fcitx5-android/fcitx5-android#109]
希望有九宫格布局，提高中文输入速度。

九宫格对中文输入法的速度提升是很明显的。

**Comment by rocka** [comment]
这个在短期内应该实现不了 ... 需要 [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) 的 pinyin engine 先支持九键（或者放通用一点，任意数量的组合键）输入，然后是 [fcitx5](https://github.com/fcitx/fcitx5) 的虚拟键盘布局 API ，最后才是 Android 这边适配界面。~说人话就是未来可期~

**Comment by TheInterestingSoul** [comment]
其实可以跳过前两步，就是模糊音。同文输入法中用户搞的九键甚至18键16键布局都是使用模糊音完成的

**Comment by bantouguo** [comment]
手机上就想找个九宫格的开源输入法，同文输入法设置了半天，结果并不顺利，

期待作者能有突破~~

**Comment by Mr-Li-jc** [comment]
请问现在实现了九宫格吗？手机上没有九宫格确实不方便额

**Comment by oldherl** [comment]
没有

> 请问现在实现了九宫格吗？手机上没有九宫格确实不方便额

**Comment by kartbl** [comment]
会有30键的布局吗？

**Comment by yibajianghudao** [comment]
想要九宫格

**Comment by DoveBoy** [comment]
很希望引入9宫格键盘

**Comment by rocka** [comment]
合并到 #377

**Comment by 2LC16** [comment]
现在有九宫格了吗？

**Comment by wangzyz** [comment]
还没有九宫格，暂时用的微信输入法。习惯九宫格了

**Comment by tmzqcn** [comment]
同求!

**Comment by zasl** [comment]
+1

**Comment by Brx86** [comment]
如果非常需要九宫格，而且是常见方案，可以用隔壁 语燕输入法 https://github.com/gurecn/YuyanIme

**Comment by chenleichao** [comment]
＋1
