### ISSUE TITLE
输入振动功能能否尽快修复？

### ISSUE THREAD

**Issue by SunflowerThom** [fcitx5-android/fcitx5-android#113]
习惯了gboard的振动，现在输入的时候没有振动是非常难受的一件事，打字都感觉无力。麻烦尽快修复一下，辛苦您了！

**Comment by keta1** [comment]
具体是什么错误？
打字没有振动？

**Comment by SunflowerThom** [comment]
> 具体是什么错误？ 打字没有振动？

是的 声音和震动无效 系统为类原生lineage OS Android12

**Comment by q234rty** [comment]
同为 LineageOS Android 12 无法复现。
能否检查一下 fcitx5-android 的行为设置中的“按键时振动”和“系统按键音”有没有被关闭？

**Comment by SunflowerThom** [comment]
![Screenshot_20220910-123454_设置](https://user-images.githubusercontent.com/20704491/189468846-7e20cee8-8c67-4094-b1fb-28a6adbf6112.png)
![Screenshot_20220910-123235_小企鹅输入法5](https://user-images.githubusercontent.com/20704491/189468847-4ea78300-8401-49d1-8ece-03140bed9cea.png)
可以确定的是这两个按键都有打开，但是没有声音和振动。可能是我的lineage os是非官方的原因

**Comment by myantboy** [comment]
振动和声音不太同步，声音滞后比较明显

**Comment by rocka** [comment]
closed by #148
