### ISSUE TITLE
键盘位置调节

### ISSUE THREAD

**Issue by MesPent** [fcitx5-android/fcitx5-android#116]
Keyboard position adjustment
希望可以调节键盘的高度

比如这样
https://user-images.githubusercontent.com/80346269/189528526-1ab4beaf-538a-456f-8ba2-ce2044a775a5.mp4

可以为屏幕下方预留空间
-----------
部分手机屏幕是圆角的，键盘总会有部分会被挡住，操作也会有影响
Under the rounded screen, some keys are always covered or affect the use.

![mmexport1662895796541.jpg](https://user-images.githubusercontent.com/80346269/189525018-a4e03337-0b6b-487d-a567-0b4fd1f81d47.jpg)

比如下滑不了句号这个键，因为下方屏幕太小了。
不过不是什么大问题。

作者考虑一下加这个，谢谢了

**Comment by rocka** [comment]
completed in f051aef4d6f77e20b2564490afdc883eda12f0d6
