### ISSUE TITLE
Support more languages / engines 支持更多输入法引擎

### ISSUE THREAD

**Issue by qndydyhm** [fcitx5-android/fcitx5-android#117]
Support some other languages such as Japanese and Korean

**Comment by Tennyleaz** [comment]
Could be good to support `fcitx5-chewing` (注音輸入法), and `fcitx5-table-extra` (倉頡、行列、速成...) also.

**Comment by adarsh1001** [comment]
Seconded, Japanese input would be really appreciated.

**Comment by rocka** [comment]
Loading addon from plugin is implemented in #231, as well as an Anthy plugin (https://github.com/fcitx5-android/fcitx5-android/blob/46fa45178a0443796ac2b8a6dd1a4aa4d377875f/plugin/anthy). From now on, we can gradually add support for more engine addons.
