### ISSUE TITLE
新增图片主题无法持续保持

### ISSUE THREAD

**Issue by gmg137** [fcitx5-android/fcitx5-android#118]
在新增主题，添加背景图片后，在清理小企鹅输入法后台后再调用输入法 ，主题就会恢复到系统主题。测试多次都是这样。

**Comment by rocka** [comment]
检查一下是不是开启了主题设置中的“跟随系统暗色模式“。如果开启了这个选项，会在每次输入法重启或者系统配置（暗色模式，屏幕方向，语言等）改变的时候重新设置主题。

**Comment by gmg137** [comment]
还真是这原因，非常感谢，已经没问题
