### ISSUE TITLE
[bug] QQ 聊天无法删除回复

### ISSUE THREAD

**Issue by sukanka** [fcitx5-android/fcitx5-android#121]
## 描述
一旦在QQ聊天中选择回复某一段文字，被选择的文字无法删除（可以选择回复另一段文字，但是不能不回复）
就图里面的那段文字无法删除，可以替换成回复别的消息。

## 补充
注： gboard 正常，
0.0.2-197-g4af305f-release 版本正常

0.0.2-204-g5a4e391-release 不正常
0.0.2-210-g0eb401b-release 不正常

## 附图
![security_Screenshot_20220914-112828-469](https://user-images.githubusercontent.com/31362108/190060165-198fdbd6-ed74-4de6-8a45-a11a016da1a1.png)

**Comment by rocka** [comment]
caused by https://github.com/fcitx5-android/fcitx5-android/commit/0f150ec44b9f799437a98c45377241c3c2e46dcd

**Comment by rocka** [comment]
should be fixed by https://github.com/fcitx5-android/fcitx5-android/commit/00377811ea868bdfb7ac0adf4f50c2cb6fe16ce3

**Comment by sukanka** [comment]
感谢，经验证在 0.0.2-215-g1168e30-release 问题已解决
