### ISSUE TITLE
未开启数字键盘选词，输入中文再切进符号键盘，点击数字仍是数字选词而不是输入数字

### ISSUE THREAD

**Issue by PaPerseller** [fcitx5-android/fcitx5-android#122]
系统 lineage 19.1，软件 0.0.2-216。数字键盘选词已关闭，在输入中文后立马点击 “?123” 进入符号键盘点击最上方数字栏，会进行看不见候选词的选词操作而不是期望的输入数字。

**Comment by rocka** [comment]
这里的“数字键盘”对应的是桌面键盘的数字小键盘区，对应 `KP_*` 系列的按键；而`?123` 符号键盘上的数字对应的是桌面键盘字母键区上的那一行数字键。所以从某种意义上也能算是 working as intended ，但其实又不是，因为虚拟键盘根本没必要这么分。

总之还是等 fcitx5 的虚拟键盘 API 出来再说 ...

**Comment by berberman** [comment]
#123 引入的新符号键盘会直接提交候选词并输入数字。
