### ISSUE TITLE
在用物理键盘输入时，一些字母会从预选框里逃出来

### ISSUE THREAD

**Issue by ikmjssc** [fcitx5-android/fcitx5-android#128]
例如，y请问你在打字的时候z有没有u莫名出现一些夹在句子里的字母？a就像我打的这句话。

复现：快速重复敲打实体键盘上的任意两个字母。环境：los19.1 蓝牙键盘 自然码双拼

**Comment by rocka** [comment]
maybe related to aa0fdab

**Comment by rocka** [comment]
should be fixed by 5581203
