### ISSUE TITLE
配置输入法丢失

### ISSUE THREAD

**Issue by dhdiu** [fcitx5-android/fcitx5-android#132]
有时重启后配置过的输入法恢复成英语和拼音

**Comment by dhdiu** [comment]
English启用单词提示默认打开，这个设置也会恢复

**Comment by rocka** [comment]
重启恢复默认输入法之后，在开发者设置里面把日志导出一下传上来吧。我这里没法复现。

**Comment by dhdiu** [comment]
重启后需要几秒后自动加载已设置配置
