### ISSUE TITLE
指定方向选择功能部分场景无法使用

### ISSUE THREAD

**Issue by dhdiu** [fcitx5-android/fcitx5-android#137]
向左选择<|
向右选择>|
无法选择其他行的内容只能选择到这一行的最左边或最右边
wps等文本编辑器内点击<|和>|后无反应

**Comment by rocka** [comment]
<kbd>|<</kbd> <kbd>>|</kbd> 这两个按键分别是模拟发送物理键盘上的 <kbd>Home</kbd> <kbd>End</kbd> ，至于到底是什么效果，要看应用自己怎么处理。

**Comment by dhdiu** [comment]
如果行数很多的话，向上选择会很慢，可否建议增加一键选择功能

**Comment by dhdiu** [comment]
请问安卓有办法实现选择指定位置的文本吗

**Comment by WhiredPlanck** [comment]
> 请教安卓有办法实现向指定方向选择文本甚至在两个字之间选择吗

理论上是可行的，但是这些需求安卓几乎没有官方 API 可以实现，大概率是要自己写 …… 以我自己的思路来讲，会比较复杂
