### ISSUE TITLE
按快了容易漏键

### ISSUE THREAD

**Issue by tigerinput** [fcitx5-android/fcitx5-android#141]

**Comment by tigerinput** [comment]
https://user-images.githubusercontent.com/115606953/197189563-e57abbec-cb41-43a3-a19d-1f29977e4437.mp4

**Comment by rocka** [comment]
这个问题出现的频率有多高？

**Comment by tigerinput** [comment]
很高。打快了，几乎两三个字就要错一个。

**Comment by lilydjwg** [comment]
难道这就是我换了 fcitx5-android 总觉得比之前更容易按错了的原因？

**Comment by tigerinput** [comment]
提供个思路。比如打ab，如果a key_up与b key_down同时发生时，就会丢键。

https://user-images.githubusercontent.com/115606953/197193174-1cf56dc9-e70e-4090-b04a-591abdbacc6d.mp4

**Comment by lilydjwg** [comment]
那没错了。你这最后一个图里跟我平时遇到的一模一样……

**Comment by rocka** [comment]
https://user-images.githubusercontent.com/13914967/197194325-ae4c4329-9e89-4fcc-bd69-00d6fe7aec9b.mp4

为什么我复现不了啊，是我手速不够快吗？

**Comment by kamabokowen** [comment]
安卓11，魅族18Pro，Flyme 9.3，可以复现这个问题，请看视频，出问题的地方进行了10倍慢放。

https://user-images.githubusercontent.com/48863130/197325882-a4082d2c-514b-49be-8a94-d933c663b8f0.mp4

**Comment by rocka** [comment]
@tigerinput 提供的视频和 @kamabokowen 的视频中表现出的问题似乎并不是相同的。

![image](https://user-images.githubusercontent.com/13914967/197812389-a50d647c-9827-4ddc-bc86-1d7f0508d5f7.png)

从前者的截图中可以发现，丢失的按键并没有出现 popup ，也就是连 keydown 都没机会触发。

![image](https://user-images.githubusercontent.com/13914967/197812240-6a7ffa10-7360-4bbd-9f9e-b04054e26869.png)

后者的截图中，丢失的按键出现了 popup ，也就是说至少 keydown 被触发了。而按键丢失的原因是在按下后触点发生了移动，其中心偏移到了按键的 bounding box 之外，致使抬起时未能触发 click 动作。

https://github.com/fcitx5-android/fcitx5-android/blob/0ae842dcee02fe174a39fa828d77924d3edbda0b/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CustomGestureView.kt#L172-L179

https://github.com/fcitx5-android/fcitx5-android/blob/0ae842dcee02fe174a39fa828d77924d3edbda0b/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CustomGestureView.kt#L198-L204

https://github.com/fcitx5-android/fcitx5-android/blob/0ae842dcee02fe174a39fa828d77924d3edbda0b/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CustomGestureView.kt#L104-L106

后者的问题已经在 https://github.com/fcitx5-android/fcitx5-android/commit/035085fa90db392f0ac7bbc087fbfb927234db9f 中进行了规避，仿照 [`View#pointerInView(float,float,float)`](https://android.googlesource.com/platform/frameworks/base/+/refs/tags/android-13.0.0_r11/core/java/android/view/View.java#18727) 的方法，使用 [`ViewConfiguration#getScaledPagingTouchSlop()`](https://developer.android.com/reference/android/view/ViewConfiguration#getScaledPagingTouchSlop()) 的数值增加对点按时移动的宽容度。

至于前者的问题，目前还不清楚如何解决。

**Comment by rocka** [comment]
> 提供个思路。比如打ab，如果a key_up与b key_down同时发生时，就会丢键。
> 
>  22-10-21-20-12-17.mp4

@tigerinput 问一下这个视频里用的手机是 vivo OriginOS 系统吗？

**Comment by rocka** [comment]
should be fixed by ac5e97b
