### ISSUE TITLE
[Feature] Hope to add emoji keyboard / 希望可以增加emoji表情符号键盘

### ISSUE THREAD

**Issue by kamabokowen** [fcitx5-android/fcitx5-android#142]
![e98211b5dc398b340a7db92e3205b38](https://user-images.githubusercontent.com/48863130/197705687-14d9278d-9507-4e3c-98a4-413b916ac42a.jpg)

形式如Gboard这样的，可以分类选择Emoji表情。
目前最新的版本是2022年9月发布的Emoji 15.
Such as Gboard, you can select Emoji emoji by category.
The latest version: Emoji 15 is released in September 2022

**Comment by berberman** [comment]
Implemented in 34b0f8d54b34d5dc15f5b7d09a60028341bf2ac3
