### ISSUE TITLE
能否和Trime共用一套键盘前端呢

### ISSUE THREAD

**Issue by QiangF** [fcitx5-android/fcitx5-android#149]
感觉键盘布局大同小异。

**Comment by WhiredPlanck** [comment]
> 感觉键盘布局大同小异。

同文输入法活跃贡献者前来指正，同文和 fcitx5-android 底下的实现实际上大相径庭，就可以说是完全不同。大同小异只是表面上的、片面的感觉，两者目前是走不到一块去的。所以这个问题的答案目前是否。
