### ISSUE TITLE
Enlarge tapping areas for A and L keys

### ISSUE THREAD

**Issue by wzyboy** [fcitx5-android/fcitx5-android#152]
In QWERTY layout, there are gaps to the left of A key and to the right of L key. In Gboard and Trime, these gaps are valid tapping areas as well. It would decrease tapping error if Fcitx5 for Android allows tapping in these gaps.

**Comment by zhongkechen** [comment]
经常按不到A和L

**Comment by oldherl** [comment]
No. The visual key size should match the actual size, or it would be very confusing. Pressing a blank area should just do nothing.

**Comment by mokapsing** [comment]
> 

can't agree more, I used to be confused about the behavior on trime
