### ISSUE TITLE
希望能关闭语言切换键

### ISSUE THREAD

**Issue by Dustin-Hayes-Hong** [fcitx5-android/fcitx5-android#155]
![Screenshot_20221121_114125](https://user-images.githubusercontent.com/78560143/202961119-1f0fbc7f-b406-4328-8e76-5e816816b68d.jpg)
![qq_pic_merged_1669002055567](https://user-images.githubusercontent.com/78560143/202961132-5f020924-7701-4a84-9766-d8b64aaf2a21.jpg)
中间对齐有时候更方便双手打字

**Comment by chwt163** [comment]
建议把语言切换键放到工具栏。

**Comment by chwt163** [comment]
建议把语言切换键放到工具栏。

**Comment by chwt163** [comment]
或者像百度输入法那样，空格键右侧再多放一个问号键，来保持空格键的居中。
空格键也确实没必要搞得这么长。

**Comment by archytasos** [comment]
反对，我就是因此删掉了trime。

**Comment by lilydjwg** [comment]
这个现在可以通过选项去掉了。

**Comment by lilydjwg** [comment]
空格键能用来移动光标，长点好。

**Comment by rocka** [comment]
closed by c168829
