### ISSUE TITLE
英文输入法支持首字母自动大写

### ISSUE THREAD

**Issue by zhongkechen** [fcitx5-android/fcitx5-android#156]
句首字母自动大写是一般英文输入法都支持的功能。如果没有这个功能的话，还不如把英文输入法从fcitx中删掉，直接使用系统英文输入法更方便。

**Comment by WhiredPlanck** [comment]
英语键盘是默认键盘，无法删除。如果我猜对的话，你可能是不喜欢目前的单词提示，可以在 输入法 -> English -> 小齿轮 转入的设置页面中将“启用单词提示”关闭。

**Comment by zhongkechen** [comment]
不，这个功能叫 Auto Capitalization，即句首字母自动大写，这是需要的功能。

**Comment by rocka** [comment]
这并不是一个很容易实现的功能。要根据上下文自动大写，首先要实现 surrounding text ，但 fcitx5 的 [SurroundingText](https://github.com/fcitx/fcitx5/blob/5.0.20/src/lib/fcitx/surroundingtext.h) 要求同步更新，而 Android 的 [getSurroundingText](https://developer.android.com/reference/android/view/inputmethod/InputConnection#getSurroundingText(int,%20int,%20int)) / [getTextBeforeCursor](https://developer.android.com/reference/android/view/inputmethod/InputConnection#getTextBeforeCursor(int,%20int)) / [getTextAfterCursor](https://developer.android.com/reference/android/view/inputmethod/InputConnection#getTextAfterCursor(int,%20int)) 都需要耗费 IPC 往返的时间。另外还需要在键盘与 fcitx5 之间同步大写锁定状态的功能，也就是让 fcitx5 控制键盘布局的 API ，这些都没有实现。

**Comment by sihuan** [comment]
> 句首字母自动大写是一般英文输入法都支持的功能。如果没有这个功能的话，还不如把英文输入法从fcitx中删掉，直接使用系统英文输入法更方便。

1. 并不是每个人都需要句首字母大写
2. 使用系统输入法会导致输入法主题不一样
3. 实现此功能并不容易 https://github.com/fcitx5-android/fcitx5-android/issues/156#issuecomment-1322883436
4. 有手动删除 fcitx 英文键盘的方法 https://github.com/fcitx5-android/fcitx5-android/issues/157#issuecomment-1322874790

**Comment by zhongkechen** [comment]
> 对于必须要句首大写并接受英文输入使用系统输入法的用户可以选择手动删除 fcitx 的英文键盘。如果想兼得两者，帮助开发可能是最快的方法～

如何手动删除fcitx的英文键盘？

**Comment by sihuan** [comment]
> > 对于必须要句首大写并接受英文输入使用系统输入法的用户可以选择手动删除 fcitx 的英文键盘。如果想兼得两者，帮助开发可能是最快的方法～
> 
> 如何手动删除fcitx的英文键盘？
你回复的这条消息里已经给出了链接😶

**Comment by sihuan** [comment]
> > > 对于必须要句首大写并接受英文输入使用系统输入法的用户可以选择手动删除 fcitx 的英文键盘。如果想兼得两者，帮助开发可能是最快的方法～
> > 
> > 
> > 如何手动删除fcitx的英文键盘？

你回复的这条消息里已经给出了链接no_mouth
