### ISSUE TITLE
希望能增加笔顺输入法

### ISSUE THREAD

**Issue by chwt163** [fcitx5-android/fcitx5-android#159]
这里有笔顺输入法的码表：
https://www.oschina.net/p/stroke-seq_mb

**Comment by rocka** [comment]
建议使用 [fcitx5-table-extra](https://github.com/fcitx/fcitx5-table-extra) 中的 T9 (Stroke) ，也是横竖撇捺折

https://github.com/fcitx/fcitx5-table-extra/blob/master/tables/t9.conf.in

**Comment by chwt163** [comment]
> 建议使用 [fcitx5-table-extra](https://github.com/fcitx/fcitx5-table-extra) 中的 T9 (Stroke) ，也是横竖撇捺折
> 
> https://github.com/fcitx/fcitx5-table-extra/blob/master/tables/t9.conf.in

这样是九宫格键盘还是全键盘？

**Comment by chwt163** [comment]
添加自定义码表是跟 linux 桌面版一样吗？没找到 tables 文件夹的位置

**Comment by rocka** [comment]
> 这样是九宫格键盘还是全键盘？

目前码表不会对键盘布局产生任何影响，没有九宫格

> 添加自定义码表是跟 linux 桌面版一样吗？没找到 tables 文件夹的位置

参考 https://fcitx5-android.github.io/faq/#_2 ，没有请新建

**Comment by chwt163** [comment]
> 

谢谢！期待有九宫格。

**Comment by chwt163** [comment]
把数字键盘当成九宫格，然后把横竖撇捺折映射到数字上，是否可行？

**Comment by rocka** [comment]
码表输入法可以使用数字键作为输入码，你可以根据自己的需求定制码表。

至于自定义键盘布局的部分合并到 #109
