### ISSUE TITLE
剪贴板提示的超时时间无法调整

### ISSUE THREAD

**Issue by chwt163** [fcitx5-android/fcitx5-android#160]
调整之后，按了确定，仍然是30秒。

另外建议：如果没有使用粘帖，而是输入其他字符，则即便没有超时，也应该自动关闭剪贴板提示。

**Comment by rocka** [comment]
https://github.com/fcitx5-android/fcitx5-android/blob/5d32bf273ce8892e934ae2dc32d53f0aad4b8a1c/app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt#L220-L227

30s 是最小值，范围是 30~300

另外这个超时之后会进入超时状态，收起键盘或者打开工具栏后会自动关闭，如果一直放着不动就不会关闭。

**Comment by rocka** [comment]
不过既然都做成文本框了，可以把范围再放得宽一些

**Comment by lilydjwg** [comment]
不该。我经常在复制完成之后、粘贴前还输入些东西。比如先打开 GitHub 再搜函数名，或者先敲 wget 再粘贴网址。

**Comment by rocka** [comment]
should be fixed by https://github.com/fcitx5-android/fcitx5-android/commit/ee2a3cb2bf756dd2ca41f47774fa39522acbf628#diff-52ee3701e9584f49809666225325f18960a51c5c18b4035c853e13508f8c0e79
