### ISSUE TITLE
蓝牙键盘输入时空格键异常

### ISSUE THREAD

**Issue by lemon7z** [fcitx5-android/fcitx5-android#165]

**Comment by lemon7z** [comment]
刚才又试了下，似乎是自定义码表出的问题，默认拼音是连键盘没有复现。
奇了，在网页输入没问题，wps输入的时候，按了空格之后，输入一个字母就自动提交了，两个以上的字都输不了，按几下空格就会提交几个字，之后才能正常输入。

**Comment by lemon7z** [comment]
刚才又试了下，wps可以复现，连接键盘后连软键盘输入都有问题
vivo自带的浏览器地址栏、便签、x浏览器没能复现

**Comment by lemon7z** [comment]
![Screenshot_2022_1212_033150](https://user-images.githubusercontent.com/8458065/206924906-a44bdb39-5ac7-4f64-a520-e06bd66c2919.gif)

**Comment by rocka** [comment]
建议关闭嵌入式预编辑（设置-全局选项-在程序中显示预编辑文本），尤其是在这种富文本编辑器里。

WPS 在 `onUpdateSelection` 和 `onUpdateCursorAnchorInfo` 中汇报的光标位置不一致，并且后者的位置是完全错误的 `[-1, -1]` ，导致输入法无法判断光标位置。

**Comment by rocka** [comment]
f6846a2 中更改了判断光标位置的方式，开启嵌入式预编辑也不会再出现这种问题了
