### ISSUE TITLE
希望增加 Rime 支持

### ISSUE THREAD

**Issue by xz-dev** [fcitx5-android/fcitx5-android#166]
这样就能和电脑同步词库了

**Comment by zhouqiw** [comment]
或者有转换功能，这样就更完美了

**Comment by mokapsing** [comment]
附议

**Comment by WhiredPlanck** [comment]
想用 Rime 为何不来同文呢？有什么 Bug 欢迎反馈：https://github.com/osfans/trime/issues

**Comment by lilydjwg** [comment]
词库转换起来应该不难的。

**Comment by mokapsing** [comment]
> 想用 Rime 为何不来同文呢？有什么 Bug 欢迎反馈：https://github.com/osfans/trime/issues

目前在用同文，但是感觉同文像是一位年迈的老人了，混身充满了小毛病，很难恢复青春了。

这里无意伤害同文的开发者，他们尽力了，不过感觉同文感觉是很难有什么大的改善了，不得不承认，安卓和win的前端正在没落，也许单一的前端很难维持，将rime当成某个输入法其中的插件来做，或许能走的更远

所以希望fcitx-rime被带到fcitx5-android上来

**Comment by mokapsing** [comment]
> @mokapsing 我就是同文目前（唯一）的活跃开发者，有啥问题你就在同文的 Issue 反馈 ～ 目前同文正在经历较大程度的重构，前几天刚过了一轮集中 Bug 修复。

我是群里扯淡的那个（某一个），我知道你在努力中，但我也希望会有另一个新坑，毕竟离开的开发者太多了，担心有一天同文也会停下来，然后没有替代品可用

如果fcitx5-android-rime有了，那你也可以不用一个人那么辛苦搞同文，和其他的开发者一起在新坑作战
