### ISSUE TITLE
希望增加中文输入分词功能

### ISSUE THREAD

**Issue by Richard2091** [fcitx5-android/fcitx5-android#168]
例如输入`饥饿`，拼音是`ji'e`

**Comment by Richard2091** [comment]
虽然有模糊音，但分词更准确一些。
而且在输入时，大写是没有作用的 
![Screenshot_20221219-100227_Via](https://user-images.githubusercontent.com/53105011/208333764-f9bf8407-7d78-49c9-b06a-a12b54ae3faf.png)

**Comment by Richard2091** [comment]
抱歉，才发现可以使用 `'` 符号来分词

**Comment by monologconnor** [comment]
可否增加设置选项，在中文输入时将shift键（大小写键）替换为分词键呢
