### ISSUE TITLE
软件崩溃报错

### ISSUE THREAD

**Issue by Richard2091** [fcitx5-android/fcitx5-android#169]
在使用 [米窗](https://github.com/sunshine0523/Mi-FreeForm) 的小窗口时有几率导致输入法崩溃，使用其他输入法没有遇到过。
附上两次崩溃的日志：
[org.fcitx.fcitx5.android-2022-12-21T11_32_06Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/10277282/org.fcitx.fcitx5.android-2022-12-21T11_32_06Z.txt)
[org.fcitx.fcitx5.android-2022-12-21T05_33_43Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/10277284/org.fcitx.fcitx5.android-2022-12-21T05_33_43Z.txt)

**Comment by rocka** [comment]
根据日志信息来看，应该已经在 2b7e694 7cd1b8e 修复过了。请更新到最新的 CI 构建版本。

https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/

**Comment by Richard2091** [comment]
> 根据日志信息来看，应该已经在 [2b7e694](https://github.com/fcitx5-android/fcitx5-android/commit/2b7e6949f4aa1718676d44956464359f2037f4f7) [7cd1b8e](https://github.com/fcitx5-android/fcitx5-android/commit/7cd1b8ec4dc4040d7b2a13a8f92a9ff8f6aa14b3) 修复过了。请更新到最新的 CI 构建版本。
> 
> https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/

安装试了一下，的确已经修复了，不好意思
