### ISSUE TITLE
安卓13无法创建table和inputmethod文件夹

### ISSUE THREAD

**Issue by lidawei97688** [fcitx5-android/fcitx5-android#171]
各种文件管理器都试了，就连系统内置的文件访问UI都不行，难道只能root了之后才行吗?

**Comment by lidawei97688** [comment]
如果可以的话建议内置一个文件管理模块，能导入和删除就行，按安卓这个说法这些文件夹属于隐私区域，那么自己的文件自己管理总行了吧？

**Comment by rocka** [comment]
用系统文件管理器（ Documents UI ），打开侧边栏，选择“小企鹅输入法5”，可以直接操作 Documents Provider

<img src="https://user-images.githubusercontent.com/13914967/210503228-d7a95498-74e3-4bfa-a64f-e31fcd316ad4.png" width="360">
