### ISSUE TITLE
添加自定义短语功能

### ISSUE THREAD

**Issue by superLei** [fcitx5-android/fcitx5-android#174]
比如输入qq , 输出100000

**Comment by rocka** [comment]
建议使用 QuickPhrase 快速输入，触发方式是长按逗号之后右划，或者拼音输入法中按 v 触发。在设置界面 插件-快速输入-编辑器 中可以自定义映射。

输入任意字符输出任意短语的这种“自定义短语“，目前不考虑 https://github.com/fcitx/fcitx5/issues/270

但如果输入的是合法全拼，可以使用自定义词库的方式实现。
