### ISSUE TITLE
do you knowe chinese?

### ISSUE THREAD

**Issue by zhouqiw** [fcitx5-android/fcitx5-android#180]

**Comment by zhouqiw** [comment]
your project is very good, but it not build my word library;

**Comment by WhiredPlanck** [comment]
> your project is very good, 

Thank you for your kindness.

> but it not build my word library;

But I still don't understand what are you talking about.

**Comment by WhiredPlanck** [comment]
如果中文才是你的母语的话，你可以直接打中文。
