### ISSUE TITLE
[建议]组件化实现插件

### ISSUE THREAD

**Issue by mokapsing** [fcitx5-android/fcitx5-android#181]
如题，我在玩路由器固件时，有些作者搭建了在线编译打包的网站，可以让用家在其网站上勾选需要包含的组件，再点击下载后生成对应的包，如果没有更好的办法处理安卓上的插件，建议参考这种方式。

**Comment by rocka** [comment]
插件系统在计划中，但不会是在线生成安装包这种形式。
