### ISSUE TITLE
输入数据相关文件的存储路径

### ISSUE THREAD

**Issue by cyeec11** [fcitx5-android/fcitx5-android#184]
经观察，目前输入法会自动在`/storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/pinyin/`目录下，生成`user.dict`与`user.history`文件，分别记录**用户词典**和**输入历史**。

而该路径在Android10及以下的系统中，可被第三方APP任意访问，存在 ~~较大~~ 一定的 隐私泄露风险.

鉴于当前仍有较大比例用户的ROM基于Android10及以下系统，提议更改默认存储路径或方式。

**Comment by rocka** [comment]
存到私有应用数据就不方便导入导出数据，存到外部数据区域就被说有隐私泄漏风险，那你说怎么办好呢？

**Comment by cyeec11** [comment]
（啊啊啊 我使用“隐私泄露风险”一词没有冒犯的意思，初衷仅是单纯探讨，如果造成了可能存在的误解，在这里先道个歉，真心很感谢项目各位开发者的付出！）

对于 `user.dict` 可以考虑通过新增“导出导入功能”来进行控制？ 如果不考虑词典云同步场景，`user.dict` 的使用频率一般在更换设备时，这样用户可以选择在拷贝后删除文件来保护隐私。

另可将云同步作为一个单独的功能开关，用户可自定义 `user.dict` 的外部存储路径，以实现词典云同步。

`user.history` 若是记录输入历史，可移入私有的应用数据区域？

**Comment by WhiredPlanck** [comment]
> （啊啊啊 我使用“隐私泄露风险”一词没有冒犯的意思，初衷仅是单纯探讨，如果造成了可能存在的误解，在这里先道个歉，真心很感谢项目各位开发者的付出！）
> 
> 对于 `user.dict` 可以考虑通过新增“导出导入功能”来进行控制？ 如果不考虑词典云同步场景，`user.dict` 的使用频率一般在更换设备时，这样用户可以选择在拷贝后删除文件来保护隐私。
> 
> 另可将云同步作为一个单独的功能开关，用户可自定义 `user.dict` 的外部存储路径，以实现词典云同步。
> 
> `user.history` 若是记录输入历史，可移入私有的应用数据区域？

fcitx5-android 的目前隐私策略中有不联网的条款，因此不存在所谓的“云同步”。保存路径也不是作为前端的 fcitx5-android app 本身决定的，而是作为输入法后端的 fcitx5 输入法框架（或者其引擎/插件）决定的。fcitx5 本身是 Linux 系统下的电脑输入法框架，Linux 没有 Android 下那么多五花八门的要求，为了 Android 而去改动，我个人觉得不太值得。

**Comment by cyeec11** [comment]
> > （啊啊啊 我使用“隐私泄露风险”一词没有冒犯的意思，初衷仅是单纯探讨，如果造成了可能存在的误解，在这里先道个歉，真心很感谢项目各位开发者的付出！）
> > 对于 `user.dict` 可以考虑通过新增“导出导入功能”来进行控制？ 如果不考虑词典云同步场景，`user.dict` 的使用频率一般在更换设备时，这样用户可以选择在拷贝后删除文件来保护隐私。
> > 另可将云同步作为一个单独的功能开关，用户可自定义 `user.dict` 的外部存储路径，以实现词典云同步。
> > `user.history` 若是记录输入历史，可移入私有的应用数据区域？
> 
> fcitx5-android 的目前隐私策略中有不联网的条款，因此不存在所谓的“云同步”。保存路径也不是作为前端的 fcitx5-android app 本身决定的，而是作为输入法后端的 fcitx5 输入法框架（或者其引擎/插件）决定的。fcitx5 本身是 Linux 系统下的电脑输入法框架，Linux 没有 Android 下那么多五花八门的要求，为了 Android 而去改动，我个人觉得不太值得。

并非指 fcitx5-android 额外联网实现云同步功能，只需用户词典暴露在外部数据区中，用户可通过坚果云、Dropbox 或foldersync 等搭配实现多端词库同步。
