### ISSUE TITLE
背景的透明部分不会暗化

### ISSUE THREAD

**Issue by TTsdzb** [fcitx5-android/fcitx5-android#186]
# 如何复现

1. 找一张有透明部分的图片
2. 选择该图片添加主题
3. 拖动亮度条，观察图片的透明区域

# 现象

图片的透明部分没有被暗化，仍为纯白底色。

# 预期结果

图片的透明部分（即底色）应当被一起暗化。

**Comment by TTsdzb** [comment]
# 版本

0.0.3-68-g45bdac14-release

**Comment by rocka** [comment]
因为不想压缩图片，所以导入的图片都是按照 PNG 格式存的，就保留了透明通道，当时没考虑到这个问题。

**Comment by rocka** [comment]
透明区域实际上并不是“纯白底色”，而是输入法窗口后面的应用的颜色，所以如果找一张半透明的图片当背景，是能透出键盘后面的界面的

![Screenshot_20231217-225426_Trebuchet](https://github.com/fcitx5-android/fcitx5-android/assets/13914967/ba56d6dc-61a4-41a3-9eeb-017c4d7ac231)

不过（半）透明的地方没有被 ColorFilter 处理到，确实是个问题 ...

**Comment by rocka** [comment]
透明区域实际上并不是“纯白底色”，而是输入法窗口后面的应用的颜色，所以如果找一张半透明的图片当背景，是能透出键盘后面的界面的

![Screenshot_20231217-225426_Trebuchet](https://github.com/fcitx5-android/fcitx5-android/assets/13914967/ba56d6dc-61a4-41a3-9eeb-017c4d7ac231)

不过（半）透明的地方没有被 ColorFilter 处理到，确实是个问题 ...

**Comment by rocka** [comment]
should be fixed by 34ee814
