### ISSUE TITLE
希望增加笔画过滤

### ISSUE THREAD

**Issue by Brx86** [fcitx5-android/fcitx5-android#188]
fcitx5 linux版有笔画过滤，在拼音输入同音字的时候，可以用笔画辅助筛选，而android版目前没有类似功能
![Screenshot_2023-01-30_14-30-19](https://user-images.githubusercontent.com/44391900/215404967-652b63a1-9906-40b1-9dc1-c8986ce31231.png)
![Screenshot_20230130_143146](https://user-images.githubusercontent.com/44391900/215404969-268f4d01-debd-4e97-8c5a-05b40178a8df.jpg)

**Comment by Brx86** [comment]
希望在展开候选栏时可以加入笔画过滤（图为百度输入法）
![图片](https://user-images.githubusercontent.com/44391900/215405428-e86fadf7-e9e1-4ce8-a3b9-5f096fbd9284.png)

**Comment by rocka** [comment]
长按 <kbd>z</kbd> 键，然后选择 <kbd>`</kbd> 即可。

<img src="https://user-images.githubusercontent.com/13914967/215405706-1ee6e434-8454-4233-8ef3-fdf7da979960.png" width="360">

如果你想自己配置快捷键，需要在高级设置里关闭“隐藏快捷键配置”。
