### ISSUE TITLE
建议：增加分号（；）在主键盘或数字键盘内

### ISSUE THREAD

**Issue by Meavel** [fcitx5-android/fcitx5-android#190]
在某些输入法，如：半分输入法，行列40，微软双拼，都需要用到分号。本人已经在半分输入法的conf和txt档内增加分号的码表，可是无法成功运行。建议主要在字母区中增加，因为打字需要配合英文字母a-z。
(Label: enhancement)

**Comment by rocka** [comment]
合并到 #109 由输入法引擎决定键盘布局（九宫格，独立数字行，分号等）
