### ISSUE TITLE
按键上显示标点干什么？

### ISSUE THREAD

**Issue by sonichy** [fcitx5-android/fcitx5-android#193]

**Comment by rocka** [comment]
长按，或者下划（可以在键盘设置中更改为上划），可以快速输入标点符号。很多输入法都有类似的功能，否则输入标点符号还需要切换到符号键盘，过于繁琐了。

**Comment by sonichy** [comment]
空间有限，太乱了，做个设置隐藏。

**Comment by WhiredPlanck** [comment]
为什么语气这么不客气？这里没有人欠你的钱 ……

**Comment by dqwyy** [comment]
按键上显示标点是世界上绝大多数输入法的设计，且是一个非常优秀的设计
