### ISSUE TITLE
希望支持[锁定当前输入模式]

### ISSUE THREAD

**Issue by yiteei** [fcitx5-android/fcitx5-android#197]
总是自动切换到En输入模式，很多输入法都没有，多一个功能多一个选择

**Comment by rocka** [comment]
其实是支持的，在全局选项里，把“共享输入状态”设置为“所有”就可以了，这样只要输入法进程不被杀掉，就会一直记住上次用过的输入模式。

剩下的两个选项“程序”和“否”在手机上的作用几乎是相同的，就是为每个 App 单独记住输入法状态。比如在词典里查单词用英文输入法，切到便签里打字用拼音，再切回词典，仍然是英文输入法。
