### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by Celestialpppo** [fcitx5-android/fcitx5-android#203]
1.拼音muo会识别为mu o，导致“抹”字打不出来。

2.点击拼音光标会移动，但是点击退格当前字母不会删除而是从最后一个输入的字母开始删除。

不知道是不是我的问题，有意见烦请指正。

**Comment by wengxt** [comment]
@Celestialpppo 抹 的拼音是 mo。

**Comment by rocka** [comment]
第二个问题，应用内预编辑（输入中的拼音串）是默认关闭的，同时点击预编辑串移动光标也是默认关闭的。如果需要这个功能，请在 高级 设置中关闭 忽略系统光标位置 (Ignore system cursor position)。

https://fcitx5-android.github.io/faq/#_5

**Comment by Celestialpppo** [comment]
> @Celestialpppo 抹 的拼音是 mo。

文化沙漠了属于是，可能是我们那边方言问题

**Comment by Celestialpppo** [comment]
> 第二个问题，应用内预编辑（输入中的拼音串）是默认关闭的，同时点击预编辑串移动光标也是默认关闭的。如果需要这个功能，请在 高级 设置中关闭 忽略系统光标位置 (Ignore system cursor position)。
> 
> https://fcitx5-android.github.io/faq/#_5

好的谢谢大佬
