### ISSUE TITLE
希望能添加自定义按键功能，如长按或上滑为“全选”等，并能自定义按键的上下滑或长按出来的字符

### ISSUE THREAD

**Issue by lanyun712** [fcitx5-android/fcitx5-android#208]
用了同文的长按或上滑 a 、x、c、v ，对应为 全选、剪切、复制、粘贴，方便不少，希望能添加此功能。还有就是下滑（上滑）符号，要是能自定义也是最好的，毕竟每个人常用的符号都不一样，把自己常用符号编辑上去效率又会高不少。最好是能自定义键盘布局，已看到前面有人提过添加九键的问题，知道若要实现上述功能不易，这里先占个坑，希望大佬们有空有精力时再慢慢完善。

**Comment by rocka** [comment]
合并到 #109

**Comment by ChaunceySheng** [comment]
希望可以自由设定长按字母键出现的候选字符列表。
