### ISSUE TITLE
码表输入法（如五笔）关闭“自动选择候选词之后提交”选项后唯一候选词点空格让词条上屏会多一个空格上屏

### ISSUE THREAD

**Issue by lanyun712** [fcitx5-android/fcitx5-android#209]
如题，试了其它码表输入法都一样，只要关了这个选项只要候选词条是唯一的，注意是候选词条是唯一时，点空格让该词条上屏就会在词条后面多上屏一个空格。如选“五笔字型”方案，打"方法"，编码为 yyif ，打完四码再空格上屏就会多一个空格，并且点按已出现的“方法”不能上屏。另外在这种情况下候选显示很奇怪，打完编码显示出的是唯一的词条时，并不是显示在下方候选栏中，而是显示在编码输出处。
版本：0.0.4-52-geda70637-release

**Comment by rocka** [comment]
建议到上游 https://github.com/fcitx/fcitx5-chinese-addons/issues 反馈， Android 端只是界面，没法控制这些东西。

**Comment by rocka** [comment]
如果你想实现：“无论候选词是不是唯一，都必须按空格才上屏“，可以把五笔设置中”选择唯一候选词的长度限制“设置为 `0` ，禁用自动选择唯一候选词的功能。默认值是 `-1` ，代表码表的最长码长（五笔是 `4` ）。
