### ISSUE TITLE
第一个候选字颜色相对其他偏暗

### ISSUE THREAD

**Issue by paopjian** [fcitx5-android/fcitx5-android#211]
示例第一个图片也是,感觉最左边的候选词颜色相对其他颜色偏灰
![示例图](https://user-images.githubusercontent.com/13914967/202180575-04b6db41-ff24-4bef-899a-8051fc0243f5.png)

**Comment by rocka** [comment]
![image](https://user-images.githubusercontent.com/13914967/223682036-382f8a27-2ead-42b6-823d-e1a658e32a65.png)

候选字的颜色是一样的
