### ISSUE TITLE
中文输入时缺少分割号

### ISSUE THREAD

**Issue by paopjian** [fcitx5-android/fcitx5-android#212]
谷歌输入法中文可以第一个字符大写,如果是小写输入,大写位置就变成了 '词, 这样就可以将词语分开
否则企鹅,这2两个字在输入法里就分不开了,还得长按z调出'

**Comment by rocka** [comment]
合并到 #109

**Comment by PapainTea** [comment]
可以通过上划或者下滑‘z’按键实现分词
