### ISSUE TITLE
布局方向为 RTL 时 popup 错误

### ISSUE THREAD

**Issue by ikmjssc** [fcitx5-android/fcitx5-android#217]
如图所示不论是什么键的popup都在最右边
![Screenshot_20230311-142443_Via](https://user-images.githubusercontent.com/59211989/224469941-a23b341f-30c8-4128-b2aa-a07bd9a44dda.png)
（顺便一提键盘布局也会变成从右往左写的，挺难受的）

**Comment by rocka** [comment]
should be fixed by 978442a
