### ISSUE TITLE
BUG：输入法设置界面通过垃圾桶图标无法删除输入方案

### ISSUE THREAD

**Issue by cabins** [fcitx5-android/fcitx5-android#221]
输入法设置界面 - 输入法 - 右上角铅笔图标 - 复选框选择一个输入法 - 点击右上角的垃圾桶，观察是否可以将输入方案删除。

预期要删除掉；
实际删除不掉。

**Comment by rocka** [comment]
此 bug 已在 872eb9a 修复，但还没有发布新版本。可以在 Jenkins CI 下载 master 分支的构建： https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/
