### ISSUE TITLE
疑惑：这个输入法软件竟然出现了网络数据用量 Issue: This input method App is already using network data

### ISSUE THREAD

**Issue by Ching0Hsu** [fcitx5-android/fcitx5-android#222]
手机型号：Google Pixel 6
Android版本号：13

问题描述：我是昨天上午不经意发现这个好用且开源的简体中文输入法，它运行顺畅而且对权限请求非常克制，也不需要网络的存取权限，但是昨天晚上我检视网络数据用量时发现它使用了多达584MB的数据用量，我非常奇怪一个没有网络存取权限的应用如何使用网络数据。
这部手机只用于工作上的联系与突发公事处理，尽可能只使用F-Droid上架的软件并运行GrapheneOS，似乎可排除是手机方面的问题，遍寻网络后只找到一个有点相关的讨论，所以想请问大家是否能提供我任何建议或指引，让我排除这个相当困惑的问题，谢谢您的任何帮助。

![Screenshot_20230319-082809](https://user-images.githubusercontent.com/128265729/226147690-3bf33680-652d-4d49-a086-ad3eba86bea3.png)

可能有关的讨论：https://www.reddit.com/r/fossdroid/comments/hu1k4p/app_without_internet_access_use_internet_data/

**Comment by oldherl** [comment]
如果你确定没有从其他下载渠道下载到了一个被恶意修改的第三方版本的话，那么你大概应该研究一下是不是GrapheneOS的统计bug

**Comment by WhiredPlanck** [comment]
首先可以肯定的是，fcitx5-android 既无申请任何联网权限，也无任何与联网有关的代码逻辑。fcitx5-android 官方发布在各个平台上的 app 都是由编译机自动拉取 GitHub 上的开源的代码并自动构建的。个人角度上，我首先怀疑是系统流量统计有缺陷，比如可能系统错误地将使用输入法时的背景应用（比如 IM 应用：微信、QQ 等）所使用的流量统计在了输入法上。

**Comment by Ching0Hsu** [comment]
> 如果你确定没有从其他下载渠道下载到了一个被恶意修改的第三方版本的话，那么你大概应该研究一下是不是GrapheneOS的统计bug

谢谢您的回应，我确定这个输入法软件是下载于F-Droid，也确定它拥有的权限并不包括网络存取，所以才感觉困惑。
![Screenshot_20230319-094650](https://user-images.githubusercontent.com/128265729/226149312-8817e405-e5bb-4711-b0f9-907c40d3cfc7.png)
![Screenshot_20230319-094725](https://user-images.githubusercontent.com/128265729/226149318-c76b3f68-87fc-447e-92c6-4dfd1bcea44a.png)

**Comment by Ching0Hsu** [comment]
> 首先可以肯定的是，fcitx5-android 既无申请任何联网权限，也无任何与联网有关的代码逻辑。fcitx5-android 官方发布在各个平台上的 app 都是由编译机自动拉取 GitHub 上的开源的代码并自动构建的。个人角度上，我首先怀疑是系统流量统计有缺陷，比如可能系统错误地将使用输入法时的背景应用（比如 IM 应用：微信、QQ 等）所使用的流量统计在了输入法上。

是的，我目前也在朝您对于系统统计有缺陷的假设去观察。
GrapheneOS以隐私安全且目前仅为Pixel系列手机量身打造而小有名气，因为服务的手机相对单一，差异性不大，本来没去考虑会有这样的错误。

**Comment by Ching0Hsu** [comment]
目前仍持续观察流量使用，过几天回报最新情况。

**Comment by berberman** [comment]
与项目开发无关故关闭。
