### ISSUE TITLE
缺乏对外设的适配

### ISSUE THREAD

**Issue by dyron503** [fcitx5-android/fcitx5-android#225]
在使用蓝牙键盘时，发现本应用未对外接接盘作出有效适配。
![Screenshot_20230324_112912_Finder](https://user-images.githubusercontent.com/78830487/227417260-1bcf19c3-e297-4795-aaa0-65db9adeb995.jpg)
在这个页面上，触控键盘没有隐藏，也无法通过数字按键进行选字，或是通过+打开翻页功能。
Gboard的效果如下，希望可以起到参考作用。
![Screenshot_20230324_112822_Finder](https://user-images.githubusercontent.com/78830487/227417825-2d68f4b0-4221-40a0-96c6-fc327f105b71.jpg)

总的来说，希望可以增加如下的特性:
* 在连接蓝牙（有线）键盘时隐藏输入菜单；
* 弹出选字框；
* 通过键盘/点击进行选字；
* 通过键盘移动高亮光标和翻页。
* 许多输入法适配较差：它们提供12个（而不是键盘上的9个）备选字词，导致有几个完全无法选中。Gboard是良好适配的输入法之一。

诚挚感谢。

**Comment by rocka** [comment]
duplicate of #106
