### ISSUE TITLE
导入用户词典允许跳过错误或者支持不完整拼音

### ISSUE THREAD

**Issue by ArcanusNEO** [fcitx5-android/fcitx5-android#226]
PC上有使用ibus的libpinyin，其导出的用户词典格式与此输入法支持的格式类似，但存在类似 `包含 bao'h 5` 、 `命运石之门 ming'yun'shi'zhi'm 84` 这样不完整拼音形式的行，导入小企鹅输入法会报错。手动删除这些行不太现实，工作量太大。能否增加支持导入不完整拼音的功能？如果不行的话希望可以增加跳过错误行的逻辑。

**Comment by rocka** [comment]
建议提给上游 https://github.com/fcitx/fcitx5-chinese-addons/issues
