### ISSUE TITLE
个人词库导入导出功能

### ISSUE THREAD

**Issue by Walter-Lea** [fcitx5-android/fcitx5-android#232]
作者大大，请问后续有没有增加个人词库导入导出功能的想法呢

**Comment by rocka** [comment]
https://github.com/fcitx5-android/fcitx5-android/releases/tag/0.0.7 版加了所有应用数据的导入导出，当然包括词库

**Comment by Walter-Lea** [comment]
作者大大，我测试了一下export 功能，发现会报错，测试机器（华为mate40 pro EMUI：11.0.0.118 Android：10 ）报错信息如下：（这个crash log 点保存会显示程序崩溃，也没法复制，只能截图了）
![WechatIMG950](https://github.com/fcitx5-android/fcitx5-android/assets/47944281/9f0c9c52-f048-4e8b-b709-9a23e5ca5e93)
![WechatIMG951](https://github.com/fcitx5-android/fcitx5-android/assets/47944281/acf2f54b-89d7-4f57-9c2e-2371c9039618)
![WechatIMG949](https://github.com/fcitx5-android/fcitx5-android/assets/47944281/f6316d22-6691-4b08-86e9-1973182bc509)

**Comment by rocka** [comment]
这是 Android 标准的创建文件的方式，不知道为什么在你的设备上会出问题

https://developer.android.com/training/data-storage/shared/documents-files#create-file

你有禁用或卸载过系统应用吗？

**Comment by Oliveira-Lee** [comment]
嗷嗷那我知道为啥了，我把华为自带的文件浏览器卸载了，估计是这个原因

**Comment by rocka** [comment]
EMUI 卸载自带文件管理器需要 root 权限吗？

**Comment by Oliveira-Lee** [comment]
不用哎，我直接用的adb卸载的
