### ISSUE TITLE
german language support 

### ISSUE THREAD

**Issue by leminsc8er** [fcitx5-android/fcitx5-android#235]
german (ger)/deutsch (de) language support:
- menu
- dictionary
- layout (qwerz)
- link to wiki/source if language/aditonal not listed

**Comment by rocka** [comment]
I'm not aware of any German input method engine which works with fcitx5, and I don't know German at all so there is no chance for me to implement one.

Also there is no custom layout support in fcitx5-android yet, only the hardcoded qwerty one.
