### ISSUE TITLE
可能加入调用系统语音输入吗？这样就完美了，如果能加入手写输入就更好了

### ISSUE THREAD

**Issue by qttttttp** [fcitx5-android/fcitx5-android#239]
可能加入调用系统语音输入吗？这样就完美了，如果能加入手写输入就更好了

**Comment by oldherl** [comment]
现价段不存在自由的中文语音识别引擎。如果你想用讯飞或谷歌，请直接用它们自己的输入法。

**Comment by qttttttp** [comment]
感谢回复,这个我不懂。我想是不是可以调用系统语音引擎识别到的文字再上屏,比如miui系统的语音识别日志。我这是瞎想勿怪🤗。同文输入法可以实现,可惜门槛有点高。

**Comment by berberman** [comment]
@rocka 调用系统的 API https://developer.android.com/reference/android/speech/SpeechRecognizer 也需要联网和录音权限
