### ISSUE TITLE
边距范围内易误触

### ISSUE THREAD

**Issue by monologconnor** [fcitx5-android/fcitx5-android#243]
在设置选项`键盘`下由`键盘两侧边距`和`键盘底部边距`设定的区域在触碰时会导致所有按键失效，即在触碰边距区域时无法正常输入，尤其是曲面屏设备在抓握时极易触碰到两侧边距区域导致无法输入，希望后续版本可以忽略掉键盘背景区域的触摸事件。

**Comment by rocka** [comment]
should be fixed by 2cd7efe
