### ISSUE TITLE
Android13不能访问/Android/data/org.fcitx.fcitx5.android，无法导入自定义输入方案

### ISSUE THREAD

**Issue by niclau** [fcitx5-android/fcitx5-android#244]
我原本一直用LIME挂郑码码表，最近打算转用fcitx，根据https://github.com/fcitx5-android/fcitx5-android/issues/99 ，需要把码表放进/Android/data/org.fcitx.fcitx5.android/files/data，觉得是很简单的事情。
但发现Android13（三星S21+ ONEUI5.1）的APP不能直接访问/Android/data，导致不能把码表放进去，用三星自家的文件管理器提示需要从电脑访问。
从电脑上能访问/Android/data/org.fcitx.fcitx5.android/files/data了，但data目录是空的，手动新建table文件夹和inputmethod文件夹均提示出错，搞不懂是什么问题了?
最后提一个建议，可否像lime那样提供一个导入、导出码表的功能?谢谢

三星自带的文件管理器
![Screenshot_20230420_125926_My Files](https://user-images.githubusercontent.com/575928/233262757-db14da5a-afad-448a-b924-383f2132b1eb.jpg)

能访问/Android/data目录的my app fv file explorer，确实能访问，但不能新建目录
![Screenshot_20230420_124807_FV File Explorer](https://user-images.githubusercontent.com/575928/233262768-3e33ecd6-840d-4713-a4a0-0827d7ba36f5.jpg)

USB连接电脑，不能新建目录
![屏幕截图 2023-04-20 124038](https://user-images.githubusercontent.com/575928/233262771-c40f65f2-0a72-493e-873e-61a21c030f7b.png)

**Comment by rocka** [comment]
导入码表输入法：
https://fcitx5-android.github.io/faq/#_2

使用系统自带 DocumentsUI 访问 fcitx5 data 目录：
https://fcitx5-android.github.io/faq/#_8
