### ISSUE TITLE
优化空间占用

### ISSUE THREAD

**Issue by VitalyAnkh** [fcitx5-android/fcitx5-android#250]
![Screenshot_2023-04-22-03-55-00-090_com miui securitycenter-edit](https://user-images.githubusercontent.com/24508452/233723812-398dd11a-6492-4df1-9a3b-17554017c574.jpg)
非常棒的开源软件，希望等功能完善后考虑优化存储空间占用。

**Comment by rocka** [comment]
现在 apk 里的内容几乎都是运行时必须的，已经没什么可压的了

![image](https://user-images.githubusercontent.com/13914967/234937998-d40e3c7a-15e5-42e4-9db8-d42897b246f8.png)

当然硬要说的话还可以把几个不常用的码表（晚风、冰蝉全息、电报码）拆出来，再省个几 M

---

还有一个方向就是让 fcitx5 直接支持从 apk 中读取 assets 以及 dlopen addon library ，这样可以省下很多空间（因为不用把 assets 复制出来了）。但问题也很明显：要在 fcitx5 中写很多 `#ifdef ANDROID` ；实现很麻烦，要自己解析 zip 而不能用 ndk 的 AAsset API （因为它不支持列出目录下的目录 https://issuetracker.google.com/issues/140538113 ）；而且除了能降低存储空间占用，也并没有别的好处，反而让 Android 上的 addon 机制和别的平台上都不一样了，变相提高了维护成本。

所以我们现在不想考虑这个问题。
