### ISSUE TITLE
调用系统自带的TTS引擎

### ISSUE THREAD

**Issue by Pantyhose-X** [fcitx5-android/fcitx5-android#254]
## 调用系统自带的TTS引擎
 `输入空格`或`选择单词` 后TTS朗读单词，`输入回车键`后朗读句子。
2. 应用于语言学习。发音纠正，这样可以纠正发音和加深记忆，
3. 母语不是英语。需要学习英语，市场非常大 

例子

https://user-images.githubusercontent.com/42504385/132130706-a1a8ec10-416a-4711-b5d3-c91086e9710f.mp4

**Comment by BackMountainDevil** [comment]
系统自带了tts不是可以直接朗读吗。。关输入法啥事
