### ISSUE TITLE
 [Feature request] mozc support to input japanese

### ISSUE THREAD

**Issue by brucekomike** [fcitx5-android/fcitx5-android#256]
there is fcitx-mozc on debian-like distributions, and I used to have en, zh-hans and jp input method in a keyboard.
so how about adding mozc support ?

**Comment by rocka** [comment]
Mozc is too complicated to compile on Android, so we do not have a plan for it yet.

But meanwhile you can try the Anthy Plugin: https://jenkins.fcitx-im.org/job/android/job/fcitx5-android-plugin-anthy/

You will have to install fcitx5-android's latest CI build from https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/ to be able to use the plugin. If the plugin does not load, you may need to restart the input method. Or just install the plugin before installing input method so Android restarts it for you.

**Comment by brucekomike** [comment]
The Anthy Plugin is a great solution, which should to be mentioned somewhere.
Maybe there can be a list of availiable plug-ins ?

**Comment by ghost** [comment]
see also:  #667

**Comment by MeoCag** [comment]
mozc体验还是要好太多，我注意到fcitx5 for ios已经内置了mozc，直接把mozc编译过去实现的，或许可以试试？
