### ISSUE TITLE
实体键盘字母键在未呼出输入法且处于拼音模式时不工作

### ISSUE THREAD

**Issue by Blue-Beaker** [fcitx5-android/fcitx5-android#258]
1.接入实体键盘，并将fcitx5置于拼音模式
2.打开一个可在不呼出输入法时接受按键并做出反应的程序，如avnc vnc客户端，不要呼出输入法
3.使用实体键盘键入一些字母
此时发现这些字母并未被程序接受到。
如果切换到其他输入法，或将fcitx5置于英文模式，则可以正常使用。

输入法版本：0.0.5-0-g679ab7db-release
Android版本：9

**Comment by rocka** [comment]
should be fixed by d2714a1

please try the latest CI build: https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/25/
