### ISSUE TITLE
第一次按删除键会隐藏预测栏，而不是删除输入框中的汉字

### ISSUE THREAD

**Issue by dongguaguaguagua** [fcitx5-android/fcitx5-android#259]
版本号：0.0.5-0-g679ab7db-release
打字的时候会进行删除操作，但是第一次删除键的作用是隐藏提示栏同时显示工具栏。但是我觉得有一点点麻烦，主要是与之前用的输入法的逻辑不一样。盲猜作者大大搞删除键的这个功能主要是因为预测栏有下拉按钮，再做一个不显示按钮太占用空间。但是我觉得可以参考讯飞或者搜狗的做法，就是把预测栏做成左右滚动式的，然后一个隐藏预测栏（显示工具栏）的按钮放在最右边，这样会比较好。如果我这样的需求比较小众做成设置也可以（或者可以左右滑动切换预测栏与工具栏？）

**Comment by rocka** [comment]
原因是 fcitx 是一个桌面输入法，在桌面上基本没人会用预测，所以这部分就是随便做的。

**Comment by dongguaguaguagua** [comment]
确实，其实我对于有无预测也无所谓，并不是刚需。

**Comment by zxdposter** [comment]
@rocka 希望能像百度输入法那样，给一个删除键是否直接删除输入框汉字的选项，对于需要经常使用预测的用户来说非常有用。
