### ISSUE TITLE
可以增加粤拼吗

### ISSUE THREAD

**Issue by SpaceChung7** [fcitx5-android/fcitx5-android#261]

**Comment by rocka** [comment]
可以先尝试一下 https://github.com/fcitx/fcitx5-table-extra 里的 jyutping-table ，按照 https://fcitx5-android.github.io/faq/#_2 的步骤导入就可以。

不过 fcitx5 也是有单独的粤拼引擎的（ https://github.com/fcitx/libime-jyutping ），但移植这个并不是那么容易，需要先把 app 中的 libime 和 chinese-addons 也拆成模块。

**Comment by rocka** [comment]
#342 完成之后，有了一个新的选择：用 rime 的粤拼方案 https://github.com/rime/rime-cantonese

**Comment by rocka** [comment]
#356 粤拼引擎移植完成
