### ISSUE TITLE
在 Windows 环境下缺少 ECM 无法编译通过

### ISSUE THREAD

**Issue by Mr-Li-jc** [fcitx5-android/fcitx5-android#264]
![image](https://github.com/fcitx5-android/fcitx5-android/assets/22043213/31431981-3ed5-44ed-be51-11e7e61d5547)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/22043213/afe3c7c9-4918-4de5-aa56-f08adedaeec6)

**Comment by rocka** [comment]
按照 README.md 里的说明，还需要安装 https://github.com/KDE/extra-cmake-modules

另外，本项目的开发都是在 Linux 中进行的，此前（ #102 ）也有在 Windows 下进行编译的尝试，但最后无疾而终了。你可以自己探索一下。

**Comment by Mr-Li-jc** [comment]
苹果系统也报这个错，我已经装了这个(https://github.com/KDE/extra-cmake-modules)，而且ecm也装了，还是报跟上面Windows一样的错，难道苹果系统也不行吗？

**Comment by rocka** [comment]
> 我已经装了这个 https://github.com/KDE/extra-cmake-modules ，而且ecm也装了

链接给出的“这个”就是 ECM ，那么你说的“而且ecm也装了”到底是装了什么，怎么安装的，安装到了什么地方？

如果你确定已经安装了 ECM ，只是 cmake 找不到，可以把环境变量 `ECM_DIR` 设置成安装的路径

https://github.com/fcitx5-android/fcitx5-android/blob/2cef173c092408f42b94d2004c2d7ccc0e5bb067/lib/fcitx5/src/main/cpp/cmake/FindECM.cmake#L1-L5

默认值是按照一般 Linux 发行版的目录结构设置的，对 mac 可能不适用。可以参考 https://t.me/fcitx5_android_group/47970
