### ISSUE TITLE
关于空格键的建议

### ISSUE THREAD

**Issue by no1uvbsvname** [fcitx5-android/fcitx5-android#266]
空格键希望出一个长按就可以一直输入空格的功能了
,我以前在讯飞上用过这个.感觉非常好
小企鹅版本0.0.5-0-g679ab7db

**Comment by lilydjwg** [comment]
~~你为什么需要那么多空格~~

**Comment by no1uvbsvname** [comment]
有些时候,为了排版,需要打上空格,但是又不能换行.
比如说,打卷子的是,会有较长的一段的空白的,但是我不太喜欢用下划线

**Comment by lilydjwg** [comment]
原来如此。在手机上操作这个，辛苦了。
这种情况下我会复制比较长的空格串再粘贴、然后重复。

**Comment by no1uvbsvname** [comment]
这个方法如果需要打特别多的时候就不太适用了,

**Comment by lilydjwg** [comment]
怎么会呢？这个办法打大量空格要快多了，毕竟几何级数。

**Comment by rocka** [comment]
duplicate of #145
