### ISSUE TITLE
請增加英文dvorak佈局，以及注音輸入法

### ISSUE THREAD

**Issue by carnivion** [fcitx5-android/fcitx5-android#271]
這兩個是我最常用的輸入法了。
現在用的鍵盤（可以完全自定佈局和主題色，還有支援ctrl、alt、tab、fn等等），可是現在沒有在更新了，play商店裏面都下架，新手機不可下載，所以轉到這邊來了。謝謝開發者！
dvorak佈局排列有困難的話，我可以提供我現在的排列作爲參考。

**Comment by oldherl** [comment]
#109

**Comment by Meavel** [comment]
目前colemak配列的版本，是根据源码重新编译的，dvorak配列也可依照相同的思路对源代码重新编译成apk包。至于注音……目前已经有人提交这个事情了，就等开发者回应吧。

**Comment by rocka** [comment]
duplicate #109 #117

首先需要移植注音的引擎（ https://github.com/chewing/libchewing 和 https://github.com/fcitx/fcitx5-chewing ），其次有些注音的方案也需要自定义键盘布局。 ~但是我们真的很缺人~

**Comment by flier268** [comment]
@rocka 注音的畫面應該顯示ㄅㄆㄇ，而不是abc
另外，注音有[聲調](https://zh.wikipedia.org/zh-tw/%E6%B3%A8%E9%9F%B3%E7%AC%A6%E8%99%9F?useskin=vector#%E8%81%B2%E8%AA%BF)
