### ISSUE TITLE
在有候选词的情况下输入数字会输入候选词

### ISSUE THREAD

**Issue by Eliot00** [fcitx5-android/fcitx5-android#273]

**Comment by Eliot00** [comment]
移动端输入法用数字选候选的功能感觉是多余的

**Comment by oldherl** [comment]
然而还有其他人认为候选词条是多余的，只需要用键来选词……

**Comment by lilydjwg** [comment]
在正式支持物理键盘之前，只能这么凑合着用了。另外像 scrcpy 这种工具也可能无法作为物理键盘接入。

**Comment by Eliot00** [comment]
> 

这特性可以关吗？个人看法在手机上如果我要选词直接点候选项就好了，本身没有单独的数字栏，输数字就要长按第一排字母栏再滑动选中，结果输入的还不是数字，得删掉重来，很让人抓狂……

**Comment by oldherl** [comment]
可是如果你要输入数字，为什么会有候选词呢？你选择了候选词之后不就不会有了么

**Comment by Eliot00** [comment]
> 可是如果你要输入数字，为什么会有候选词呢？你选择了候选词之后不就不会有了么

比如我要输入“有10个苹果”，输入“有”字后，候选词第一个是这，再按下q键，滑到1，实际输入的不是1，而是“这”字

**Comment by oldherl** [comment]
> 比如我要输入“有10个苹果”，输入“有”字后，候选词第一个是这，再按下q键，滑到1，实际输入的不是1，而是“这”字
哦，所以你不要打开预测就行了

**Comment by rocka** [comment]
建议更新到最新的 CI 构建版本 https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/ 。 2cef173 已经解决（规避）了这个问题。
