### ISSUE TITLE
表情里面部分显示乱码、剪切板条目长按 图标错位

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#278]
![Screenshot_20230606-021820_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/be4da198-cc08-4887-9fc7-f109c99fe18d)
![Screenshot_20230606-021842_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/3e86d823-ec5c-4656-833c-94b121bd6e7b)

**Comment by rocka** [comment]
“乱码”是因为你的手机不支持部分 Unicode 15 的 Emoji 字符。请更新系统，或者自己换字体。
“错位”是因为你的手机系统魔改了 Android 内置的 PopupMenu 控件，导致显示有问题。正常的 Android 系统不会出现这种问题。

**Comment by JUST-INTJ** [comment]
好吧，我用的三星Android10设备。
