### ISSUE TITLE
输入时没有按键音

### ISSUE THREAD

**Issue by Moukubi** [fcitx5-android/fcitx5-android#279]
Phone：三星F52
Android Version：13
App Version： org.fcitx.fcitx5.android-0.0.5-0-g679ab7db-arm64-v8a-release.apk

**Comment by Moukubi** [comment]
有没有计划加入非系统按键音

**Comment by H1karuru** [comment]
+1

**Comment by Moukubi** [comment]
> 别，默认别整个按键音joy
> 
> 这个需要小企鹅支持自定义主题吧
> 
> 以前用过一个自带输入法的机械键盘主题，感觉也蛮有趣，就是公共场合有点尬joy

自定义按键音，和振动一样可设置成0就好了
