### ISSUE TITLE
无法删除和覆盖原有词典

### ISSUE THREAD

**Issue by CyrusYip** [fcitx5-android/fcitx5-android#280]
## 需求

目前没办法用新版本词典，希望能有删除和覆盖功能。

## 问题

我在 https://archlinux.org/packages/extra/any/fcitx5-pinyin-zhwiki/ 下载了维基百科词典。一开始下载 20230507 版本，用 ZArchiver 解压后在「输入法->拼音->词典」成功导入，名称为 zhwiki。今天下载了 20230605 版本，解压后导入提示「导入错误 词典已存在」。我也没找到删除原有词典的按钮。

<details>
<summary>报错图片</summary>

![Screenshot_20230606-173825_小企鹅输入法5](https://github.com/fcitx5-android/fcitx5-android/assets/60951091/25cb7a6b-9344-4301-9162-3a9b3741400d)

</details> 

词典：

[zhwiki-20230605.dict.tar.gz](https://github.com/fcitx5-android/fcitx5-android/files/11662905/zhwiki-20230605.dict.tar.gz)

[zhwiki-20230507.dict.tar.gz](https://github.com/fcitx5-android/fcitx5-android/files/11662910/zhwiki-20230507.dict.tar.gz)

## 软件版本

- Fcitx5 for Android：0.0.5-0-g679ab7db
- 系统： LineageOS 20（Android 13）

**Comment by rocka** [comment]
左划删除

**Comment by CyrusYip** [comment]
@rocka 谢谢！感觉在应用删除东西是长按比较多，没想到是左划，如果可以提示用户左划是删除就更好啦。

**Comment by rocka** [comment]
新版本增加了多选删除， toolbar 右侧有编辑按钮，按一下进入多选模式，同时编辑按钮会变成删除按钮。可以下载最新的 CI Build 体验一下 https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/
