### ISSUE TITLE
希望能增加词库快速部署功能

### ISSUE THREAD

**Issue by abcRiverDoc** [fcitx5-android/fcitx5-android#285]
词库修改后还需要再次挂载   太麻烦了
希望能出个快捷键，一键部署

**Comment by rocka** [comment]
挂载？部属？没看懂到底在说哪些步骤

**Comment by abcRiverDoc** [comment]
就是我修改词库以后，希望输入法里面能响应
类似小狼毫的重新部署





zzz
***@***.***









                       
原始邮件
                       
                     

发件人："rocka"< ***@***.*** &gt;;

发件时间：2023/6/18 17:35

收件人："fcitx5-android/fcitx5-android"< ***@***.*** &gt;;

抄送人："abcRiverDoc"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [fcitx5-android/fcitx5-android] 希望能增加词库快速部署功能 (Issue #285)




 
挂载？部属？没看懂到底在说哪些步骤

**Comment by abcRiverDoc** [comment]
我简单录了个屏，大佬可以参考一下
要是直接长按候选可以删除&nbsp;调整也行



zzz
***@***.***









                       
原始邮件
                       
                     

发件人："rocka"< ***@***.*** &gt;;

发件时间：2023/6/18 17:35

收件人："fcitx5-android/fcitx5-android"< ***@***.*** &gt;;

抄送人："abcRiverDoc"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [fcitx5-android/fcitx5-android] 希望能增加词库快速部署功能 (Issue #285)




 
挂载？部属？没看懂到底在说哪些步骤

**Comment by rocka** [comment]
你的录屏在哪呢？

**Comment by rocka** [comment]
> 就是我修改词库以后，希望输入法里面能响应

你用什么方式修改词库？拼音词库需要使用 `libime_pinyindict` 编译，码表词典需要使用 `libime_tabledict` 编译，都不是容易手动修改的类型。如果你想改动一个 txt 之后就让输入法自动重载词库，那就更不容易了。

**Comment by abcRiverDoc** [comment]
好的。。收到 感谢 到时积累到一定程度再修改吧。
