### ISSUE TITLE
能否用下面的逗号跟句号让第二第三候选上屏

### ISSUE THREAD

**Issue by abcRiverDoc** [fcitx5-android/fcitx5-android#286]
![微信图片_20230619183001](https://github.com/fcitx5-android/fcitx5-android/assets/16484240/57e9b12c-72d4-48a4-9a41-b32b8a62a7b4)
五笔用户基本上最多就三个候选

**Comment by lilydjwg** [comment]
默认是 ;'，大概你改一下就可以？不过改完在物理键盘上就不好用了。

**Comment by rocka** [comment]
在高级设置里关闭“隐藏快捷键配置”，五笔设置中就会出现“选择第二个候选词”“选择第三个候选词”的设置。分别设置为英文逗号和句号即可。

**Comment by abcRiverDoc** [comment]
收到，已经搞定，感谢指点加外接键盘时，虚拟键盘不能隐藏，后期有隐藏的计划没
&nbsp;


zzz
***@***.***





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月19日(星期一) 晚上6:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fcitx5-android/fcitx5-android] 能否用下面的逗号跟句号让第二第三候选上屏 (Issue #286)





 
在高级设置里关闭“隐藏快捷键配置”，五笔设置中就会出现“选择第二个候选词”“选择第三个候选词”的设置。分别设置为英文逗号和句号即可。
 
&mdash;
