### ISSUE TITLE
set_target_properties Can not find target to add properties to: scel2org5

### ISSUE THREAD

**Issue by soulaxin** [fcitx5-android/fcitx5-android#302]
**描述问题 / Describe the bug**
执行 ./gradlew build报错：
CMake Error at CMakeLists.txt:73 (set_target_properties):
    set_target_properties Can not find target to add properties to: scel2org5

**日志 / Log**
> Task :app:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Error at CMakeLists.txt:49 (add_subdirectory):
C/C++:   The source directory
C/C++:     /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/libime
C/C++:   does not contain a CMakeLists.txt file.
C/C++: CMake Error at CMakeLists.txt:51 (target_compile_options):
C/C++:   Cannot specify compile options for target "kenlm" which is not built by
C/C++:   this project.
C/C++: CMake Error at CMakeLists.txt:58 (add_subdirectory):
C/C++:   The source directory
C/C++:     /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/fcitx5-lua
C/C++:   does not contain a CMakeLists.txt file.
C/C++: CMake Error at CMakeLists.txt:71 (add_subdirectory):
C/C++:   The source directory
C/C++:     /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/fcitx5-chinese-addons
C/C++:   does not contain a CMakeLists.txt file.
C/C++: CMake Error at CMakeLists.txt:73 (set_target_properties):
C/C++:   set_target_properties Can not find target to add properties to: scel2org5

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:configureCMakeDebug[arm64-v8a]'.
> [CXX1429] error when building with cmake using /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/CMakeLists.txt: -- Android: Targeting API '23' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 14.0.7
  -- The CXX compiler identification is Clang 14.0.7
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /home/chenjk/dev/tool/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /home/chenjk/dev/tool/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1")
  -- Found Fcitx5Utils: /home/chenjk/dev/code/fcitx5-android/lib/fcitx5/src/main/cpp/cmake
  -- Found Fcitx5Config: TRUE
  -- Found Fcitx5Core: TRUE
  -- Found Fcitx5Module: TRUE
  -- Found libevent include directory: /home/chenjk/dev/code/fcitx5-android/lib/fcitx5/src/main/cpp/prebuilt/libevent/arm64-v8a/include
  -- Found libevent component: /home/chenjk/dev/code/fcitx5-android/lib/fcitx5/src/main/cpp/prebuilt/libevent/arm64-v8a/lib/libevent_core.a
  -- Found libevent component: /home/chenjk/dev/code/fcitx5-android/lib/fcitx5/src/main/cpp/prebuilt/libevent/arm64-v8a/lib/libevent_extra.a
  -- Found libevent 2.1.12 in /home/chenjk/dev/code/fcitx5-android/lib/fcitx5/src/main/cpp/prebuilt/libevent/arm64-v8a
  -- Found PkgConfig: TRUE
  -- Found Fcitx5Core: TRUE (Required is at least version "5.0.16")
  -- The following OPTIONAL packages have been found:

   * fmt
   * Libevent
   * OpenCC

  -- The following REQUIRED packages have been found:

   * ECM (required version >= 1.0.0)
   * PkgConfig
   * Fcitx5Utils
   * Fcitx5Config
   * Fcitx5Core (required version >= 5.0.16)
   * fcitx5
   * Fcitx5Module
   * Gettext

  -- Configuring incomplete, errors occurred!
  See also "/home/chenjk/dev/code/fcitx5-android/app/.cxx/Debug/1b236k49/arm64-v8a/CMakeFiles/CMakeOutput.log".

  C++ build system [configure] failed while executing:
      /home/chenjk/dev/tool/android/sdk/cmake/3.22.1/bin/cmake \
        -H/home/chenjk/dev/code/fcitx5-android/app/src/main/cpp \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=23 \
        -DANDROID_PLATFORM=android-23 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/home/chenjk/dev/tool/android/sdk/ndk/25.2.9519653 \
        -DCMAKE_ANDROID_NDK=/home/chenjk/dev/tool/android/sdk/ndk/25.2.9519653 \
        -DCMAKE_TOOLCHAIN_FILE=/home/chenjk/dev/tool/android/sdk/ndk/25.2.9519653/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/home/chenjk/dev/tool/android/sdk/cmake/3.22.1/bin/ninja \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/chenjk/dev/code/fcitx5-android/app/build/intermediates/cxx/Debug/1b236k49/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/chenjk/dev/code/fcitx5-android/app/build/intermediates/cxx/Debug/1b236k49/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=Debug \
        -DCMAKE_FIND_ROOT_PATH=/home/chenjk/dev/code/fcitx5-android/app/.cxx/Debug/1b236k49/prefab/arm64-v8a/prefab \
        -B/home/chenjk/dev/code/fcitx5-android/app/.cxx/Debug/1b236k49/arm64-v8a \
        -GNinja \
        -DANDROID_STL=c++_shared \
        -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF
    from /home/chenjk/dev/code/fcitx5-android/app
  CMake Error at CMakeLists.txt:49 (add_subdirectory):
    The source directory

      /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/libime

    does not contain a CMakeLists.txt file.

  CMake Error at CMakeLists.txt:51 (target_compile_options):
    Cannot specify compile options for target "kenlm" which is not built by
    this project.

  CMake Error at CMakeLists.txt:58 (add_subdirectory):
    The source directory

      /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/fcitx5-lua

    does not contain a CMakeLists.txt file.

  CMake Error at CMakeLists.txt:71 (add_subdirectory):
    The source directory

      /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/fcitx5-chinese-addons

    does not contain a CMakeLists.txt file.

  CMake Error at CMakeLists.txt:73 (set_target_properties):
    set_target_properties Can not find target to add properties to: scel2org5

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**设备信息 / Device Infomation**

cat /proc/version
Linux version 5.15.0-76-generic (buildd@lcy02-amd64-019) (gcc (Ubuntu 9.4.0-1ubuntu1\~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #83\~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023

sdkmanager --list_installed
Installed packages:
  Path                 | Version      | Description                     | Location
  -------              | -------      | -------                         | -------
  build-tools;33.0.2   | 33.0.2       | Android SDK Build-Tools 33.0.2  | build-tools/33.0.2
  cmake;3.22.1         | 3.22.1       | CMake 3.22.1                    | cmake/3.22.1
  ndk;25.2.9519653     | 25.2.9519653 | NDK (Side by side) 25.2.9519653 | ndk/25.2.9519653
  patcher;v4           | 1            | SDK Patch Applier v4            | patcher/v4
  platform-tools       | 34.0.3       | Android SDK Platform-Tools      | platform-tools
  platforms;android-12 | 3            | Android SDK Platform 12         | platforms/android-12
  platforms;android-33 | 2            | Android SDK Platform 33         | platforms/android-33

java -version
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.5+8-adhoc.root.jdk17u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 17.0.5+8-adhoc.root.jdk17u, mixed mode, sharing)

**Comment by rocka** [comment]
>  /home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/libime
>
>does not contain a CMakeLists.txt file.

It seems that you did not fetch submodules, please follow the instructions in README.md

https://github.com/fcitx5-android/fcitx5-android/blob/e5af5b5f80338429cbf2bec7d35266868e878618/README.md?plain=1#L70-L77

**Comment by soulaxin** [comment]
我执行了这个步骤，但是这个目录如下，貌似文件没有同步下来。
```sh
B360-N:~/dev/code/fcitx5-android/app/src/main/cpp/libime$ pwd
/home/chenjk/dev/code/fcitx5-android/app/src/main/cpp/libime
B360-N:~/dev/code/fcitx5-android/app/src/main/cpp/libime$ ll
总用量 12K
drwxrwxr-x 9 chenjk chenjk 4.0K 7月   6 15:44 ..
drwxrwxr-x 2 chenjk chenjk 4.0K 7月   6 15:46 .
-rw-rw-r-- 1 chenjk chenjk   60 7月   6 15:46 .git
B360-N:~/dev/code/fcitx5-android/app/src/main/cpp/libime$ cat .git
gitdir: ../../../../../.git/modules/app/src/main/cpp/libime
B360-N:~/dev/code/fcitx5-android/app/src/main/cpp/libime$ ll ../../../../../.git/modules/app/src/main/cpp/libime
总用量 48K
drwxrwxr-x 4 chenjk chenjk 4.0K 7月   6 15:46 objects
drwxrwxr-x 2 chenjk chenjk 4.0K 7月   6 15:46 info
drwxrwxr-x 2 chenjk chenjk 4.0K 7月   6 15:46 hooks
-rw-rw-r-- 1 chenjk chenjk   73 7月   6 15:46 description
drwxrwxr-x 2 chenjk chenjk 4.0K 7月   6 15:46 branches
drwxrwxr-x 6 chenjk chenjk 4.0K 7月   6 15:46 ..
drwxrwxr-x 5 chenjk chenjk 4.0K 7月   6 15:46 refs
-rw-rw-r-- 1 chenjk chenjk 1.9K 7月   6 15:46 packed-refs
drwxrwxr-x 3 chenjk chenjk 4.0K 7月   6 15:46 logs
-rw-rw-r-- 1 chenjk chenjk   23 7月   6 15:46 HEAD
-rw-rw-r-- 1 chenjk chenjk  317 7月   6 17:52 config
drwxrwxr-x 8 chenjk chenjk 4.0K 7月   6 17:52 .
```

**Comment by rocka** [comment]
I have no idea what's wrong, maybe you can try `git submodule update --init --recursive` again, or 

- `git pull --recurse-submodules && git submodule update`
- `git submodule update --recursive --remote`

**Comment by berberman** [comment]
试试重新初始化：
```
git submodule deinit -f .
git submodule update --init -- recursive
```
