### ISSUE TITLE
候选项显示若有长词条时会很不协调

### ISSUE THREAD

**Issue by lbzj** [fcitx5-android/fcitx5-android#303]
如图，若有长词条时，候选显示不协调，希望长词条在首选时字号还是显示正常大小，当显示不下时后面可以用三个点「···」表示，按下展开按钮可以显示全词条。当候选长词条在首选以后的，如在二选时，候选框显示为：首选，二选，当显示不下时后面可以用三个点「···」表示，按下展开按钮可以显示全词条，然后是三选四选等。
另外建议候选可以左右滑动并点选，这样就不用点开那个展开按钮了。
![IMG_20230706_204537](https://github.com/fcitx5-android/fcitx5-android/assets/103396815/ce230931-7221-46db-a844-158cdc8965ea)
![IMG_20230706_204517](https://github.com/fcitx5-android/fcitx5-android/assets/103396815/c4bdc150-a19f-4bba-be03-593538d36f07)
![IMG_20230706_204450](https://github.com/fcitx5-android/fcitx5-android/assets/103396815/a92752cd-abd0-4d7d-8190-6686e530273d)

**Comment by rocka** [comment]
当一个候选词过长的时候，无论省略哪里都可能不合适，而且正常打字的时候也不会一次输入这么长的句子。如果要实现长句在首选怎么样，在二选怎么样，然后三选四选怎么样，这样代码写完之后会很难维护。

你是不是想要一个和剪贴板类似的“短语板”？

**Comment by CyrusYip** [comment]
输入长词语也会出现第一候选词占满一行的情况。

例如：使用维基百科词库，用全拼输入 `yan se bu fen`，「颜色不分蓝绿支持性专区颜色田慎节」
这个人名是第二候选词。
![imagy-image](https://github.com/fcitx5-android/fcitx5-android/assets/60951091/d6128333-c733-4f7d-b21c-d0b16898e7f5)

**Comment by oldherl** [comment]
> 输入长词语也会出现第一候选词占满一行的情况。
> 
我没觉得这个显示有任何问题

**Comment by CyrusYip** [comment]
@oldherl 这样看不到第二个词，只能知道第二个词很长。此时需要先展开再点击，按两下。如果能显示部分第二候选词，可能不需要展开就知道是这个词，按一下。
