### ISSUE TITLE
请求固定数字或符号键盘

### ISSUE THREAD

**Issue by auniel** [fcitx5-android/fcitx5-android#304]
问题：在几乎所有的输入场景中，无法固定数字或符号键盘。

具体情况：有的时候，用户需要大量输入数字或符号，比如需要连续发送20条“666”的微信信息。当用户第一次从全键盘切换到数字键盘，输入一串数字，并点击发送后，输入法自动从数字键盘切换回拼音全键盘。

诉求：希望在默认设置的情况下，用户在数字键盘或符号键盘页面中，选择并发送内容后，不会自动跳转回拼音全键盘。退一步讲，希望允许用户自定义是否要在输入数字并发送后，自动跳转回拼音全键盘。

**Comment by auniel** [comment]
补充：剪贴板也存在上诉情况。

**Comment by rocka** [comment]
设置可以加，但我觉得默认情况下不跳转回键盘不太合适。

**Comment by auniel** [comment]
感谢回复。

至于是否有必要在默认情况下，不跳转回键盘，我没有主意。

一方面，对于某些需要经常输入数字的场景，默认不跳转或许比较有利。比如会计对账，微商报账，编辑记录页码，直播or会议频繁扣1扣2等。

另一方面，出于好奇，我去查看了搜狗、微信、百度、讯飞输入法的安卓版本，都是输入并发送数字后，默认不跳转回主键盘。Gboard和同文输入法则是会跳转回。

为啥会有这个差异，我也不明所以。或许是互相学习，或许是真有类似我这种用户去反馈。

但凭作者决断。感谢贡献。

**Comment by auniel** [comment]
> 设置可以加，但我觉得默认情况下不跳转回键盘不太合适。

感谢回复。

至于是否有必要在默认情况下，不跳转回键盘，我没有主意。

一方面，对于某些需要经常输入数字的场景，默认不跳转或许比较有利。比如会计对账，微商报账，编辑记录页码，直播or会议频繁扣1扣2等。

另一方面，出于好奇，我去查看了搜狗、微信、百度、讯飞输入法的安卓版本，都是输入并发送数字后，默认不跳转回主键盘。Gboard和同文输入法则是会跳转回。

为啥会有这个差异，我也不明所以。或许是互相学习，或许是真有类似我这种用户去反馈。

但凭作者决断。感谢贡献。

**Comment by auniel** [comment]
请问您输入数字后，点击发送了吗？（可以在微信里试试）

**Comment by auniel** [comment]
请问您输入数字后，点击发送了吗

**Comment by JUST-INTJ** [comment]
微信点击'发送'后确实是会回到主界面的，国产输入法不会。

**Comment by rocka** [comment]
e656ec0
