### ISSUE TITLE
快速输入无法触法bug

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#305]
很久就发现了，自定义的快速输入触发词有些不能触法。所以一直没用这个功能。刚没事测试了一番，发现仅不能以 ‘sj’开头，否则无法触法。
0.0.6.31

![20230715_172538](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/c301ba33-29d9-442f-b15f-dff559d9270c)

![20230715_172559](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/11a1b1cc-fd78-488f-bc39-4dc949935ea5)
![Screenshot_20230715-174251_MiXplorer](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/788475bb-0bf5-4464-836b-edb446ceeefc)

**Comment by rocka** [comment]
实际上 `fh` `sj` `rq` 都不能触发，因为这三个是 Lua IME API 自带的触发词

https://github.com/fcitx/fcitx5-chinese-addons/blob/351f76b9b11539dfd07903cb5729e8dc8eefa356/im/pinyin/pinyin.lua#L488-L491

如果你用不到 Lua 脚本的功能，去附加组件里面把 “Lua IME API” 禁用掉就好了。

**Comment by JUST-INTJ** [comment]
好的😘😘
