### ISSUE TITLE
Set traditional Chinese input as default

### ISSUE THREAD

**Issue by flux77** [fcitx5-android/fcitx5-android#307]
I am using fcitx5-android version 0.0.6-0-g024241cf, which I installed via F-Droid. I use traditional Chinese characters more than simplified characters, so I want to set traditional characters as default. I am able to toggle between traditional and simplified in the keyboard, but the setting does not persist. For example, if I switch to traditional characters in fcitx5-android keyboard, and restart whatever app I am using (or restart my phone), fcitx5-android keyboard would then input simplified characters instead of traditional characters. Please add a way to set traditional Chinese as default. Thank you.

**Comment by rocka** [comment]
If you enable "Traditional Chinese" and exit the input method normally, i.e. switch to another input method, the setting would persist when you switch back. Do not force stop the input method, or swipe it away from recent Apps screen, that way Android systemd would kill the process and maybe cause data loss.
