### ISSUE TITLE
ClipboardEditActivity has been finished before calling `onNewIntent()`

### ISSUE THREAD

**Issue by shitlime** [fcitx5-android/fcitx5-android#309]
**描述问题 / Describe the bug**

ClipboardEditActivity has been finished before calling `onNewIntent()`.

**重现步骤 / To Reproduce**

1. 打开剪贴板
2. 长按任意一项
3. 点击“编辑”
4. 打开剪贴板
5. 长按任意一项
6. 点击“编辑”
7. 此时，ClipboardEditActivity 经历了 `onPause` 生命周期，被finish了， `onNewIntent()` 实际并未调用

**预期的行为 / Expected behavior**

应该能正常调用 `onNewIntent()` ，处理新的 `intent` 刷新编辑的内容

**日志 / Log**

**截图 / Screenshots**

**设备信息 / Device Infomation**

- 操作系统 / OS: 鸿蒙3
- 应用版本 / App Version: 0.0.6-g024241cf

**附加信息 / Additional context**

没有pull这个项目，所以不发pr了，也许删掉下面这段应该可以正常工作：

https://github.com/fcitx5-android/fcitx5-android/blob/0f85b9a86a31a01b9515d567063e6bc52a8b003f/app/src/main/java/org/fcitx/fcitx5/android/ui/main/ClipboardEditActivity.kt#L76-L80

**Comment by rocka** [comment]
这里的本意是，当 ClipboardEditActivity 被切到后台的时候，就自动 finish() 自己，防止在最近任务界面出现，不过确实没有考虑到连续点两次编辑的状况。换成 `onStop()` 也许更合适。

**Comment by rocka** [comment]
48b7408

**Comment by shitlime** [comment]
> 这里的本意是，当 ClipboardEditActivity 被切到后台的时候，就自动 finish() 自己，防止在最近任务界面出现，不过确实没有考虑到连续点两次编辑的状况。换成 `onStop()` 也许更合适。

学到了，确实应该用 `onStop()` 而不是删除，但是为什么没有考虑点击两次编辑的情况，会想到使用 `onNewIntent()` 呢？

**Comment by rocka** [comment]
大概是从 MainActivity 里复制来的吧 ... 已经不记得最开始为什么要这么写了
