### ISSUE TITLE
Readme contains broken link

### ISSUE THREAD

**Issue by fohfuu** [fcitx5-android/fcitx5-android#311]
**描述问题 / Describe the bug**

README contains a reference to the Anthy github [here](https://github.com/fcitx5-android/fcitx5-android/blob/master/README.md#L25), which 404s.

**重现步骤 / To Reproduce**

1. View fcitx5-android README.
2. Click on the link to the Anthy repository.

**预期的行为 / Expected behavior**

Accesses Anthy repository.

**日志 / Log**

N/A

**截图 / Screenshots**

N/A

**设备信息 / Device Infomation**

- 操作系统 / OS: N/A
- 应用版本 / App Version: main

**附加信息 / Additional context**

N/A

**Comment by rocka** [comment]
It's a link to anthy plugin source directroy: https://github.com/fcitx5-android/fcitx5-android/tree/master/plugin/anthy , rather than "Anthy GitHub".
