### ISSUE TITLE
wps输入tab之后再输入其他字符会自动删除

### ISSUE THREAD

**Issue by lemon7z** [fcitx5-android/fcitx5-android#314]
如题，只在实体键盘上复现，软键盘没问题
“在程序中显示预编辑文本”这个设置实体键盘也有问题，只输入字母
上面的问题都是在wps上出现，其它app似乎没有

**Comment by rocka** [comment]
请根据 Issue Template ，具体描述问题，尽可能给出详细的复现步骤，以及预期的行为、实际出现的行为，并提供系统/应用版本，必要时提供截图和日志。不符合模板的 Issue 将会被直接关闭。
