### ISSUE TITLE
无需快捷键，快捷输入词库内容置顶

### ISSUE THREAD

**Issue by duzixian** [fcitx5-android/fcitx5-android#321]
使用人群：
双拼为主、音形为辅的用户
个人词库

使用场景：
当双拼遇到想打单字时，使用音形码来实现单字输入
（我电脑上用纯小鹤音形，但手机上因效率问题以双拼为主。但时常遇到想要输入一些单字的情况，这时候切换音形输入法有1s延迟，当前使用快捷输入的形式实现单字输入）

现有方式：
以A键下滑@作为快捷输入的快捷键，在快捷输入词库里面导入小鹤音形码表
（我只导入了34码长的单字）

希望实现：
在输入法选项里加入一个开启“快捷输入置顶”的选项，当所键入的字母完全匹配快捷输入的词库时，置顶快捷输入所提供的选项
（比如我在双拼模式下输入"jpf"，第一个选项是"解放"，而我的快捷输入完全匹配是"揭"，如果开启这一个选项，那么就将"揭"作为首选，"解放"在其后）

替代实现：
其实还有个实现方式，那就是在私有方案的设置页面加个开关，完全匹配时，无论在什么输入法中，都置顶显示。但我感觉这样做会产生一些不必要的麻烦，不若把码表导入快捷输入中

功能好处：
1.不用输入某个特定键开启快捷输入，操作更加流畅
2.相当于拥有了最高权重的个人常用词库
3.可实现双拼和音形的兼容输入

提问初衷：
当想要输入一个快捷输入词库的词时，需要考虑这个词是否在快捷词库，这是有一个思考延迟的，一个思考负担，一个不确定因素。
且很多时候会出现忘记按快捷输入的快捷键的情况，按了三四个键才反应过来匆忙退选，故希望能够有个选项开启默认首选。

**Comment by rocka** [comment]
可以用 fcitx5-chinese-addons 最近新增的 customphrase 功能 https://github.com/fcitx/fcitx5-chinese-addons/pull/138

应该很快就能合并过来 ...

**Comment by duzixian** [comment]
> 

好哒，很是期待。
