### ISSUE TITLE
键盘与虚拟按键重合

### ISSUE THREAD

**Issue by 1219099256** [fcitx5-android/fcitx5-android#322]
**描述问题 / Describe the bug**

**重现步骤 / To Reproduce**

**预期的行为 / Expected behavior**

**日志 / Log**

**截图 / Screenshots**

![Screenshot_20230824_174039_com microsoft emmx~01](https://github.com/fcitx5-android/fcitx5-android/assets/63403797/e28cc57d-ace9-4eea-b0dc-ac26c13d7d5e)

**设备信息 / Device Infomation**

- 操作系统 / OS: [Android 10 (鸿蒙os 2)]
- 应用版本 / App Version: 
![Screenshot_20230824_174455_com android settings](https://github.com/fcitx5-android/fcitx5-android/assets/63403797/35bdf646-01e8-46ba-bba9-3f21af9d9673)

**附加信息 / Additional context**

隐藏虚拟按键再弹出恢复正常

**Comment by rocka** [comment]
https://fcitx5-android.github.io/faq/#_11
