### ISSUE TITLE
“#”输入时出现全/半角确认

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#326]
我用的最新版，发现无论是否开启全半角，中文输入法时输入“#”时，总会出现: #(半角)  ＃   两个候选词让我手动选择。输入：*+-=/  时会自动上屏。
可能是因为#＃的全半角太像了？要二次确认吗。

![Screenshot_20230830-153636_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/8701a6e3-8c12-439d-aa3d-77f61fde44db)
![Screenshot_20230830-153615_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/8342e604-09c9-4ac4-b6e4-d2f2673da9f9)
![Screenshot_20230830-153522_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/82bd6f2d-fc61-4ba8-bb4b-91707995b7d8)

**Comment by rocka** [comment]
这是 fcitx5-chinese-addons 5.1.0 新增的 candidate based punctuation API https://github.com/fcitx/fcitx5-chinese-addons/commit/f6bca14c37c4dd849945a767c083fc9beb94d32d ，让一个英文标点可以映射到多个中文标点。比如 [ 可以映射成 【 「 『 ❲ ［ 四种全角括号。

如果你不需要这个特性，在 拼音（或双拼）设置 - 标点 里，把 # 号的第二个映射删除即可。
