### ISSUE TITLE
建议增加一个中英文输入切换的快捷键

### ISSUE THREAD

**Issue by sztuxp** [fcitx5-android/fcitx5-android#328]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

目前，切换中英文，要弹出一个对话框，进行选择，效率比较低

**描述解决方案 / Describe the solution you'd like**

可以像百度输入法设置一个键，如果不好配置键盘，可以设置一个选项，用户来定义一个快捷键，就像系统设置快速输入一样

**l描述替代方案 / Describe alternatives you've considered**

**附加信息 / Additional context**

**Comment by nuaoc** [comment]
为啥我点左下那个小地球就直接能切换了

**Comment by rocka** [comment]
短按语言切换键（空格左边的🌐键）即可

**Comment by sztuxp** [comment]
miui 13, 安卓12,短按没有反应，长按弹出切换对话框，是不是漏掉什么设置？了？

**Comment by rocka** [comment]
发一下 设置里的输入法列表界面 和 切换对话框 的截图看看？短按切换输入法就是这个键唯一的功能，没有设置的。你是不是把英文输入法删掉了？

或者还有一个替代方案，找到 “设置 - 键盘 - 空格键长按行为“，修改为“轮换输入法”或者“在当前输入法和第一个输入法之间切换”，这样可以长按空格键切换输入法。

**Comment by sztuxp** [comment]
我现在就是用第二个方案，长按空格键来进行切换

**Comment by sztuxp** [comment]
不好意思，是我设置问题，不知道怎么把轮换时跳过第一个输入法勾选上了。第一次用， 这个输入法太赞了！
