### ISSUE TITLE
微软双拼方案无法输入ing韵母

### ISSUE THREAD

**Issue by The-D66** [fcitx5-android/fcitx5-android#329]
**描述问题 / Describe the bug**

微软双拼方案采用`;`输入韵母ing，但在配置微软双拼输入后键盘上未找到`;`，致使无法输入相关拼音

**重现步骤 / To Reproduce**

配置双拼输入法双拼方案为微软双拼后即可复现

**预期的行为 / Expected behavior**

![image](https://github.com/fcitx5-android/fcitx5-android/assets/18234905/eb66356f-5fc9-4652-9fb9-a003e701559e)
如谷歌输入法，采用输入声母后左下shift键变为`;`的方式进行ing韵母的输入

**截图 / Screenshots**

![0c844b4cd053857fd21835d9026cbe83](https://github.com/fcitx5-android/fcitx5-android/assets/18234905/a9861384-f5a1-4e4a-b0f6-7d226d20f22e)
fcitx5目前输入情况如图，无`;`按钮，建议将Shift键变为`;`或横屏时在`l`键右侧增设`;`

**设备信息 / Device Infomation**

- 操作系统 / OS: [ Android 13 (MIUI 14)]
- 应用版本 / App Version: [ 0.0.7-gac5720a1]

**附加信息 / Additional context**

暂可打开in与ing的模糊音，采用`n`键输入的方式规避，但违反输入习惯，希望能够修复相关问题

**Comment by rocka** [comment]
#73
