### ISSUE TITLE
密码自动填充 Auto fill with KeypassDX

### ISSUE THREAD

**Issue by realfanyujun** [fcitx5-android/fcitx5-android#334]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**
不确定是否是输入法的问题。我使用KeypassDX作为密码管理软件，使用Gboard输入法时在网页中可以自动填充密码；而当使用fcitx5时，点击KeypassDX建议的匹配密码后，网页中的密码输入框仍为空白。

**描述解决方案 / Describe the solution you'd like**
在网页中点击KeypassDX建议的匹配密码后，应该能够自动将用户名密码等数据填充到框中。

**附加信息 / Additional context**

系统：安卓12（MagicUI 7），测试时使用的安卓浏览器是fulguris。请帮忙鉴别下是否是输入法的问题。谢谢！

**Comment by rocka** [comment]
你是想说 [KeePassDX](https://github.com/Kunzisoft/KeePassDX) 吗？

**Comment by realfanyujun** [comment]
是这个软件，我在fdroid安装的。不懂问题在哪里，同样的网页用Gboard可以自动输入

于 2023年9月10日 GMT+08:00 下午11:50:09, rocka ***@***.***> 写到:

**Comment by realfanyujun** [comment]
把fcitx5键盘设置中的"显示内置填充建议"关闭，就可以正常用了。问题终结

**Comment by rocka** [comment]
不知道是我的问题还是 KeePassDX 实现的问题，如果把这一行

https://github.com/fcitx5-android/fcitx5-android/blob/8c8860a2620a6ba5fdd16289ee0506d0e02e3772/app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt#L651

改成

```kotlin
 		return InlineSuggestionsRequest.Builder(listOf(spec, spec, spec, spec, spec, spec, spec)) 
```

才能显示出多个 suggestion ，也能正常填充密码；但是现在的版本，配合 Bitwarden 和 Google Play Service 自带的 autofill service ，是能显示出多个 suggestion ，并且正常填充密码的。

从文档上来看： [InlineSuggestionsRequest.Builder#Builder](https://developer.android.com/reference/android/view/inputmethod/InlineSuggestionsRequest.Builder#Builder(java.util.List%3Candroid.widget.inline.InlinePresentationSpec%3E))

> List: The [`InlinePresentationSpec`](https://developer.android.com/reference/android/widget/inline/InlinePresentationSpec) for each suggestion in the response. If the max suggestion count is larger than the number of specs in the list, then the last spec is used for the remainder of the suggestions.

list 里面只填一项是符合规定的。
