### ISSUE TITLE
[Feature Request]增加中文五笔画输入法，方便在小屏手机上使用

### ISSUE THREAD

**Issue by nkdanfer** [fcitx5-android/fcitx5-android#335]
增加中文五笔画输入法，方便在小屏手机上使用。
手太大或屏幕太小时用横竖撇捺折的五笔画输入法会更不容易出错。
望采纳。

**Comment by oldherl** [comment]
现在拼音输入法里面就可以使用 hspnz 来笔画输入，而至于专门的笔画键盘布局，需要等待 #109
