### ISSUE TITLE
无法储存自定义词组

### ISSUE THREAD

**Issue by joyxcola** [fcitx5-android/fcitx5-android#336]
**描述问题 / Describe the bug**

输入过一次的词组，比如说人名，下次输入时还是和第一次输入一样，并且在
 管理自定义词组的设置选项中显示  未实现类型‘External‘

**截图 / Screenshots**
![20230914141110](https://github.com/fcitx5-android/fcitx5-android/assets/77083229/ef7da287-6902-48cc-8d8a-a0897fb8b08d)

**设备信息 / Device Infomation**

三星A54

- 操作系统 / OS:   Android 13  One UI版本 5.1
- 应用版本 / App Version: [Google play最新版本]

**附加信息 / Additional context**

**Comment by rocka** [comment]
你用的哪种输入方式？拼音还是码表？

这个“自定义词组”管理的是自定义从输入字符串到任意短语的映射，和记忆自造词没有关系。

**Comment by joyxcola** [comment]
用的拼音

rocka ***@***.***> 于 2023年9月14日周四 14:44写道：

**Comment by rocka** [comment]
如果打完一串拼音，再挨个选字，正常情况下是能记住的。如果一个字一个字地打，就不会被记住。

另外，如果输入框设置了 IME_FLAG_NO_PERSONALIZED_LEARNING ，比如在 Chrome 的隐身窗口内输入，会激活输入法的隐私模式，工具栏最左边的按钮图标也会变化，此时输入的词语也不会被记录。

**Comment by joyxcola** [comment]
好的。。知道了，另外还想问下这个输入法是否无法存储英文的输入词组？比如英文的昵称之类的？

rocka ***@***.***> 于 2023年9月14日周四 15:12写道：

**Comment by rocka** [comment]
不能存储英文词组。

**Comment by nanoarchaeota** [comment]
请问现在版本的 管理自定义词组 显示   `未实现类型'External'`要怎样才能导入自定义短语呢

**Comment by rocka** [comment]
@nanoarchaeota 下个版本就有了，或者下载 CI 最新版

https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/
