### ISSUE TITLE
语音输入

### ISSUE THREAD

**Issue by QGB** [fcitx5-android/fcitx5-android#344]
不想打字

**Comment by rocka** [comment]
不想写代码

**Comment by QGB** [comment]
@rocka  为什么要 following template ，我意思表达到不就行了吗。  开源就是发扬舍己为人的共产主义精神🐶

语音输入功能什么时候上线？  可以白嫖讯飞搜狗百度输入法的语音识别api吗？

**Comment by oldherl** [comment]
> @rocka 为什么要 following template ，我意思表达到不就行了吗。 开源就是发扬舍己为人的共产主义精神🐶

因为只用四个字根本不知道你想要什么。另外没有人是免费的劳工，你想要什么可以自己写代码来实现。
> 
> 语音输入功能什么时候上线？ 可以白嫖讯飞搜狗百度输入法的语音识别api吗？

Never.
你想用这些大公司的API，那就是直接把你的输入内容直接交给他们了，本项目也就无法保证你的隐私和数据安全。那样你为什么不直接去用它们的产品？
