### ISSUE TITLE
华为mate pad 2023 HarmonyOS 4.0  平板无法在 Android/data/org.fcitx.fcitx5.android/files/data/ 目录下创建文件夹

### ISSUE THREAD

**Issue by zigeweiwu** [fcitx5-android/fcitx5-android#346]
**描述问题 / Describe the bug**

使用的rime 插件，需要新建文件夹

**重现步骤 / To Reproduce**

在 Android/data/org.fcitx.fcitx5.android/files/data/  此目录下，系统文件管理器无法新建文件夹
**预期的行为 / Expected behavior**

**日志 / Log**

**截图 / Screenshots**

**设备信息 / Device Infomation**
华为mate pad 2023
- 操作系统 / OS: HarmonyOS 4.0 
- 应用版本 / App Version: [e.g. 0.0.7-37-ga4d4eb8e-release]

**附加信息 / Additional context**

**Comment by rocka** [comment]
请使用 Android 自带的 DocumentsUI （包名为 com.android.documentsui 或 com.google.android.documentsui ），或者支持 SAF 的文件管理器

---

see also

https://fcitx5-android.github.io/faq/#_8

https://github.com/fcitx5-android/fcitx5-android/issues/171#issuecomment-1370562893
