### ISSUE TITLE
能不能添加一个语音输入啊，用谷歌的好难受

### ISSUE THREAD

**Issue by SuYuXian99999** [fcitx5-android/fcitx5-android#347]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

**描述解决方案 / Describe the solution you'd like**

**描述替代方案 / Describe alternatives you've considered**

**附加信息 / Additional context**

**Comment by oldherl** [comment]
目前没有可用的自由/开源中文语音识别引擎。

**Comment by SuYuXian99999** [comment]
> 目前没有可用的自由/开源中文语音识别引擎。

那岂不是遥遥无期了![emotion_download_1691240289204.jpeg](https://github.com/fcitx5-android/fcitx5-android/assets/143699423/3195c252-c647-4c7b-b73f-8648b8565d69)

**Comment by BackMountainDevil** [comment]
whisper.cpp 蜀黍加入（m4t 太大了

**Comment by rocka** [comment]
可以用这个 https://github.com/ElishaAz/Sayboard

**Comment by gkzhb** [comment]
推荐一个基于 whisper 的语音输入法 [FUTO Voice Input](https://voiceinput.futo.org/) (repo: [Aleksandras Kostarevas / VoiceInput · GitLab](https://gitlab.futo.org/alex/voiceinput) ) ，能在 fcitx5-android 里使用

存在的问题是 FUTO 官方说的中文的简体繁体输出偶尔有问题（混杂简体和繁体的输出文本）

**Comment by GitCourser** [comment]
一个开源的离线语音引擎, [sherpa-ncnn](https://github.com/k2-fsa/sherpa-ncnn), 就是不知道怎么把它变成输入法或插件放到fcitx5中用

**Comment by fastfading** [comment]
> 推荐一个基于 whisper 的语音输入法 [FUTO Voice Input](https://voiceinput.futo.org/) (repo: [Aleksandras Kostarevas / VoiceInput · GitLab](https://gitlab.futo.org/alex/voiceinput) ) ，能在 fcitx5-android 里使用
> 
> 存在的问题是 FUTO 官方说的中文的简体繁体输出偶尔有问题（混杂简体和繁体的输出文本）

能输入提示词吗  ，简体繁体可以通过提示词解决

**Comment by fastfading** [comment]
[FUTO Voice Input](https://voiceinput.futo.org/)
[Sayboard](https://github.com/ElishaAz/Sayboard)
都能work ，   

还有很多online 的whisper 方案，   
问题是如何  集成外部输入软件，
谁有这方面的文档。
我已经集成了PC端  whisper ，   现在基本上不用打字了

谁能提供一个android fcitx文档来实现语音

**Comment by gkzhb** [comment]
FUTO Voice 简繁混杂的问题可以加提示词优化，在 models -> personal dictionary 中添加提示词：
```
以下是普通话的句子。
```
