### ISSUE TITLE
出现同一局域网两部手机共享剪贴板的问题

### ISSUE THREAD

**Issue by Chengxcy** [fcitx5-android/fcitx5-android#348]
两部同一品牌的手机，三星Note10和三星S23,在三星Note10上复制东西，在三星S23的剪贴板上会出现，这是功能还是bug？要是功能的话，在三星S23上复制内容，但在三星Note10上却不会出现。
![Screenshot_20231009_150828_GitHub.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/91258009/008a53f0-b3e8-458b-8c87-98410b8615ec)
![mmexport1696835985512.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/91258009/5b818931-d455-4c3b-a8e3-37396085b9df)

提个需求：
1.空格键太宽了，两旁的逗号键“，”和句号键“。”按键小了点，容易误触，能否加宽点。
![Screenshot_20231009_152119_GitHub.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/91258009/2095326d-522b-4a78-a387-e437940f65c5)

2.看有网友提过需求被开发人员否定了，不过我还想再提一下，能否让句号键“。”双击上屏，单击的话实现某种引导功能，比如引导快符，这样打标点符号就顺畅多了。小企鹅本身也有快捷输入功能，也很好，但是要按很多键。

**Comment by Chengxcy** [comment]
使用的是这个版本0.0.7.45
![Screenshot_20231009_152641_Fcitx5 for Android.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/91258009/1a519257-1dd1-472c-8fd7-c1096dbf0c7f)

**Comment by Chengxcy** [comment]
> 输入法没有联网权限，也不可能向其他设备发送剪贴板内容。请自行检查是否有安装其它剪贴板同步类的应用。

是的。我再排查看看，是不是手机设置问题。

**Comment by rocka** [comment]
至于 2. ，首先句号键长按可以输入更多的标点符号。其次，如果你想单击句号键后可以输入更多的标点符号，可以在 附加组件 - 拼音 - 标点 中，给英文句号 `.` 添加更多的映射。虽然它在拼音设置里，但对码表输入法也有效。

<img src="https://github.com/fcitx5-android/fcitx5-android/assets/13914967/19922224-104b-4bb2-89b8-d15507025d31" width="360">

<img src="https://github.com/fcitx5-android/fcitx5-android/assets/13914967/dc45e3f5-b079-465e-927d-1805fea655da" width="360">

**Comment by Chengxcy** [comment]
映射这个我看到了，映射这么多，可还是要选择的，和在标点集里找差不多。
我说的快捷引导的意思是说，比如输入两个键：
⑴ 。+w→？
⑵ 。+g→！

我看别的输入法有这个功能，只是提一个需求而已，如果没有这样的计划就算了哈😄
希望小企鹅输入法越来越好😄😄😄

**Comment by Chengxcy** [comment]
找到原因了，是手机本身隐藏的功能🙈，同一账户同一网络共享导致的，换任何输入法都是这样，与小企鹅输入法无关🫡🤗
