### ISSUE TITLE
希望增加逗号和句号按键宽度，添加快捷引导功能

### ISSUE THREAD

**Issue by Chengxcy** [fcitx5-android/fcitx5-android#349]
1.空格键太宽了，两旁的逗号键“，”和句号键“。”按键小了点，显得有点拥挤，容易误触，能否加宽点。
2.小企鹅本身也有快捷输入功能，也很好，但是要按很多键。能否添加一个快捷引导按键，比如右侧的句号，能否让句号键“。”双击上屏，单击的话实现某种引导功能，比如引导快符功能，这样打标点符号就顺畅多了。

**Comment by rocka** [comment]
1. 请等待自定义键盘布局功能。
2. 不能。如果你想实现类似的功能，参考这个评论 https://github.com/fcitx5-android/fcitx5-android/issues/348#issuecomment-1752485498

**Comment by Chengxcy** [comment]
> 1. 请等待自定义键盘布局功能。
> 2. 不能。如果你想实现类似的功能，参考这个评论 https://github.com/fcitx5-android/fcitx5-android/issues/348#issuecomment-1752485498

好的，期待自定义键盘布局功能😀

**Comment by Chengxcy** [comment]
> > 1. 请等待自定义键盘布局功能。
> > 2. 不能。如果你想实现类似的功能，参考这个评论 https://github.com/fcitx5-android/fcitx5-android/issues/348#issuecomment-1752485498
> 
> 好的，期待自定义键盘布局功能😀

对于2.我目前的解决方法是，op两键参与编码（我的码表中没有op编码）相当于引导，对应26个字母键来编码，然后在“选择唯一候选词的正则表达式”里添加^op[a-z]，能实现快速上屏，也挺不错的，唯一的遗憾就是多按了一个键。
比如：
opv ——
opw ？

**Comment by rocka** [comment]
@Chengxcy 

你能接受更改码表的话就好办了。首先把英文句号加到码表的编码里

```
KeyCode=abcdefghijklmnopqrstuvwxy.
```

然后可以用英文句号开头编码标点符号


```
.w ？
.g ！
```

然后修改“选择唯一候选词的正则表达式”为 `^\.\w+`

就能实现你想要的效果了。

**Comment by Chengxcy** [comment]
感谢指导，又学到新知识了
