### ISSUE TITLE
[FR] 请求支持键盘界面上划键入标点符号和数字

### ISSUE THREAD

**Issue by Yanlin-Duanmu** [fcitx5-android/fcitx5-android#351]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

目前输入法已经支持通过下滑快速键入标点数字，请求追加一个选项开关，可以供用户选择上划或下滑来进行符号的快捷输入。

**描述解决方案 / Describe the solution you'd like**

允许用户选择使用在键盘界面对应符号上划快速输入标点和数字。

**附加信息 / Additional context**

软件默认方案是符号在字母下方，下滑输入符号。我是采取的讯飞和搜搜狗输入法的界面布局方案，符号设置在右上，上划快速输入符号数字。（上划其实还有种把符号甩到文本框的畅快感）

被朋友推荐这款应用，爱不释手，希望能够支持上划快速键入符号的功能。
![Screenshot_20231012173321.png](https://github.com/fcitx5-android/fcitx5-android/assets/68236504/4170ba5a-569c-42d1-92ce-dd147b28d680)

**Comment by rocka** [comment]
打开输入法设置，键盘 - 划动输入标点符号及数字，更改为“上划”即可。
