### ISSUE TITLE
同一个版本为什么有的手机没有云拼音?

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#352]
1. 有一台找不到云拼音功能开关。这是因为什么?
2. 还有 记得不是说小企鹅是离线本地运行的吗。🤔🤔

![IMG_20231013_042653](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/a45c820c-16b4-4b67-9365-46f892c29556)

**Comment by wengxt** [comment]
@JUST-INTJ 手机上从来就没有启用过这个功能

**Comment by rocka** [comment]
手机上没有编译 cloudpinyin addon。有时能看到云拼音的选项的原因是， pinyin engine 是在加载时注册的一个 defer event 里判断云拼音是否可用的

https://github.com/fcitx/fcitx5-chinese-addons/blob/c10a731c56b20aa48555ac215947c802da11f76b/im/pinyin/pinyin.cpp#L970-L982

如果进入拼音设置时，其还未加载完成，界面上就会显示出云拼音的选项（更改这些选项也不会有任何影响）。这时候返回上一级页面，重新进入拼音设置，相关的选项就会被隐藏。
