### ISSUE TITLE
关于增加语言切换键(language switch key)单击行为选项

### ISSUE THREAD

**Issue by ywx** [fcitx5-android/fcitx5-android#357]
能不能为"语言切换键"增加类似"空格键"的单击行为选项:
轮换输入法(Enumerate input methods)
在当前输入法和第一个输入法之间切换(Toggle input method activate state)
显示输入法选择对话框(how input method picker dialog)

类似

![LangSwitchKeyPressBehavior-zh-small](https://github.com/fcitx5-android/fcitx5-android/assets/1286394/3c85a4cb-06c6-41ee-b8ef-2ca65e97d7bd)

**Comment by rocka** [comment]
6005047 #372
