### ISSUE TITLE
增加英文键盘字母小写、合并符号/数字键盘切换按钮、删除数字键盘中的"="

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#359]
一. 增加英文键盘下字母是小写的。
原因: 记不住上次键盘停留在什么输入壮态，虽然可以开启设置中的"焦点更换后显示输入法信息"功能，但需要在键盘弹出后(注:无法提前/或延后。只能是在输入法弹出后)立刻将注意力从输入框移到键盘左上角并进行逻辑判断,这会打断注意力让人分心，一般人都会盲打不会特别留意键盘。
如果改成英文键盘时是字母小写的，利用余光在无意识下就可判断，就可以集中注意力在输入框中。

二. 合并符号/数字键盘切换按钮
和 #358 的问题有点相似。不过我不建议通过长按符号按钮`?123`来进行切换，一来长按需要延时，二来键盘边界不好滑动。我建议只合并符号/数字切换按钮，以当前状态下判断下一点击弹出符号/数字键盘。第三次回到主键盘。虽然会多按一次按钮但能更快速的打开需要的键盘并且不需要太多注意力。

三. 删除数字键盘中的"=" 或交换= 与 . 的键位。
原因如图。

以上需求是个人长久使用下的真实体验，可供参考。
![Screenshot_20231019-150432_One UI Home](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/e6308ad6-82a2-4a4a-be15-09efae69edc1)
![Screenshot_20231019-152040_One UI Home](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/f7040e1b-ff96-4bad-8e8b-5102f9434753)

**Comment by oldherl** [comment]
请拆分成三条 issue

**Comment by rocka** [comment]
需要更改键盘布局的一律等键盘布局 API 完成之后再做。
