### ISSUE TITLE
增加英文键盘字母小写

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#360]
一. 增加英文键盘下字母是小写的。
原因: 记不住上次键盘停留在什么输入壮态，虽然可以开启设置中的"焦点更换后显示输入法信息"功能，但需要在键盘弹出后(注:无法提前/或延后。只能是在输入法弹出后)立刻将注意力从输入框移到键盘左上角并进行逻辑判断,这会打断注意力让人分心，一般人都会盲打不会特别留意键盘。
如果改成英文键盘时是字母小写的，利用余光在无意识下就可判断，就可以集中注意力在输入框中。

**Comment by rocka** [comment]
你是指即使大写锁定打开了，键盘字母仍然是小写吗？

而且当前输入法的名字会显示在空格键上，应该一眼就能看到吧。

**Comment by Magic989** [comment]
> 你是指即使大写锁定打开了，键盘字母仍然是小写吗？
> 
> 而且当前输入法的名字会显示在空格键上，应该一眼就能看到吧。

大佬你好，对于这个issue我有下面的看法：
很多输入法的键盘字母逻辑是这样的：
1. 输入法为中文的时候，键盘字母是大写的
2. 输入法为英文且未开启大写锁定时，键盘字母是小写的
3. 输入法为英文且已开启大写锁定时，键盘字母是大写的

我感觉这样也是有一定道理，英文输入键盘所见即所得，中文输入键盘和实体键盘相同，同时也能防止混淆中文和英文输入法。

下面是我的一些个人想法：
说起混淆中英文输入法的问题，其实那个语言切换键极其容易误触，有时候打字的时候按逗号不小心碰到就切到英文了。
当然，输入法内部也提供了取消语言切换键的开关，靠长按空格键一样能实现输入法切换。
虽然这样也能替代，但是切换也不够灵活。我想若是能将其移动到工具栏上可能会让语言切换更顺畅。
不过这条建议或许会比较主观，因为可能会有用户觉得输入中文后如果立马要输入英文，那么中文联想会占据工具栏，此时就需要按退格键让工具栏重新出现，导致无法顺畅切换输入法。
但我个人习惯是中英文之间得有空格隔开，输入中文后如果想输入英文，则立马加上空格，工具栏就会露出来。
所以这可能是一个涉及到个人习惯的想法，刚好这个issue让我想到这个问题，就提一下。

**Comment by rocka** [comment]
@Magic989

>英文输入键盘所见即所得，中文输入键盘和实体键盘相同，同时也能防止混淆中文和英文输入法。

其实并不是只有“中文”和“英文”两种输入法，码表也不一定只能输入中文。键盘字母大小写切换的实现已经是“又不是不能用”的水平了，如果再加个选项，判断当前语言，可维护性只会更差。~~所以这个问题还是留给自定义键盘布局来解决吧~~

>输入法切换 …… 若是能将其移动到工具栏上可能会让语言切换更顺畅。

Google Pinyin 就是这么切换中英文的，我一开始也想做成这样，但还是那个问题，不一定只有中文和英文两种输入法。输入法太多了显示不下怎么办？输入法名字太长放不开怎么办？工具栏上的其它图标/剪贴板提示和输入法切换应该怎么共存？等等要考虑的实在是太多了。

**Comment by Magic989** [comment]
> @Magic989
> 
> > 英文输入键盘所见即所得，中文输入键盘和实体键盘相同，同时也能防止混淆中文和英文输入法。
> 
> 其实并不是只有“中文”和“英文”两种输入法，码表也不一定只能输入中文。键盘字母大小写切换的实现已经是“又不是不能用”的水平了，如果再加个选项，判断当前语言，可维护性只会更差。~所以这个问题还是留给自定义键盘布局来解决吧~
> 
> > 输入法切换 …… 若是能将其移动到工具栏上可能会让语言切换更顺畅。
> 
> Google Pinyin 就是这么切换中英文的，我一开始也想做成这样，但还是那个问题，不一定只有中文和英文两种输入法。输入法太多了显示不下怎么办？输入法名字太长放不开怎么办？工具栏上的其它图标/剪贴板提示和输入法切换应该怎么共存？等等要考虑的实在是太多了。

确实，软件开发中这些问题难以避免，由 fcitx5-android 实现基础的、解决用户痛点的功能，剩下的模块由用户根据自身需求去安装，解决用户痒点，这种模式不仅能提升软件的可维护性，也能满足更多用户的需求。
这不禁让我想到了老牌密码管理软件 KeePass ，KeePass 的开发者走的也是这个思路，做了 [KeePass Plugins and Extensions](https://keepass.info/plugins.html) ，二十年的老项目到现在还充满生机与活力。大佬们有建设类似于这样的拓展列表的计划吗。
将来或许有机会借此建立社区，并获取一些广告收益以维持开发热情，毕竟输入法几乎是每个电子设备使用者绕不开的软件。虽然大多数用户可能更倾向于成品输入法，但在如此大的用户基数下注重个性化体验和隐私保护的用户应该不在少数。当然这只是我个人的一点拙见，大佬不用太放在心上。

**Comment by oldherl** [comment]
温馨提示： fcitx 也是二十年的老软件了，只是并没有成立公司或进行任何商业化尝试
