### ISSUE TITLE
候选栏中显示有预测时的问题

### ISSUE THREAD

**Issue by SolidBlock-cn** [fcitx5-android/fcitx5-android#361]
**描述问题 / Describe the bug**
当候选栏中显示有词语预测时，无法把这些预测叉掉，除非输入或者删除新的内容，否则这些预测会一直显示。
此外，按退格键删除一个文本后可以删除预测，但是按住并左滑删除多个文本去了还不行。
**重现步骤 / To Reproduce**

**预期的行为 / Expected behavior**
在候选中的预测列表中加上一个叉号 

**日志 / Log**

**截图 / Screenshots**

![Screenshot_2023-10-22-19-55-54-14_3aea4af51f236e4932235fdada7d1643](https://github.com/fcitx5-android/fcitx5-android/assets/32444848/5d594e4e-fdb0-4d0b-a6d9-fb92bf65c3b8)
在输入了“词语”一词后的预测列表。
**设备信息 / Device Infomation**

- 操作系统 / OS:
- 应用版本 / App Version:

**附加信息 / Additional context**

**Comment by rocka** [comment]
https://github.com/fcitx5-android/fcitx5-android/commit/c638e408008a06eaa54e4e90b521c4eb6404f626 实现了左划退格键清除预测
