### ISSUE TITLE
除拼音以外的输入法是不是不能导入词库

### ISSUE THREAD

**Issue by SolidBlock-cn** [fcitx5-android/fcitx5-android#362]
我阅读了此输入法的官方文档，文档介绍了如何导入拼音词库，但是似乎这样的词库对五笔不太适用？
当前的五笔词库真的太匮乏了，像“搜狗”“重置”“抖音”“轨道交通“等词库均未包含在词库中。

**Comment by rocka** [comment]
五笔不支持单独导入词库，需要重新导入整个码表。可以参考 https://github.com/fcitx5-android/fcitx5-android/discussions/267

**Comment by SolidBlock-cn** [comment]
好遗憾
