### ISSUE TITLE
Traditional Chinese setting is reset after phone reboot

### ISSUE THREAD

**Issue by null-von-sushi** [fcitx5-android/fcitx5-android#365]
**描述问题 / Describe the bug**
When rebooting the phone, simplified is set as the default IME again. The settings UI specifies a way to set opencc options, but has no option to actually keep traditional as the default option. 
May be related to #307 , but it seems that issue was only discussing preserving the state while the application is running. I would like to preserve the "traditional Chinese" option across phone reboots

**重现步骤 / To Reproduce**

1. Use the toolbar on the keyboard to select 繁
2. Reboot the phone
3. Type `wei`. It will show 为, and the setting is back to 简

**预期的行为 / Expected behavior**

The toolbar should still show 繁，and typing `wei` should suggest 為 

**日志 / Log**

N/A, can be provided if necessary

**截图 / Screenshots**

![Screenshot_20231026-155318](https://github.com/fcitx5-android/fcitx5-android/assets/13616397/1830d722-9b27-4d89-8b05-1b809bb25b35)

**设备信息 / Device Infomation**

- 操作系统 / OS: Android 13 (Graphene OS)
- 应用版本 / App Version: 0.0.7-gac5720a1-release

**附加信息 / Additional context**

Please consider either making the toolbar preference persist across reboots, or adding a tickbox in the app's main settings page.
Thank you.

**Comment by rocka** [comment]
This issue should have been fixed by https://github.com/fcitx5-android/fcitx5-android/commit/5f645ea68fcf98ea21fd9941555336436f23544f , and I cannot reproduce it myself.

Can you update to the latest CI build and try again?

**Comment by null-von-sushi** [comment]
Really sorry, I think the issue was on my side. I can confirm the IME does indeed remember the settings as long as a proper reboot via the normal Android system UI option is done (don't use 3rd party apps or the terminal).

My apologies, and thank you for the fast response.
