### ISSUE TITLE
关于添加剪贴板中文分词的一点建议

### ISSUE THREAD

**Issue by cangkuai** [fcitx5-android/fcitx5-android#366]
是否可以添加一个像搜狗输入法一样的剪贴板分词呢，现在gitee上有一个现成的库，虽然这个库有点大，但是java在编译的时候只会编译使用到的类所有应该不会增加太多的体积
https://gitee.com/lionsoul/jcseg?utm_source=alading&utm_campaign=repo

**Comment by rocka** [comment]
duplicate of #262

**Comment by cangkuai** [comment]
就像这样![IMG_20231027_095932.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/33569578/fd4ddafa-32fb-4cca-8d11-db4ef132dc7e)
