### ISSUE TITLE
Allow changing keyboard with the language changing key

### ISSUE THREAD

**Issue by mks-h** [fcitx5-android/fcitx5-android#372]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

I would like to use this keyboard for Japanese input only, and use AOSP keyboard for other languages. This would be easier if this keyboard allowed to cycle not just through its layouts, but also to different keyboard. This is the deafult behaviour in AOSP keyboard. 

**描述解决方案 / Describe the solution you'd like**

Press the language changing key -> change to the next input method (aka another keyboard app)

**描述替代方案 / Describe alternatives you've considered**

**附加信息 / Additional context**

**Comment by rocka** [comment]
6005047 new option "Keyboard - Language Switch Key Behavior"
