### ISSUE TITLE
浮动输入

### ISSUE THREAD

**Issue by ker-j** [fcitx5-android/fcitx5-android#374]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

在安卓平板使用实体键盘时输入框面积占用过大问题，因为连接了实体键盘，不需要显示出键位信息

**描述解决方案 / Describe the solution you'd like**

在主流的输入法里有浮动输入和适配pc那种去掉键位信息直接显示候选框
浮动输入：可以总有浮动在屏幕任何位置并任意调整输入法面积大小，而不仅仅是大面积呈现在底部，这个功能对安卓平板用来来说刚需
输入候选框：浮动输入本地还是缩小键盘面积，但是适配输入候选框才是解决安卓平板的实体键盘最好方法，主流输入法平台有这两项功能，却都无法使用星空键道。

**描述替代方案 / Describe alternatives you've considered**

**附加信息 / Additional context**

我是小米的安卓平板用户，星空键道能用的输入法不多，支持浮动输入和适配实体键盘的则更少

**Comment by rocka** [comment]
duplicate of #106
