### ISSUE TITLE
Feature request: break the space key into 5, add Ctrl Alt Tab Esc

### ISSUE THREAD

**Issue by QiangF** [fcitx5-android/fcitx5-android#376]
The long space key is for physical keyboard, it is long so both of your thumbs can press it. We don't use thumb to press space on the phone.

Ctrl Alt Tab Esc are the must have keys for a hacker's keyboard, for user of emacs or termux. Also long press modifier (Ctrl and Alt) should make the persistent. So for example, when Ctrl is on, you can use f and b to move forward and backward.

It will be a productivity boost just using some common hot keys.

**Comment by rocka** [comment]
This project is not "hacker's keyboard", it would never be a built-in feature. However once customizable keyboard layout is done, you could do it yourself.

**Comment by oldherl** [comment]
Meanwhile there are other people desperately disabling the language key to make the space bar longer...
