### ISSUE TITLE
韩语输入法键盘不显示韩语字母

### ISSUE THREAD

**Issue by HonkaiSR** [fcitx5-android/fcitx5-android#378]
安装韩语插件并开启后可以正常输入韩文，但键盘还是英文键盘（键盘UI显示英文字母，而非韩文字母）。

希望可以像"谷歌Gboard韩语键盘"和"苹果iOS韩语键盘"一样，让韩语键盘UI显示韩语字母。

如果是我哪里没设置好还望指正。

感谢！

**Comment by rocka** [comment]
目前还没实现这个功能。 #377
