### ISSUE TITLE
rime插件总是自动的部署

### ISSUE THREAD

**Issue by codesnoodles** [fcitx5-android/fcitx5-android#383]
**描述问题 / Describe the bug**
在进行指纹操作时，rime插件会自动的部署

**重现步骤 / To Reproduce**

1. 加载rime插件
2. 启用基于rime插件的输入法
3. 进行指纹操作
4. 出现rime插件的自动部署 

**预期的行为 / Expected behavior**

**日志 / Log**

**截图 / Screenshots**

![a7f8d83d30057b79a1deeeeb74f7687](https://github.com/fcitx5-android/fcitx5-android/assets/51237602/212082da-3f5f-4ea4-8842-866edae3b54a)

**设备信息 / Device Infomation**

- 操作系统 / OS: [e.g. Android 13 (MIUI 14)]
- 应用版本 / App Version: [e.g. 0.0.8-0-g4c8399ad-release]
- rime 插件：[0.0.8-0-g4c8399ad]

**附加信息 / Additional context**

**Comment by toddlerya** [comment]
+1 在支付，切换窗口时经常会显示重新部署，正常输入没这个问题。

**Comment by rocka** [comment]
请尝试使用 RIME 插件最新的 CI 构建（0.0.8-55-gc638e408 或更高）： https://jenkins.fcitx-im.org/job/android/job/fcitx5-android-plugin-rime/

**Comment by toddlerya** [comment]
> 请尝试使用 RIME 插件最新的 CI 构建（0.0.8-55-gc638e408 或更高）： https://jenkins.fcitx-im.org/job/android/job/fcitx5-android-plugin-rime/

更新CI构建的最新版本，问题已修复，指纹操作不再触发重新部署。

![Screenshot_2024-01-28-00-17-14-717_org.fcitx.fcitx5.android.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/5418150/2e3e4964-1ae6-4203-bbec-6dd34a305840)

**Comment by zhichengroup** [comment]
使用sayboard和rime-0.0.8-55-gc638e408插件，从sayboard返回时也会触发。
rime使用的是[雾凇配置](https://github.com/iDvel/rime-ice)

**Comment by rocka** [comment]
@zhichengroup 切换到别的输入法时，当前输入法的进程会被结束；再切换回来时，输入法进程又被启动，自然会触发重新部署。
