### ISSUE TITLE
Starting from Android 14, input methods from Gboard will not be shown in input method selection

### ISSUE THREAD

**Issue by scrpr** [fcitx5-android/fcitx5-android#384]
**描述问题 / Describe the bug**
在Android 14中，Gboard提供的输入法不会显示在fcitx5-android的输入法选择框中，只能通过系统设置中的输入法选择器切换输入法。

**重现步骤 / To Reproduce**
1. 长按语言切换键
2. 显示输入法选择框

**预期的行为 / Expected behavior**
显示来自所有键盘提供的输入法。

**截图 / Screenshots**
fcitx5-android的输入法选择框：
![fcitx5](https://github.com/fcitx5-android/fcitx5-android/assets/46473171/c68beb8a-e84f-4d48-96cb-ebfb898b9980)
系统提供的输入法选择框：
![system](https://github.com/fcitx5-android/fcitx5-android/assets/46473171/69ebf1d3-8889-4ab9-935a-75e9bb00dcb7)
Gboard的输入法选择框：
![gboard](https://github.com/fcitx5-android/fcitx5-android/assets/46473171/98e83ef1-8503-461c-8de3-6ae0e43a63a2)

**设备信息 / Device Infomation**

- 操作系统 / OS: Android 14 AOSP
- 应用版本 / App Version: 0.0.8-0-g4c8399ad-release

**Comment by rocka** [comment]
I don't know why but the return value of [InputMethodManager#getEnabledInputMethodList](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#getEnabledInputMethodList()) does not contain gboard on Android 14

**Comment by scrpr** [comment]
@rocka [getInputMethodList](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#getInputMethodList()) does not work either, that's really strange.

One workaround is to use [showInputMethodPicker](https://developer.android.com/reference/android/view/inputmethod/InputMethodManager#showInputMethodPicker()) instead. Since all subtypes are available to system, I guess it would be fine.

However, I'm afraid implementing this will cause Gboard to be unable to detect fcitx5 in its own picker, but who knows?

**Comment by rocka** [comment]
fixed by 278c820
