### ISSUE TITLE
Keyboard doesn't adjust for navbar sometimes

### ISSUE THREAD

**Issue by Quackdoc** [fcitx5-android/fcitx5-android#385]
**描述问题 / Describe the bug**
Sometimes when I open the keyboard, it does not adjust for the navbar

**重现步骤 / To Reproduce**
Sporadically using the keyboard, no consistent method of replication. However it can be fixed by changing keyboard, and change back. However it does seem to occur more when I have not used the keyboard for a prolonged period of time

**预期的行为 / Expected behavior**
Always adjust for navbar

**日志 / Log**
No crash log

**截图 / Screenshots**
![Screenshot_20231116-103748_Discord](https://github.com/fcitx5-android/fcitx5-android/assets/74831516/cbd69238-4f3f-40bc-b84c-815a9eb108e6)

**设备信息 / Device Infomation**

- 操作系统 / OS: Android 10 samsung s9+
- 应用版本 / App Version: 0.0.8-0-g4c8399ad-release

**Comment by rocka** [comment]
See FAQ: https://fcitx5-android.github.io/faq/#_11

I never reproduce this kind of issue on my own device. If you can help debug this, PRs welcomed. Otherwise I cannot fix this.
