### ISSUE TITLE
希望添加对Gboard词库的导入支持

### ISSUE THREAD

**Issue by dontknowhy** [fcitx5-android/fcitx5-android#391]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**

并无任何功能性问题，但我没法导入Gboard词库

**描述解决方案 / Describe the solution you'd like**

能正确识别Gboard和谷歌拼音的词库并进行转换加导入，最好能支持多一些例如rime的yaml格式

**描述替代方案 / Describe alternatives you've considered**

深蓝词库转换(用脚想都知道挺麻烦的，这玩意Linux跑还会有很多问题)

**附加信息 / Additional context**

无

**Comment by Zig-Rust-Odin** [comment]
> 深蓝词库转换(用脚想都知道挺麻烦的，这玩意Linux跑还会有很多问题)

90%的人都用win10, Gboard的zip 格式后期编辑麻烦

> 深蓝词库转换 

应该支持 深蓝词库转换 出来的格式 如rime的.txt .yaml格式 等

**Comment by rocka** [comment]
https://github.com/studyzy/imewlconverter/pull/319
