### ISSUE TITLE
Add "floating" options for tablet users and Make "Text Editing" menu present always.

### ISSUE THREAD

**Issue by JacenBridger** [fcitx5-android/fcitx5-android#392]
**Is your feature request related to a problem? Please describe.**

++ Yes. There are two problems I'm facing.
1. When using this keyboard on tablet, it occupies most of bottom screen.
2. When I'm using symbols/numbers, the"Text Editing " / "Edit-cut-copy-paste" menu disappears.

**Describe the solution you'd like**
++
1. Add floating options like Gboard.
2. Make"Text Editing " / "Edit-cut-copy-paste" menu always present i.e, for all appearances of keyboard (Letters, Symbols, emojis etc.)
3. If the "Text editing" menu can be placed top right of the keyboard, that will be great.

**Describe alternatives you've considered**

++ Not that I can think of.

**Additional context**

![Screenshot_2023-11-23-18-19-49-888_com miui notes_1_062106](https://github.com/fcitx5-android/fcitx5-android/assets/110893579/b1aea788-de51-485b-b39b-3a66c8e3e483)
![Screenshot_2023-11-23-18-16-34-245_com miui notes_062058](https://github.com/fcitx5-android/fcitx5-android/assets/110893579/0fdaf86e-37e0-4a49-9e68-aa38e7932146)

**Comment by rocka** [comment]
1. #115 
2. No it should not. Text editing menu and symbol categories are totally different things.
3. What do you mean by "be placed top right of the keyboard"?

**Comment by JacenBridger** [comment]
For (2), I agree they are different things, but there are certain cases like solving math problem, it's easier to directly editing from the "Text editing" menu. 
I will be attaching a screenshot of gboard for (2) & (3). Thank You.
![Screenshot_2023-11-24-06-18-10-782_ch deletescape lawnchair plah](https://github.com/fcitx5-android/fcitx5-android/assets/110893579/e47684c4-1fca-4933-9385-c615191e45f7)
