### ISSUE TITLE
微软双拼输入法下，如何输入分号对应的韵母 “ing”？

### ISSUE THREAD

**Issue by BH2WFR** [fcitx5-android/fcitx5-android#397]
微软双拼输入法中，韵母“ing”对应分号键，如何输入?

**Comment by rocka** [comment]
- #73
- #377

**Comment by tp20c5** [comment]
已解决，rime佬的这个fork版本支持了虚拟键盘布局自定义，可以实现和其他输入法一样的大写键、ing合键，根据自己喜欢的交互方法使用不同布局（默认大写切换或默认分号）
https://github.com/fxliang/fcitx5-android

https://github.com/user-attachments/assets/2812b7f4-30cc-466c-9633-1c3a111ac152
https://github.com/user-attachments/assets/cb1ee181-6340-4e95-9833-b424259bf9ed
