### ISSUE TITLE
候选词和候选字能不能统一顺序？

### ISSUE THREAD

**Issue by chwt163** [fcitx5-android/fcitx5-android#403]
现在的候选列表当中，候选的字和词是混排的，有时候不太好找，能不能词统一在前，字统一在后？

**Comment by lilydjwg** [comment]
好奇怪的要求。要是我的话，会更希望字在前、词在后（因为我是五笔用户）。
当然，混排对于我来说也没有什么问题和不便。

**Comment by rocka** [comment]
不能。

https://github.com/fcitx/fcitx5-chinese-addons/issues/128
