### ISSUE TITLE
关于九宫格数字界面与符号页面的记忆问题

### ISSUE THREAD

**Issue by Nostalgia-WZQ** [fcitx5-android/fcitx5-android#404]
**描述问题 / Describe the bug**

数字界面和符号界面在切换两次以上时，即使离开时的界面是数字界面，下次进入时依然是符号界面。

**重现步骤 / To Reproduce**

在拼音输入界面，按“?123”键，点“1234”键，点“!?#”键，再点“1234”键，返回拼音输入界面，按“?123”键，进入的是符号界面，而不是离开时的数字界面。

**预期的行为 / Expected behavior**

在数字和符号多次切换后，若上次离开界面是九宫格数字界面，按“?123”键后进入的界面依然是数字界面。

**设备信息 / Device Infomation**

- 操作系统 / OS: [e.g. Android 13 (MIUI 14)]
- 应用版本 / App Version: [e.g. 0.0.8-0-g 4 c8399ad-release]

**Comment by rocka** [comment]
should be fixed by 12aa578
