### ISSUE TITLE
部分选项框左下角“默认”按钮失效

### ISSUE THREAD

**Issue by Nostalgia-WZQ** [fcitx5-android/fcitx5-android#405]
**描述问题 / Describe the bug**
如目前发现的全局选项下的“共享输入状态”和拼音设置下的“preedit mode”选项，点默认后虽然显示恢复了默认，但退出页面重进后，依然是之前的选项。

顺便想问一下“preedit mode”和“在预编辑中显示完整拼音”的作用，我改了后没看出区别。😁😁

**设备信息 / Device Infomation**

- 操作系统 / OS: [e.g. Android 13 (MIUI 14)]
- 应用版本 / App Version: [0.0.8-17-g34ee8147]

**Comment by rocka** [comment]
“Preedit Mode“控制的是输入过程中拼音串显示的位置，需要在全局选项中开启“在程序中显示预编辑文本”后才会生效。简单点说就是控制拼音串显示在输入框里还是输入法键盘左上角。

“在预编辑中显示完整拼音”是给双拼用的，开启之后，拼音串会显示成对应的全拼，而不是双拼。比如自然码双拼输入 `k` `s` 后会显示成 `kong` 。

**Comment by Nostalgia-WZQ** [comment]
> “Preedit Mode“控制的是输入过程中拼音串显示的位置，需要在全局选项中开启“在程序中显示预编辑文本”后才会生效。简单点说就是控制拼音串显示在输入框里还是输入法键盘左上角。
> 
> “在预编辑中显示完整拼音”是给双拼用的，开启之后，拼音串会显示成对应的全拼，而不是双拼。比如自然码双拼输入 `k` `s` 后会显示成 `kong` 。

好的，谢谢解答

**Comment by rocka** [comment]
should be fixed by 2b3b78f
