### ISSUE TITLE
数字九宫格里的逗号打出来是全角的，不知算不算bug

### ISSUE THREAD

**Issue by Nostalgia-WZQ** [fcitx5-android/fcitx5-android#406]
**描述问题 / Describe the bug**
从拼音键盘进入数字九宫格，其他符号都是正常的半角，唯独逗号是全角。如果改映射的话，拼音键盘也会受影响。

**预期的行为 / Expected behavior**
数字九宫格内的符号全是半角，不受映射影响。

**设备信息 / Device Infomation**

- 操作系统 / OS: [e.g. Android 13 (MIUI 14)]
- 应用版本 / App Version: [0.0.8-21-g4414086b]

**Comment by JUST-INTJ** [comment]
关掉试一下?  
![Screenshot_20231221-192944_Via](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/283a5e33-4f57-4f22-80f8-37aa00432453)

**Comment by Nostalgia-WZQ** [comment]
> 关掉试一下?  
> ![Screenshot_20231221-192944_Via](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/283a5e33-4f57-4f22-80f8-37aa00432453)
> 

这里关了的话拼音键盘里的也变成半角了

**Comment by Nostalgia-WZQ** [comment]
@rocka 已添加相关描述

**Comment by rocka** [comment]
should be fixed by 19e3d50
