### ISSUE TITLE
隐私输入开关和清空历史输入选项

### ISSUE THREAD

**Issue by terminator850** [fcitx5-android/fcitx5-android#408]
1. 注意到浏览器隐私模式下 输入法也会进入隐私模式,可否将隐私输入改为开关选项，开启后不记录历史输入。不改变词频和推荐。
2. 输入法会默认记录输入 修改词频 是否可以清空用户历史输入记录。

**Comment by rocka** [comment]
- https://github.com/fcitx/fcitx5-chinese-addons/issues/133
