### ISSUE TITLE
如何在有词的提示时回车只上屏词?

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#409]
**描述问题 / Describe the bug**
有些输入框下输入会有词的提示，此时回车只想上屏词条字母，就像中文输入时一样，不是提交。

**重现步骤 / To Reproduce**
图1应用输入时有词的提示，想回车只上屏`yyds`。
图2而没有提示。

![Screenshot_20231221-191223_Firefox Beta](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/9c4567ea-a976-4c43-bbc0-e2f5db45d662) 
![Screenshot_20231221-191242_Via](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/77605ddf-e8f1-4efb-aae6-00a322bb63df)

`词的提示可以`

**Comment by rocka** [comment]
在“全局选项“中打开”在程序中显示预编辑文本“
