### ISSUE TITLE
希望增加一个过滤字符集的功能

### ISSUE THREAD

**Issue by GitCourser** [fcitx5-android/fcitx5-android#411]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**
希望增加一个过滤字符集的功能, 能过滤生僻字

**描述解决方案 / Describe the solution you'd like**
就像简繁输出开关那样搞个开关就行, 常用字就用gb2312的6000多个字, gb18030剩下的字就是生僻字

**描述替代方案 / Describe alternatives you've considered**

**附加信息 / Additional context**

**Comment by rocka** [comment]
附加组件 - 拼音 - 启用 Unicode CJK 拓展区 B 中的字符

**Comment by GitCourser** [comment]
> 附加组件 - 拼音 - 启用 Unicode CJK 拓展区 B 中的字符

我用的自定义五笔码表，码表包含GB18030所有汉字，但是平常打字又用不到这么多，全部检索会增加重码，所以想有个开关，平常只检索GB2312的常用字，需要时用打开开关后再检索其他的生僻字

**Comment by wengxt** [comment]
@GitCourser 你可以把你的码表再复制一份只有gb2312的，然后靠切换输入法即可

**Comment by GitCourser** [comment]
> @GitCourser 你可以把你的码表再复制一份只有gb2312的，然后靠切换输入法即可

呃.......这也是个办法
