### ISSUE TITLE
跟随夜间模式偶现失灵

### ISSUE THREAD

**Issue by LeuJue** [fcitx5-android/fcitx5-android#412]
**描述问题 / Describe the bug**
已设置主题跟随系统夜间，但不能自动切换

**预期的行为 / Expected behavior**
系统切换为深色模式后，主题自动切换

**设备信息 / Device Infomation**

- 操作系统 / OS: Android12 MIUI13
- 应用版本 / App Version: 0.0.8-3-g278c820a-release

**Comment by rocka** [comment]
Should already been fixed in e5def04 . Please update to 0.0.8-16 or later.
