### ISSUE TITLE
Add GODAN keyboard for Japanese

### ISSUE THREAD

**Issue by PoneyClairDeLune** [fcitx5-android/fcitx5-android#415]
**描述你请求的功能是否和问题有关 / Is your feature request related to a problem? Please describe.**
`fcitx5-android` currently lacks GODAN layout for Japanese input.

**描述解决方案 / Describe the solution you'd like**
Add GODAN layout for Japanese input.

**描述替代方案 / Describe alternatives you've considered**
Uhh... There's none?

**附加信息 / Additional context**
* ![image](https://github.com/fcitx5-android/fcitx5-android/assets/88174309/32fd320a-4322-4239-95c9-256f67a2810e)
* #375

**Comment by rocka** [comment]
See #377 . Please do not file new issues about "support some keyboard layout"

**Comment by PoneyClairDeLune** [comment]
> See #377 . Please do not file new issues about "support some keyboard layout"

Sorry for the bother, didn't see that issue at all 😅.
