### ISSUE TITLE
RIME插件的日志查看

### ISSUE THREAD

**Issue by ziloeng** [fcitx5-android/fcitx5-android#417]
#### 摘要 / Summary

希望输出RIME插件的日志，方便调试码表方案。
RIME插件应当会生产一个日志信息，当修改了码表方案后重新部署，会输出如编码错误、词条重复等提示信息。
我在app中好像只能看到输入法主体的日志信息入口，RIME插件内部的日志则找不到查看的地方。

**Comment by rocka** [comment]
https://github.com/rime/librime/pull/730 给 librime 增加了 only log to stderr 的选项（实现为当 `log_dir` 为 `""` 时启用 glog 的 `FLAGS_logtostderr`），之后 https://github.com/fcitx/fcitx5-rime/pull/79 启用了该选项（无条件将 `log_dir` 设置为 `""`），使得 fcitx5-rime 在桌面上仅会将日志输出到 stderr ，与 fcitx5 自身输出日志的方式一致。

但是在 Android 上， glog 仅当没有启用 `logtostderr` 时，才会在输出日志到文件的同时，“顺便”输出一份到 logcat
https://github.com/google/glog/blob/v0.6.0/src/logging.cc#L1840-L1874
https://github.com/google/glog/blob/v0.6.0/src/logging.cc#825
而 Android 的 stderr 并不会被重定向到 logcat ，导致应用内置的实时日志功能无法捕捉到 rime 插件的日志。

具体解决方案还在讨论中。

**Comment by toddlerya** [comment]
我也遇到类似的问题，把Linux的词库同步到Android，然后报错了，没法查看详细日志。
![Screenshot_2024-01-24-16-37-47-515_com miui notes](https://github.com/fcitx5-android/fcitx5-android/assets/5418150/c81bef66-f14a-453c-b0f0-059028f6a5e5)

**Comment by rocka** [comment]
should be fixed by https://github.com/fcitx5-android/prebuilder/pull/23 and https://github.com/fcitx5-android/fcitx5-android/commit/de4dc2cd1f2f760657d92f041e5e32a00f12f287
