### ISSUE TITLE
Add material you support

### ISSUE THREAD

**Issue by ghtesting2020** [fcitx5-android/fcitx5-android#424]
#### 摘要 / Summary

Add Android 12+ material you support. I thinks this is official documentation: https://source.android.com/docs/core/display/material i have added screenshots of the difference it makes to icons where it follows theme. fcitx5 is one of the last apps i have not support it and stick out like sore thumb :(

#### 替代方案 / Alternative Solution

n/a

#### 附加信息 / Additional Context

![before](https://github.com/fcitx5-android/fcitx5-android/assets/69682350/4dc63621-2c79-46c0-bc0c-0eb83ba4916b)
![after](https://github.com/fcitx5-android/fcitx5-android/assets/69682350/bc353095-7935-4b84-a8a6-a4bb97e629f0)

**Comment by rocka** [comment]
#418
