### ISSUE TITLE
支持自定义模糊拼音

### ISSUE THREAD

**Issue by wanzh5** [fcitx5-android/fcitx5-android#425]
#### 摘要 / Summary

当前的模糊拼音无法做到相邻字母误触的修正，例如xueciao→xuexiao，一些其他输入法是有这类修正的（例如gboard）。
如果不能自定义，在默认方案里加上这些修正也可以。
#### 替代方案 / Alternative Solution

无
#### 附加信息 / Additional Context

无

**Comment by rocka** [comment]
请到 https://github.com/fcitx/fcitx5-chinese-addons 提新 issue ， Android 端不能决定这部分的实现。
