### ISSUE TITLE
rime插件不支持方案中的配置 switches > ascii_mode > reset 为 1，也就是默认英文模式。

### ISSUE THREAD

**Issue by MapoMagpie** [fcitx5-android/fcitx5-android#426]
#### 摘要 / Summary

如果rime的输入方案里 switches > ascii_mode > reset 设置为1的话，(0是中文，1是英文)，这时候无法在fcitx-android > rime的配置中选择该方案。改为0后则可以正常选择方案了。

#### 重现步骤 / Steps to Reproduce

https://github.com/fcitx5-android/fcitx5-android/assets/33853879/324c595e-3f42-4236-9e5c-1184cdc328a5

#### 预期行为 / Expected Behavior

switches > ascii_mode > reset = 1 时，可以正常选择方案。

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android 10, Android 13
- 应用版本 / App Version: 0.0.8
- 插件版本 / Plugins Version: plugin.rime 0.0.8

**Comment by WhiredPlanck** [comment]
如果我没记错的话，fcitx5-rime 不支持 reset 为 0。输入法默认模式整体由 fcitx5 进行管理。如果你需要默认英文模式，请在 app 中的“输入法”中将“English”移到第一位。

**Comment by MapoMagpie** [comment]
我观察了下fcitx5-rime，确实在界面上无法设置方案的ascii_mode。因为在电脑上可以通过shift或F4等一些辅助按键，然后由rime自己来处理按键改变ascii_mode，但是到了手机上缺少了这些辅助按键，没法由rime自己切换ascii_mode。

也许这个问题要到fcitx5-rime上处理，增加一个切换ascii_mode的菜单之类的，就在 `全角->半角` `汉字->汉字` 那个地方。

**Comment by swwrww** [comment]
希望在状态栏能增加一个一键切换中英的按扭

**Comment by rocka** [comment]
fcitx5-rime 没有给 ascii_mode 实现一个单独的菜单，因为 schema menu 里已经可以切换英文模式了

https://github.com/fcitx/fcitx5-rime/blob/5.1.4/src/rimeengine.cpp#L793-L796
