### ISSUE TITLE
关于 上滑/下滑 输入标点符号及数字 功能希望可以有个选项来隐藏其他字符（如带音调的字母等等）

### ISSUE THREAD

**Issue by XIU2** [fcitx5-android/fcitx5-android#429]
#### 摘要 / Summary

上滑/下滑 来输入标点符号及数字时，发现一些字母的上滑菜单里有一些特殊的字符，比如：

我想要上滑字母 `v` 来打出问好 `?`，但是经常因为滑动幅度或方向的原因导致打出了 `ǖ ǘ ǚ ǜ ü` 等字符（包括像字母 `a` `c` `y` 的上滑菜单里都有一些 “奇奇怪怪” 的字符，电脑上我都不知道怎么打出来），而这些字符我可能一辈子都不会输入过一次，但因为它们出现在上滑菜单里导致我经常想划出符号时误触，很影响使用体验。。。

另外，每个字母的上滑菜单里都有个对应的大写字母，如果是在英语输入法下，则比较方便单独输入大写字母，但是在中文拼音输入法下就感觉有点奇怪，似乎没有太大意义，因为如果是要快速输入大写英文字母，那么还需要去点第二个候选词才行。。。

****

因此希望添加一个**选项开关**，可以控制 **上滑菜单 中只会显示唯一的一个 标点/符号/数字**，也就是字母按键底部/右上显示的那个符号（即所见即所得，不会误触选中非预期符号），比如 `v` 按键底部/右上显示的是 `?`，那么上滑就只出现一个 `?` 而没有其他字符。

****

#### 替代方案 / Alternative Solution

当然，如果可以精确的控制每个字母按键上滑可以选中的标点符号数字就更好了，但这显然改动较大，工作量更大，因此我也就不抱希望了，只希望能像我上面说的那样，能控制按键上滑菜单只显示一个预期的标点/符号/数字就行啦~

**Comment by XIU2** [comment]
奥，原来是这样呀。
因为我是长按空格键来切换中英文键盘的，为了方便切换把长按延迟设置为默认值的一半 `150ms`，没想到这个 长按延迟 还和 按键上划符号 有关系，导致了我上滑时如果不够快就会被输入法认为是长按从而容易误触其他符号。。。

**Comment by PapainTea** [comment]
“设置—键盘—显示语言切换键”，你可以把这个打开，方便些
