### ISSUE TITLE
系统提示同步出错 让查看日志

### ISSUE THREAD

**Issue by rebron1900** [fcitx5-android/fcitx5-android#433]
#### 摘要 / Summary
TG群内好几个小伙伴出现了这个问题，根据日志发现是因为同步目录下存在一个 .temp.userdb 名称的文件，删除该文件后可正常同步一会儿，但是过一段时间后又会出现该问题。

#### 日志 / Log

[org.fcitx.fcitx5.android-2024-02-08T00_42_18Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/14203034/org.fcitx.fcitx5.android-2024-02-08T00_42_18Z.txt)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version:
- 应用版本 / App Version:
- 插件版本 / Plugins Version:

**Comment by rocka** [comment]
```
error backing up user dict '.temp'.
```

这句日志来自

https://github.com/rime/librime/blob/8709a7a69fc7c4979d45ae6159bf19cc28f9816d/src/rime/lever/user_dict_manager.cc#L204

请汇报问题给 rime

**Comment by MOldtime** [comment]
https://github.com/rime/librime/issues/810#issuecomment-1986707579

这估计得这边来做兼容了
