### ISSUE TITLE
数字键盘按下后就直接上屏了，不能在preedit模式下参与RIME方案的数字/日期/大写数字 等转换功能

### ISSUE THREAD

**Issue by ccyybn** [fcitx5-android/fcitx5-android#437]
#### 摘要 / Summary

数字键盘可参与 preedit 模式

#### 替代方案 / Alternative Solution

把 0-9 加一排放在主键盘上面，主键盘的数字可参与转换，就是要长按，不方便

#### 附加信息 / Additional Context

为方便理解，下面是该功能在电脑上的演示，手机上按数字键盘 preedit 直接就中断了

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/a49071b5-b5f7-4f82-b4fb-b2a8c655a43e)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/c4e19b66-94ef-488d-8ad8-5567bfe4384c)

**Comment by rocka** [comment]
数字键盘（中间有九宫格数字的那个）的按键被映射为物理键盘上的数字小键盘，但你用的 rime 方案不支持小键盘。

符号键盘（横着一排数字可以翻页的）的数字输入后，中断输入并原样使数字上屏，是设计使然。

独立数字行移步 #377
