### ISSUE TITLE
语言切换按键无法切换输入法

### ISSUE THREAD

**Issue by qwert-f** [fcitx5-android/fcitx5-android#438]
#### 摘要 / Summary
升级系统到android14后原本弹出弹框可以选择当前输入法app切换另一中输入法也可以更换为另一款输入法app，现在只能当前app换输入法了，不能切换到另一个app了

#### 重现步骤 / Steps to Reproduce
将空格键长按行为调为显示输入法对话框后长按即可

#### 截图 / Screenshots
![Screenshot_2024-02-17-14-11-18-71_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/fcitx5-android/fcitx5-android/assets/50124761/0fff231f-da9c-465c-8317-39de008ae2f6)
当面长按后如图

#### 设备信息 / Device Infomation

- 系统版本 / OS Version:ColorOS14/Android14
- 应用版本 / App Version: github最新版
- 插件版本 / Plugins Version:none

**Comment by rocka** [comment]
278c820ac4ab2f590ea39c97e1d2db0f0a44b8b4 已经修过了，到 https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/ 下载 CI 最新版
