### ISSUE TITLE
首次由英文切换至中文输入法时卡顿

### ISSUE THREAD

**Issue by weimzh** [fcitx5-android/fcitx5-android#439]
#### 摘要 / Summary

首次由英文切换至中文五笔输入法时卡顿几秒，比较影响体验

后续在进入app后的首次输入法切换也有可能出现，具体条件未知

#### 重现步骤 / Steps to Reproduce

1. 打开任一app，将英文输入法切换为中文五笔. 会卡顿三四秒左右

#### 预期行为 / Expected Behavior

不出现可感知明显卡顿
#### 设备信息 / Device Infomation

- 系统版本 / OS Version: 安卓11
- 应用版本 / App Version: 0.0.8
- 插件版本 / Plugins Version:

**Comment by weimzh** [comment]
https://github.com/fcitx5-android/fcitx5-android/assets/1220443/709a34c9-d7d1-4a3a-ab48-637d951dfad2

录屏

**Comment by rocka** [comment]
词库加载需要时间
