### ISSUE TITLE
导航栏与键盘重叠

### ISSUE THREAD

**Issue by xlucn** [fcitx5-android/fcitx5-android#441]
#### 摘要 / Summary

在lineageos21中，键盘是沉底的，并且和导航栏重叠。

#### 预期行为 / Expected Behavior

底部留有导航栏的空白高度

#### 截图 / Screenshots

![Screenshot_20240221-230656_GitHub.png](https://github.com/fcitx5-android/fcitx5-android/assets/12032219/4f5909a7-b3e3-4235-8981-310e11dda958)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Lineageos21/android14
- 应用版本 / App Version:0.0.8
- 插件版本 / Plugins Version:

#### 附加信息 / Additional Context

lineageos20上是没有这个问题的，系统升级后出现问题

重装软件无法解决问题

其他输入法（aosp、unexpected keyboard等）不存在此问题

**Comment by rocka** [comment]
https://fcitx5-android.github.io/faq/#_11

**Comment by xlucn** [comment]
> https://fcitx5-android.github.io/faq/#_11

@rocka 谢谢！我自己确实没有找到。链接里的方法确实可以解决，那我关掉issue了
