### ISSUE TITLE
全角符号补全

### ISSUE THREAD

**Issue by luckmoon** [fcitx5-android/fcitx5-android#444]
#### 摘要 / Summary
全角符号没有双引号，输入很不方便

#### 附加信息 / Additional Context
使用的雾凇方案，不确定是不是方案的问题

![img_v2_df763a76-f482-40bf-b057-293f1200ca8l](https://github.com/fcitx5-android/fcitx5-android/assets/12612749/58de9c5f-e9ca-4ddc-b258-2a0ea19fbf21)

**Comment by ChaunceySheng** [comment]
> 从来就没有“全角双引号”这种东西。英文字体显示为半角，中文字体显示为全角，本质上是一个字符。
> 
> 双引号在符号键盘 `!?#` 分类中的第二页，或者如果你的 rime 配置正常的话下划 c 键也能输入双引号。

有全角双引号的。全角字符分属于Unicode U+2000常用标点、 U+3000中日韩符号和标点、 U+FF00全形及半形字元中。

**Comment by ChaunceySheng** [comment]
最好的方式是支持用户能够自由更改符号列表和分类。

**Comment by CoelacanthusHex** [comment]
> > 从来就没有“全角双引号”这种东西。英文字体显示为半角，中文字体显示为全角，本质上是一个字符。
> > 双引号在符号键盘 `!?#` 分类中的第二页，或者如果你的 rime 配置正常的话下划 c 键也能输入双引号。
> 
> 有全角双引号的。全角字符分属于Unicode U+2000常用标点、 U+3000中日韩符号和标点、 U+FF00全形及半形字元中。

U+FF02 和 U+FF07 是直引号，不被任何 CJK 标点方案接受，中日韩标点符号区块里没有引号，常用标点里引号全半角共用码点
