### ISSUE TITLE
English输入时某些app无法显示单词推荐

### ISSUE THREAD

**Issue by RomaYun323** [fcitx5-android/fcitx5-android#446]
#### 摘要 / Summary
English输入时，某些app无法显示单词推荐。如：edge、Google keep、spark、Google搜寻、shelter...我手机大部分app都不行
但在F-droid上可以显示

#### 重现步骤 / Steps to Reproduce

1. 打开上述App
2. 点击输入框
3. 输入英文时无法出现单词推荐

#### 预期行为 / Expected Behavior
点开输入框会输入英文时会显示单词推荐，但实际没有显示英文单词推荐

#### 截图 / Screenshots

![Screenshot_2024-02-29-11-12-45-733_com microsoft emmx](https://github.com/fcitx5-android/fcitx5-android/assets/75065161/cca25b69-1e17-4402-8e5f-8d40c3b57915)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Xiaomi 13，Android 14，HyperOS 1.0.1.0
- 应用版本 / App Version: 0.0.8-61-ga8661f8e
- 插件版本 / Plugins Version: 无

**Comment by rocka** [comment]
经常有人提这个问题，比如 https://github.com/fcitx5-android/fcitx5-android/discussions/206 https://github.com/fcitx5-android/fcitx5-android/discussions/423 。但这其实并不是 bug ，是输入框通过 InputType 通知输入法不要提供候选词建议，比如这两个 flag ： [TYPE_TEXT_FLAG_AUTO_COMPLETE](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_FLAG_AUTO_COMPLETE) [TYPE_TEXT_FLAG_NO_SUGGESTIONS](https://developer.android.com/reference/android/text/InputType#TYPE_TEXT_FLAG_NO_SUGGESTIONS)

但很多输入法都不会遵守这个规则（点名批评 gboard），导致很多应用作者也不认真设定这些 flag ，甚至直接把 `VARIATION_VISIBLE_PASSWORD` 作为关闭输入法补全建议的方法，完全破坏了这些选项的语义。

be66341 给自带英文输入法加了一个选项“Disable word hint based on editor attributes”，关闭之后可以无视 InputType flag 强制启用英文补全
