### ISSUE TITLE
配置输入法时添加拼音提示不可用

### ISSUE THREAD

**Issue by BenYanYi** [fcitx5-android/fcitx5-android#447]
拉取项目后运行，在配置输入法中添加pinyin，pinyin设置中提示无可用配置项，该附件组件可能在Fcitx启动时处于禁用状态；在键盘中切换到pinyin，提示不可用

**Comment by rocka** [comment]
请提供编译环境的具体信息，以及应用运行时的日志

**Comment by rocka** [comment]
未收到回应故关闭
