### ISSUE TITLE
英文输入法的回车不应当同时执行输入上屏与回车

### ISSUE THREAD

**Issue by xz-dev** [fcitx5-android/fcitx5-android#448]
#### 摘要 / Summary

使用英文输入法，比如输入 okx，补全为 oka 等，这时我想用 okx，于是回车，这时不止输入 okx，而且还会之后立即跟上回车，这如果是空格符号等，确实没问题，但是回车往往还有执行的功能

#### 重现步骤 / Steps to Reproduce

1. 切换到英文输入法
2. 输入 okx
3. 回车
4. 发现输入 okx 加上回车

#### 预期行为 / Expected Behavior

只输入 okx

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android 14
- 应用版本 / App Version: 0.0.8-61-ga8661f8e
- 插件版本 / Plugins Version: 未使用

**Comment by rocka** [comment]
设计上就是这样的，英文输入法中的空格和回车在任何时候都表现为输入空格和回车，无论有没有补全候选词。如果你不想选择候选词，就不要按任何多余的按键。虽然 composing text 中包含下划线，但是它们已经被输入到了文本框中，不需要按回车去确认。

**Comment by xz-dev** [comment]
> 设计上就是这样的，英文输入法中的空格和回车在任何时候都表现为输入空格和回车，无论有没有补全候选词。如果你不想选择候选词，就不要按任何多余的按键。虽然 composing text 中包含下划线，但是它们已经被输入到了文本框中，不需要按回车去确认。

补充一下，我的英文输入法启用了单词提示
所以默认并不会进入文本框（这才是问题），所以这个行为和拼音输入法不一致了

**Comment by rocka** [comment]
在输入法设置中启用 “全局选项 - 在应用中显示预编辑文本”

**Comment by DdogezD** [comment]
启用 “全局选项 - 在应用中显示预编辑文本”, 之后, 依旧没有解决这个问题...奇怪
