### ISSUE TITLE
rime插件操作同步用户设置报错

### ISSUE THREAD

**Issue by WvvvWv** [fcitx5-android/fcitx5-android#452]
#### 摘要 / Summary
rime插件操作同步用户设置报错

#### 重现步骤 / Steps to Reproduce
installation文件填写自定义同步目录就会提示出现问题请查阅日志，删除sync_dir配置就不会报错且同步成功。

#### 日志 / Log
[org.fcitx.fcitx5.android-2024-03-23T10_33_34Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/14731228/org.fcitx.fcitx5.android-2024-03-23T10_33_34Z.txt)

#### 截图 / Screenshots
![976c5893ecaac6a9ecad88a92abdb3e](https://github.com/fcitx5-android/fcitx5-android/assets/40822202/64b97247-b3b6-40b9-8646-fa0ef0cb787a)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: samsung oneui6.1
- 应用版本 / App Version:0.0.8
- 插件版本 / Plugins Version: rime 0.0.8

**Comment by rocka** [comment]
因为输入法没有存储权限，所以不支持自定义 sync_dir ，请考虑使用支持 SAF 的目录同步工具，如 [FolderSync](https://foldersync.io/) ，或者使用 root 权限运行 syncthing 以访问输入法的数据目录。

**Comment by Orilx** [comment]
我在没有定义 sync_dir 的情况下也遇到了报错，抓取到的日志如下：
```
E/rime.fcitx-rime(26432): Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
E/rime.fcitx-rime(26432): failed to merge snapshot file: /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/sync/UNXBOOK/rime_ice.userdb.txt
E/rime.fcitx-rime(26432): failed synchronizing 1/1 user dict
```

**Comment by WvvvWv** [comment]
> 因为输入法没有存储权限，所以不支持自定义 sync_dir ，请考虑使用支持 SAF 的目录同步工具，如 [FolderSync](https://foldersync.io/) ，或者使用 root 权限运行 syncthing 以访问输入法的数据目录。

好的多谢，目前使用了[FolderSync](https://foldersync.io/)+[syncthing](https://syncthing.net/)进行同步，已经可以了。

**Comment by zhichengroup** [comment]
> 我在没有定义 sync_dir 的情况下也遇到了报错，抓取到的日志如下：
> 
> ```
> E/rime.fcitx-rime(26432): Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> E/rime.fcitx-rime(26432): failed to merge snapshot file: /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/sync/UNXBOOK/rime_ice.userdb.txt
> E/rime.fcitx-rime(26432): failed synchronizing 1/1 user dict
> ```

需要删除rime/.temp.userdb文件夹，可能删不掉，需要在app-高级导出用户数据，再重新导入，同步就可以了

**Comment by expoli** [comment]
这个好像是Fcitx5 rime 那边的问题，因为在Linux上也遇到过类似的问题（在Fcitx5意外退出的时候，会出现临时文件夹与锁文件，导致同步出错）

**Comment by expoli** [comment]
这个好像是Fcitx5 rime 那边的问题，因为在Linux上也遇到过类似的问题（在Fcitx5意外退出的时候，会出现临时文件夹与锁文件，导致同步出错）

**Comment by ITCJ** [comment]
请问可否使app和syncthing一样有内部存储下的文件夹的权限，随后在这个文件夹中使用synthing同步

**Comment by zhichengroup** [comment]
> 请问可否使app和syncthing一样有内部存储下的文件夹的权限，随后在这个文件夹中使用synthing同步

如果单指实现同步功能，是可以的

**Comment by PILIHU2022** [comment]
> 请问可否使app和syncthing一样有内部存储下的文件夹的权限，随后在这个文件夹中使用synthing同步

您好！请问怎么让Syncthing能够访问`Android/data/org.fcitx5.android/data/files/rime/sync`这个文件夹，我研究了好久😂
