### ISSUE TITLE
给平板端适配下

### ISSUE THREAD

**Issue by 0zjn0123** [fcitx5-android/fcitx5-android#453]
1，可以把键盘中央分割开留出位置或者变成一个小键盘(悬浮)
2，候选词的宽度调小
3，改进联想词准确率和模糊词

希望作者可以采纳🥳

**Comment by Eventide** [comment]
![Screenshot_20240327_211839](https://github.com/fcitx5-android/fcitx5-android/assets/3356210/b70ec9fa-b2ce-43d1-92e7-2224694fd070)
