### ISSUE TITLE
对剪切板功能建议

### ISSUE THREAD

**Issue by Tang-pure** [fcitx5-android/fcitx5-android#456]
#### 摘要 / Summary

像gbord一样定期清理剪切板内容避免国产app产生垃圾，并且可以的话添加开关
copy以后长按复制建议可以直接固定收藏
剪切板清除按钮区分收藏与非收藏内容

#### 替代方案 / Alternative Solution
或许可以建立识别自动清除垃圾短链的功能？

**Comment by Tang-pure** [comment]
还有就是类似搜狗输入法，在剪切板内长按一个项目可以选词部分粘贴而非全部粘贴，这样的话能十分方便贴连接等情况

**Comment by Zig-Rust-Odin** [comment]
固定功能已经实现. 
但是有一个的问题 剪切板清除2次 会把 固定内容也删除了😮‍💨

**Comment by rocka** [comment]
> 固定功能已经实现. 
> 但是有一个的问题 剪切板清除2次 会把 固定内容也删除了😮‍💨

“清除2次”时，操作提示是不同的。如果剪贴板数据库内所有条目都是被固定的，会询问“是否清除所有固定的条目”。
