### ISSUE TITLE
未适配A14，全面屏手势下键盘按键和系统按钮冲突

### ISSUE THREAD

**Issue by CanglanXYA** [fcitx5-android/fcitx5-android#458]
#### 摘要 / Summary

没有适配A14的键盘，隐藏手势线的全面屏手势下，系统不会主动抬高键盘，切换输入法和隐藏键盘按钮会和键盘上的符号键和回车键产生冲突，必须开启手势线主动抬高键盘后才能避免冲突

#### 预期行为 / Expected Behavior

系统主动在全面屏手势下抬高键盘避免冲突

#### 截图 / Screenshots

没有手势线
fctix
![Screenshot_20240331-142133_Trebuchet](https://github.com/fcitx5-android/fcitx5-android/assets/51688992/69328e36-a4d1-49bd-98d3-62891d1d1ed2)
系统自带键盘
![Screenshot_20240331-142139_Trebuchet](https://github.com/fcitx5-android/fcitx5-android/assets/51688992/9ab63f70-ce3d-4045-9e13-c9bc91c9eb71)

有手势线
![Screenshot_20240331-142204_Trebuchet](https://github.com/fcitx5-android/fcitx5-android/assets/51688992/94a2a505-5988-4296-82b8-84d3d939b066)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android 14 Lineage OS 21
- 应用版本 / App Version: 0.0.8 最新版
- 插件版本 / Plugins Version:

**Comment by rocka** [comment]
请暂时先在在输入法主题配置中，将“导航栏背景”设置为“跟随键盘背景色”。我没有 Android 14 设备，而且 Android Studio 模拟器中提供的 Android 14 系统镜像均不能复现此 bug。

**Comment by rocka** [comment]
在 Android 14 (LineageOS 21) 设备上测试，无法复现此问题。故关闭。

**Comment by CoelacanthusHex** [comment]
你是否使用了使 Nav Pill 沉浸的 Magisk 或者 Xposed 模块？如果是的话，该模块可能未适配 Android 14。请尝试换用 NavTweaks 模块。
https://github.com/Magisk-Modules-Alt-Repo/HideNavBar
