### ISSUE TITLE
由于一些手机android/data无法获取权限, 提供自定义配置存放的路径

### ISSUE THREAD

**Issue by TonyK922** [fcitx5-android/fcitx5-android#459]
#### 摘要 / Summary
可以自定义 rime配置存放的路径
这样有些无法获取android/data 目录权限的手机, 也可以用自己的配置了

#### 替代方案 / Alternative Solution
没找到

#### 附加信息 / Additional Context

**Comment by Dustin-Jiang** [comment]
> 如果你需要访问应用数据目录，请使用 Android 自带的 DocumentsUI ，或者支持 SAF 的文件管理器。

在 Google 2024.02 安全补丁中禁止了在 SAF 中授权软件访问 Android/data 目录，通过 DocumentsUI 访问 rime 配置目录经测无法写入。

![Screenshot_2024-04-23-10-21-22-869_com google android documentsui-edit](https://github.com/fcitx5-android/fcitx5-android/assets/56217843/402cb4e8-49f5-448e-8d9b-7a74b250d35c)

**Comment by rocka** [comment]
请在 DocumentsUI 侧边栏中选择“小企鹅输入法5”，而不是 Android/data 目录。参见： https://github.com/fcitx5-android/fcitx5-android/issues/171#issuecomment-1370562893
