### ISSUE TITLE
使用fcitx5-rime时一些功能失效

### ISSUE THREAD

**Issue by free-150** [fcitx5-android/fcitx5-android#462]
#### 摘要 / Summary

当我外接键盘时，在配置中设置了关于 Ctrl+Shift+“X” 这样的按键绑定会无效

#### 重现步骤 / Steps to Reproduce

使用 fcitx5-rime 插件。设置了 Ctrl+Shift+F 为切换繁体中文的快捷键但无效。
- 类似的还有 Ctrl+Shift+x 这样的基本都无效。还是发现一个内置的 Ctrl+Shift+U 为Unicode码输入，能否供写一个开关供用户关闭这些内置快捷键。
- 还有就是如果 rime 配置中有 emoji 符号也会无法显示

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: 13
- 应用版本 / App Version: 0.0.8
- 插件版本 / Plugins Version: 0.0.8

<img width="284" alt="图片" src="https://github.com/fcitx5-android/fcitx5-android/assets/92285544/d27cc451-81f3-4197-9a43-4b3a07759d7d">

<img width="823" alt="图片" src="https://github.com/fcitx5-android/fcitx5-android/assets/92285544/a8069e2d-d7b7-4d57-bf88-7f570a2b2418">

**Comment by rocka** [comment]
0.8.8 是哪个版本？

**Comment by wxyzh** [comment]
我使用雾凇拼音测试ctrl+shift+4或者ctrl+shift+3 功能正常
https://github.com/iDvel/rime-ice/blob/7ea7a678855aae794e922649f9fd9629e60a797a/default.yaml#L204-L207

**Comment by free-150** [comment]
我没试数字，只试了几个字母都不行

**Comment by wxyzh** [comment]
我改成ctrl+shift+f 也是正常的。

**Comment by rocka** [comment]
这里建议使用小写字母设定快捷键，比如 `Control+Shift+f` ，我在目前的版本上测试没有问题。

至于 Unicode 输入快捷键的问题，可以在 输入法设置 - 高级 界面中关闭 隐藏快捷键配置，然后在 输入法设置 - 附加组件 - Unicode 中即可修改其快捷键。

**Comment by free-150** [comment]
确实是大写引起的，改小写就没这问题了
