### ISSUE TITLE
为退格连续删除添加连续振动

### ISSUE THREAD

**Issue by quank123wip** [fcitx5-android/fcitx5-android#464]
#### 摘要 / Summary

因为退格（或可能的空格）具有连续输入功能，连续输入功能应该需要连续的振动反馈确保反馈精准。
#### 替代方案 / Alternative Solution

无
#### 附加信息 / Additional Context

暂无

**Comment by JUST-INTJ** [comment]
滑着删

**Comment by rocka** [comment]
Closed by #626
