### ISSUE TITLE
Unikey text appearance is not comfortable and difficult for typing

### ISSUE THREAD

**Issue by skbnoqtrjf** [fcitx5-android/fcitx5-android#465]
#### 摘要 / Summary

I used the Unikey plugin, but the texts I input the texts didn't appear on the typing box of the apps (green circle) but on the top left most of the keyboard (red circle). It's very difficult for my eyes to concentrate on the 2 different areas at the same time while typing. Note that this issue didn't happen with English, only Vietnamese (Unikey) and maybe other plugins. I already change some settings but not effective

I expect the texts should appear on the typing box of all apps

#### 附加信息 / Additional Context

![image](https://github.com/fcitx5-android/fcitx5-android/assets/143573917/fda32bd2-ec82-4403-9641-5e165c22e242)

**Comment by rocka** [comment]
Please enable "Global Options - Show preedit in application" in settings of this input method

**Comment by king1x32** [comment]
in the Termux app this error remains.
