### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by jianking123** [fcitx5-android/fcitx5-android#467]
Excuse me, what is this question，
How to solve
![9A17060BF5599D2FFE16ACFE15F653B2](https://github.com/fcitx5-android/fcitx5-android/assets/166801697/8e8c4609-97cd-4e78-bb36-1ea5d88a2e33)
A problem occurred configuring project ':app'.
> Illegal char <:> at index 155: D:\allDemo\fcitx5-android\app\property(org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, D:\allDemo\fcitx5-android\app\build))\generated\ksp\debug\kotlin

**Comment by rocka** [comment]
I see your are building on Windows, what's your JDK / Android Studio version?

I've never encountered this issue before, but I suspect it's

https://github.com/fcitx5-android/fcitx5-android/blob/364afb44dcf0d9e3db3d43a21a32601b2190cbdf/app/build.gradle.kts#L64-L68

You can try change `${layout.buildDirectory}` to `${layout.buildDirectory.asFile.get().name}`

**Comment by WhiredPlanck** [comment]
@rocka By the way, `${layout.buildDirectory}` seems to be deprecated, `layout.buildDirectory.dir` is now recommended by official. I have no idea if this can be helpful in this case.

**Comment by rocka** [comment]
No. `buildDir` was deprecated and `layout.buildDirectory` should be used instead.

https://github.com/gradle/gradle/blob/v8.7.0/subprojects/core-api/src/main/java/org/gradle/api/Project.java#L262-L270

**Comment by rocka** [comment]
Maybe

https://github.com/fcitx5-android/fcitx5-android/blob/364afb44dcf0d9e3db3d43a21a32601b2190cbdf/app/build.gradle.kts#L66

should be changed to

```kotlin
kotlin.srcDir(layout.buildDirectory.dir("generated/ksp/$name/kotlin"))
```

**Comment by jianking123** [comment]
My android studio version is 2023.2.1, I am a windows10 system, and now there are some new problems
![QQ截图20240414152413](https://github.com/fcitx5-android/fcitx5-android/assets/166801697/b08352e8-471b-4067-844c-7a640a5ffa92)
[log.txt](https://github.com/fcitx5-android/fcitx5-android/files/14969834/log.txt)
I think this may be very simple for you. I am a newbie, so I have many questions. I look forward to your reply.

**Comment by rocka** [comment]
Please follow the instructions in README.md for how to set up developtment environemnt on Windows.
