### ISSUE TITLE
双拼模式下v模式触发建v被占用无法使用

### ISSUE THREAD

**Issue by RimeKTiz6324** [fcitx5-android/fcitx5-android#469]
#### 摘要 / Summary
无法在双拼模式使用v模式快速输入

#### 重现步骤 / Steps to Reproduce
在双拼设置下的v模式启用键下方增加触发提示

#### 预期行为 / Expected Behavior
双拼设置下的v模式启用键下方出现触发提示

#### 设备信息 / Device Infomation

- 系统版本 / OS Version:
- 应用版本 / App Version:
- 插件版本 / Plugins Version:

**Comment by rocka** [comment]
应该到 https://github.com/fcitx/fcitx5-chinese-addons/issues 提个 issue
