### ISSUE TITLE
关于freestyle-playground版本

### ISSUE THREAD

**Issue by qwert-f** [fcitx5-android/fcitx5-android#470]
#### 摘要 / Summary

安装的时候错误选择了freestyle-style，然后一直请求指纹解锁或者脸部解锁后弹框报错，弹框无法关闭，应用也无法关闭
#### 重现步骤 / Steps to Reproduce

安装最新的freestyle-playground版本
#### 预期行为 / Expected Behavior

如摘要中描述的一只弹框，并且会影响其他操作，诸如使用系统设置切换输入法，清除后台

#### 日志 / Log

一直抢占我没成功点击到那个保存日志的按钮，隐约看到日志打了sqllite之类的后几行，然后输出变成红色
#### 设备信息 / Device Infomation

- 系统版本 / OS Version:coloros14
- 应用版本 / App Version:0.0.8-63

**Comment by qwert-f** [comment]
同时可能事频繁进行了弹窗的操作之类的原本应用正常的0.0.8-85版本的也被系统识别为高风险病毒了

**Comment by oldherl** [comment]
什么是freestyle？

**Comment by rocka** [comment]
Jenkins 上的 [freestyle-playground](https://jenkins.fcitx-im.org/job/android/job/fcitx5-android-freestyle-playground/) 是 https://github.com/fcitx5-android/fcitx5-android/tree/playground 分支的构建，是用于测试构建流程或者不稳定功能的“playground”，仅供开发者测试使用。

由于 https://github.com/fcitx5-android/fcitx5-android/commit/652d13d9335cf2c9b57960f3a4e5fe07c7dfe317 为剪贴板数据库增加了 sensitive 字段，改变了数据库的 schema ，导致旧版本应用无法识别新版数据库，在应用初始化阶段就会发生 crash 。而且 crash handler 并没有检测循环 crash 的机制，导致一直循环重启。

**Comment by rocka** [comment]
should be fixed by https://github.com/fcitx5-android/fcitx5-android/compare/ee59f397764d...560dda60449b
