### ISSUE TITLE
空格移动光标会超出输入框范围

### ISSUE THREAD

**Issue by Tarlafic** [fcitx5-android/fcitx5-android#472]
#### 摘要 / Summary
在部分文字框中通过滑动空格键来移动光标，焦点会移至输入区相邻的其他页面要素

#### 重现步骤 / Steps to Reproduce
1. 打开移动版 Github 页面
2. 点击搜索框 
3. 向右滑动空格键
4. 焦点移至清空按钮

#### 预期行为 / Expected Behavior
光标应当停在输入区最右端（AOSP 输入法、Gboard、Swiftkey 均为如此）

#### 设备信息 / Device Infomation
- Android 14 (crDroid 10.3)
- Fcitx5 0.0.8-0-g4c8399ad

#### 附加信息 / Additional Context
使用 BerryBrowser 浏览器

**Comment by ccyybn** [comment]
才发现有这个功能，感觉光标相对Gboard移动的有点慢，调成 `selectionSwipeThreshold = dp(5f)` 就舒服多了

**Comment by rocka** [comment]
我测试了一下 Chrome 没有这个问题； BerryBrowser 确实能复现这个问题，但即使用物理键盘的方向键移动光标，也会导致焦点被移动到别的控件上，所以我认为是它实现的问题。

另外 99b9452 给输入法模拟的按键添加了 scancode ，大概能修复某些应用里划动空格移动光标时焦点跑出输入框的问题，但是具体哪些应用受影响我也不知道。

**Comment by sdvcrx** [comment]
我这边在微信聊天输入框中遇到过。重现方式：输入一段文字，空格移动光标往最左移动，光标会消失不见，也不能再输入文字。
往右移动光标是正常的。

**Comment by rocka** [comment]
Should be fixed by 63735fb42f7b905545f1975aea3f0bff38907c8d
