### ISSUE TITLE
某个app上五笔输入法,输入后,选中文字,输入框原来的字母不会消失,文字上屏位置错位.

### ISSUE THREAD

**Issue by sundys** [fcitx5-android/fcitx5-android#473]
输入法版本, 截止今天的最新版本0.0.8-85

出现问题的安卓APP:

https://wwm.lanzout.com/i9WHg1v85hra      密码:1234

上面这个APP任意输入框都可以复现些问题:

五笔打字, 比如 天 字, 输入gd,   在候选框选中 天 字,,    输入框里面的gd不会消失, 变成  gd天  ,  如果拉着再打字光标会跑到gd和天字的中间, 正常输入字母选中文字自动上屏, 实际是在字母后面上屏.

在此APP上换其它输入法无此问题,   但是在其它app上使用企鹅输入法没有问题,  好像就是在这个app上无法正确上屏.

现在不知道到底是输入法问题还是app问题导致. 请大佬确认一下.

**Comment by rocka** [comment]
关闭“全局选项 - 在程序中显示预编辑文本”只之后，能否正确输入？

**Comment by sundys** [comment]
> 关闭“全局选项 - 在程序中显示预编辑文本”只之后，能否正确输入？

关闭可以正常使用了,感谢!  自己在设置看了好久,一直没看懂这个菜单的作用.

**Comment by rocka** [comment]
只能说又是一个对 [setComposingText](https://developer.android.com/reference/android/view/inputmethod/InputConnection#setComposingText(java.lang.CharSequence,%20int,%20android.view.inputmethod.TextAttribute)) 处理不好的应用
