### ISSUE TITLE
希望 符号键盘 也可以启用 按键边框 和 按键水波纹特效

### ISSUE THREAD

**Issue by ccyybn** [fcitx5-android/fcitx5-android#474]
#### 摘要 / Summary
符号键盘 也可以启用按键边框效果，现在这样  主键盘  和  符号键盘  不一致，看起来不协调，可以参考Gboard的效果

#### 附加信息 / Additional Context
Gboard 符号键盘

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/f033ec60-284a-4904-a6ae-641beaaba80a)

Fcitx5 符号键盘
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/8d6c4681-9972-4fbe-8b5c-5e5d5a888e25)

**Comment by ccyybn** [comment]
@rocka 那能不能像Gboard一样，提供一个只有 “常用符号” 的真键盘呢，没有边框，而且可以划来划去的，按起来总不踏实

**Comment by rocka** [comment]
就是因为讨厌符号“键盘”所以才写的符号“选择器”啊 ……

**Comment by JavaZeroo** [comment]
> 就是因为讨厌符号“键盘”所以才写的符号“选择器”啊 ……

那这个符号选择器可以自定义键位吗？包括下滑输入这种符号的位置。想修改为Gboard的位置。
