### ISSUE TITLE
文本编辑界面适配按键边框UI

### ISSUE THREAD

**Issue by Reweng** [fcitx5-android/fcitx5-android#479]
#### 摘要
文本编辑界面的按键边框是由分隔线组成的，太简陋了，跟键盘界面的按键边框不是很搭配
![Screenshot_20240425-061025_com google android apps nexuslauncher](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/52063857-b6e1-4b71-ba64-e860c44afea8)
![Screenshot_20240425-061614_com google android apps nexuslauncher](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/5ff939a8-338a-4f25-b713-d5c19f5b052f)

#### 替代方案
可以参考一下Gboard的文本编辑界面
![Screenshot_20240425-061531_com google android apps nexuslauncher](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/deec1889-bd19-40b7-8d81-0d5371f08870)

**Comment by rocka** [comment]
因为我觉得这个巨大的边框非常丑，所以没有做。谁想要可以自己写。

**Comment by ccyybn** [comment]
支持一下，个人觉得，各界面都受主题控制更好一点，让用户自己调，避免有人觉得好看，有人又觉得不好看的问题

https://github.com/fcitx5-android/fcitx5-android/issues/474

**Comment by ccyybn** [comment]
我之前没有接触过 Android开发，但经过一翻研究，自己改了一下，顺便把符号键盘的边框也加上了，不然怎么看都别扭

这是相关改动，你可以自己编译一下
https://github.com/ccyybn/fcitx5-android/commit/ef78c8e72f324eea0c0ca2a6f5da95c5dbc7d7bc

APK
https://github.com/ccyybn/fcitx5-android/releases/tag/0.0.9

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/b3449f46-0e03-4cf8-be19-380c97f78acb)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/c82a4975-dbe2-4473-ae94-1bd1d202b821)

**Comment by Reweng** [comment]
> 之前没有接触过 Android开发，但经过一番研究，我自己改了一下，顺便把符号键盘的边框也加上了，不然怎么看都别扭
> 
> 这是相关改动，你可以自己编译一下 [ccyybn@ef78c8e](https://github.com/ccyybn/fcitx5-android/commit/ef78c8e72f324eea0c0ca2a6f5da95c5dbc7d7bc)
> 
> APK https://github.com/ccyybn/fcitx5-android/releases/tag/0.0.9
> 
> ![image](https://private-user-images.githubusercontent.com/7237501/326196016-b3449f46-0e03-4cf8-be19-380c97f78acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDQzMjEsIm5iZiI6MTcxNDI0NDAyMSwicGF0aCI6Ii83MjM3NTAxLzMyNjE5NjAxNi1iMzQ0OWY0Ni0wZTAzLTRjZjgtYmUxOS0zODBjOTdmNzhhY2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMTg1MzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ0MjdlNjRkNDYzMjlhOTBhYTEyYTJiYWQ5MThiODEzZWU0MGI2MDA3Y2QzZWVjZDhlZDQ1OGMyMDUzYWU3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k-5lfugOxcjmeejT62lYPyDMhZnwQDZUciBoiFX4So0) ![image](https://private-user-images.githubusercontent.com/7237501/326196580-c82a4975-dbe2-4473-ae94-1bd1d202b821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDQzMjEsIm5iZiI6MTcxNDI0NDAyMSwicGF0aCI6Ii83MjM3NTAxLzMyNjE5NjU4MC1jODJhNDk3NS1kYmUyLTQ0NzMtYWU5NC0xYmQxZDIwMmI4MjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMTg1MzQxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk3YjRlYzRmMDE3YWE5ZWU2NTc2MGI2OGRmNmMzZjZlZTY1YWQzNTg5NzI5ZWMzNmUyZmU0NjZjYzI3YjljMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rHQQYWaCOoQ_JLtGC_dvM6UtKQyPVIfWzJHq2nT7L8g)

显示效果很完美，就连按键圆角半径也跟主键盘统一了
显示效果图（按键圆角特意调大了）
![IMG_20240428_030418](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/1b694ed0-6dfe-4fa6-beb8-8e3e68b10af6)
![IMG_20240428_030437](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/0d38ce44-4730-444b-a379-4923c29d0a3b)
![Screenshot_20240428-030310_com google android apps nexuslauncher](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/c578e14f-3f47-42b3-91f6-bc8e755471ef)
![IMG_20240428_030404](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/d313cc94-e208-4d77-909e-2e74720e429d)
我用到的主题配置
[GboardMonetDark.zip](https://github.com/fcitx5-android/fcitx5-android/files/15139545/GboardMonetDark.zip)
[GboardMonetLight.zip](https://github.com/fcitx5-android/fcitx5-android/files/15139546/GboardMonetLight.zip)

**Comment by Reweng** [comment]
@ccyybn 非常感谢你的工作🥰🥰🥰

**Comment by ccyybn** [comment]
不客气，我又加了个功能，可以独立调整 文本编辑按钮的圆角，主要是这边按钮较大，我觉得可以把圆角调大一些更好看

你可以自己编译，或重新下载

https://github.com/ccyybn/fcitx5-android/commit/67af8140a622305a9379742904ec7c5e7a4f23c1
https://github.com/ccyybn/fcitx5-android/releases

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/ff2a2530-13be-44fa-af98-2bdec6963bca)


![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/87254860-a7a6-434b-906e-caa8e1ccccd6)

**Comment by ccyybn** [comment]
我主要是没整明白这里是怎么显示成这样的，我的这里一直是个隐身图标

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/d887a238-3d03-4aff-a044-7facd5514c0d)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/432eca14-b0a6-474a-8a5f-00a7cbcafe50)

**Comment by Reweng** [comment]
> 不客气，我又加了个功能，可以独立调整 文本编辑按钮的圆角，主要是这边按钮较大，我觉得可以把圆角调大一些更好看
> 
> 你可以自己编译，或重新下载
> 
> [ccyybn@67af814](https://github.com/ccyybn/fcitx5-android/commit/67af8140a622305a9379742904ec7c5e7a4f23c1) https://github.com/ccyybn/fcitx5-android/releases
> 
> ![image](https://private-user-images.githubusercontent.com/7237501/326204177-ff2a2530-13be-44fa-af98-2bdec6963bca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDY3NTgsIm5iZiI6MTcxNDI0NjQ1OCwicGF0aCI6Ii83MjM3NTAxLzMyNjIwNDE3Ny1mZjJhMjUzMC0xM2JlLTQ0ZmEtYWY5OC0yYmRlYzY5NjNiY2EucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMTkzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA3YjU3MTYxM2Y2ZGQwMjM3ZGIyYjI1ZmFlODg3ZmFhOGFiN2Q4ZWI1MjE3MDIzMmQ0M2NiNDIyOTk1NDFhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fjDGdD28BXi6t8JowU2vN211Q96NbWVZtUf2jY46cLQ)
> 
> ![image](https://private-user-images.githubusercontent.com/7237501/326204143-87254860-a7a6-434b-906e-caa8e1ccccd6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDY3NTgsIm5iZiI6MTcxNDI0NjQ1OCwicGF0aCI6Ii83MjM3NTAxLzMyNjIwNDE0My04NzI1NDg2MC1hN2E2LTQzNGItOTA2ZS1jYWE4ZTFjY2NjZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjdUMTkzNDE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTQ5MTBjNTQwZjE0N2U1NDIxMjhkZGY3MjU0OTJlNjYyY2JkNzQwNDJlNjJjOTQ3NDU1MWViYjlmZjVkMzBhMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CnImiLS9m8jz3sukX6uwnosBNDLcXyFbg_2-nUKFmqU)

好好好🥰🥰🥰
还能加一个调节剪切板词条圆角半径调节吗，这样UI显示就更统一协调了。或者 剪切板词条圆角半径调节 也合并进 文本编辑按钮的圆角调节，剪切板词条按钮也挺大的。
![IMG_20240428_033847](https://github.com/fcitx5-android/fcitx5-android/assets/41164901/5846f159-d8aa-4bb3-b317-7e8b6c5d166a)

**Comment by ccyybn** [comment]
剪贴板这个我还没弄懂

**Comment by ccyybn** [comment]
剪贴板感觉不是按钮，不太好改，不过目前我觉的已经可以接受了

**Comment by Reweng** [comment]
> 剪贴板感觉不是按钮，不太好改，不过目前我觉的已经可以接受了

没关系的，改不了就算了

**Comment by rocka** [comment]
这个感觉比 gboard 的风格要好看一些， @ccyybn 有没有兴趣 PR 一下？

> 我主要是没整明白这里是怎么显示成这样的，我的这里一直是个隐身图标
> 
> ![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/d887a238-3d03-4aff-a044-7facd5514c0d) ![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/432eca14-b0a6-474a-8a5f-00a7cbcafe50)

左上角显示隐身图标的原因是编辑器设置了 [EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#IME_FLAG_NO_PERSONALIZED_LEARNING) ，通常在浏览器的隐身模式里出现。这时候会给 fcitx 设置 `CapabilityFlag::Sensitive` ，指示输入法不要记录输入历史。

https://github.com/fcitx5-android/fcitx5-android/blob/59558c5b624359455911082b10750f4dcbd10fe8/app/src/main/java/org/fcitx/fcitx5/android/core/CapabilityFlag.kt#L103-L105

**Comment by ccyybn** [comment]
剪贴板我搞懂怎么改了，已经弄好了，感觉稍微加大一点圆角确实要好看一些

https://github.com/ccyybn/fcitx5-android/releases/tag/0.0.9-7

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/c5a574d5-e766-4ff3-8d08-8ced0ccd9bad)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/bd319082-9198-407e-828e-6e7f8b07a5e6)

**Comment by ccyybn** [comment]
@rocka 安卓新手没怎么注意代码规范，那我先提个试试，符号键盘的边框就先不提了，因为没加开关，而且在选emoji的时候有边框会有点怪
