### ISSUE TITLE
使用rime插件时，如果输入方案开启了`enable_correction`选项，输入时会崩溃

### ISSUE THREAD

**Issue by Youxikong** [fcitx5-android/fcitx5-android#483]
#### 摘要 / Summary
使用rime插件作为输入法时，如果rime引擎使用的方案，开启了`enable_correction`选项，此时输入文字有概率会崩溃。

#### 重现步骤 / Steps to Reproduce
1. 打开中州韵/rime的用户数据目录；
2. 为所使用的输入方案添加定制化配置文件，如`rime_ice.custom.yaml`；
3. 输入以下配置并保存；
```yaml
patch:
    'translator/enable_correction': true
```
4. 进入输入界面，选择菜单选项的`重载配置`；
5. 输入c、e，此时输入法会崩溃。

#### 预期行为 / Expected Behavior
应正常出现待选文字。

#### 日志 / Log
未找到日志的位置。

#### 截图 / Screenshots
无

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android 13
- 应用版本 / App Version: 0.0.9-0-g8dc51356-release
- 插件版本 / Plugins Version: 0.0.9-0-g8dc51356

#### 附加信息 / Additional Context
无

**Comment by rocka** [comment]
https://github.com/rime/librime/pull/863

**Comment by rocka** [comment]
fixed by c8f6d25
