### ISSUE TITLE
需要按词频优化英文键盘单词的权重

### ISSUE THREAD

**Issue by ccyybn** [fcitx5-android/fcitx5-android#484]
#### 摘要 / Summary
现在英文键盘单词没有按词频排序，导致很多常见词，必须完整输入，才能匹配，极大增加了按键次数

比如
输入lo，结果是大量的生僻词
输入loo，**look** 也仅仅排在第四位

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/91ead86f-c730-4e8b-a408-3d011428722e)

#### 替代方案 / Alternative Solution
而对比一下用 **Ngram** 词频数据优化后的效果

输入lo，分别是 **long, look, love, local**
输入loo，分别是 **look, looked, looking, looks**

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/65032119-6f9f-44cd-be45-6ffe6a0e76d6)

#### 附加信息 / Additional Context
词频数据我已经整理好了，来自 [Google Ngram data](https://storage.googleapis.com/books/ngrams/books/datasetsv3.html)

由于一共有600万条（包括大量拼写错误），与牛津词典单词做交集，过滤出如下 76431条单词+词频

[dict_words.txt](https://github.com/fcitx5-android/fcitx5-android/files/15127657/dict_words.txt)

**Comment by ccyybn** [comment]
[dict_words.txt](https://github.com/fcitx5-android/fcitx5-android/files/15133839/dict_words.txt)

重整了一份，加入了缩写 didn't isn't 等等

**Comment by Marukon** [comment]
请教下这个文件怎么使用
