### ISSUE TITLE
英文键盘会出现并不匹配的单词

### ISSUE THREAD

**Issue by ccyybn** [fcitx5-android/fcitx5-android#485]
#### 摘要 / Summary
输入 autobi，会出现大量不匹配的单词置顶

#### 重现步骤 / Steps to Reproduce
输入 autobi

#### 预期行为 / Expected Behavior
只出现匹配的单词， **autobigraphy, autobigraphies** 等以autobi开头的单词

#### 截图 / Screenshots
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/d95bb1bb-18a2-4d39-8476-d16efccff598)

#### 设备信息 / Device Infomation

- 系统版本 / OS Version: Android 12
- 应用版本 / App Version: 0.0.9
- 插件版本 / Plugins Version:

**Comment by rocka** [comment]
It's error correction based on edit distance: https://github.com/fcitx/fcitx5/blob/5.1.9/src/modules/spell/spell-custom-dict.cpp#L316 . It's a feature.

**Comment by ccyybn** [comment]
> It's error correction based on edit distance: https://github.com/fcitx/fcitx5/blob/5.1.9/src/modules/spell/spell-custom-dict.cpp#L316 . It's a feature.

这个特性很不合理好吧，用户输入autobi，出现一堆不相关的结果，任何人都会觉得就是bug，或者叫设计上的bug

**Comment by ccyybn** [comment]
> It's error correction based on edit distance: https://github.com/fcitx/fcitx5/blob/5.1.9/src/modules/spell/spell-custom-dict.cpp#L316 . It's a feature.
> 
> <img alt="" width="360" src="https://private-user-images.githubusercontent.com/13914967/326158612-cf8822a8-71d5-4a63-a66c-788fb4552c0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTg1MTIsIm5iZiI6MTcxNDE5ODIxMiwicGF0aCI6Ii8xMzkxNDk2Ny8zMjYxNTg2MTItY2Y4ODIyYTgtNzFkNS00YTYzLWE2NmMtNzg4ZmI0NTUyYzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA2MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMTVjOTZhNTM0NTdhZmQzMWY2ODg1OWZmYmQ2ZTMwNGRkMTlhZjFlYWNkMjQ0NDIzN2RmMTMxODc0ZGI3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iim3FFnrfIv3hjW6pZM19zCq0wCWrUKx94ZDj6rn_6A">

我明白你的意思，就是在输入错误不匹配的时候能够自动纠正是吧，但是在输入正确匹配的时候，不能覆盖用户的意愿吧，至少应该让匹配的置顶

**Comment by rocka** [comment]
Actually, **autobigraphy** is not a word, the correct form is autobi**o**graphy, with the input method has suggested below.

**Comment by ccyybn** [comment]
> Actually, **autobigraphy** is not a word, the correct form is autobi**o**graphy, with the input method has suggested below.

这是我的笔误，我是指前缀autobi匹配，其实是想输入autobiography 来着

**Comment by ccyybn** [comment]
> Actually, **autobigraphy** is not a word, the correct form is autobi**o**graphy, with the input method has suggested below.

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/79d05a01-bfce-4d49-a0a2-f216f8ba20a5)

**Comment by ccyybn** [comment]
> Actually, **autobigraphy** is not a word, the correct form is autobi**o**graphy, with the input method has suggested below.

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/c99eda5c-c5d4-42bd-ba3f-ffa945546b1f)

**Comment by ccyybn** [comment]
> Then you are welcomed to contribute a new English word completion/correction engine to https://github.com/fcitx/fcitx5/tree/master/src/modules/spell . Both desktop fcitx5 users and fcitx5-android users can benefit from it.

好吧，有问题自己改是吧，打扰了

**Comment by rocka** [comment]
Sorry but I just don't have time (and interest) to implement every feature request in the issues list. There are too few contributors. Open source software only improves when more people work on implementing their own ideas.

**Comment by ccyybn** [comment]
> Sorry but I just don't have time (and interest) to implement every feature request in the issues list. There are too few contributors. Open source software only improves when more people work on implementing their own ideas.

I understand, so I closed the other feature request I opened yesterday. If this feature is not a bug, I think it is not necessary to waste time sorting words by frequency.
