### ISSUE TITLE
下划展开候选词/语音输入按钮收起键盘

### ISSUE THREAD

**Issue by LiuGaoRui** [fcitx5-android/fcitx5-android#486]
右上角的箭头并不总是能关闭输入法，在有预选词的时候。
有一个经常碰到的场景是，我在输入的时候，已经将所需信息输入完毕，此时一直会有后续词语联想，这种情况下右上角的箭头不能关闭输入框，而是展开全部候选词，此时会不知道如何关闭输入法，而且并不敢直接返回和按回退键，心里上会怕当前页面被返回和删除已输入内容。
希望可以优化设计，做到随时可以关闭输入法。
此事会极大优化我的体验，感谢

**Comment by rocka** [comment]
左划退格键即可清空预测候选

**Comment by LiuGaoRui** [comment]
我尝试了左划删除键，会将已输入内容全部删除，并不能清空候选词。
而且好的设计希望能一步做到关闭，任何两步都会拖累使用体验

**Comment by LiuGaoRui** [comment]
> 左划退格键即可清空预测候选

我试着按了左划删除键，将已输入的内容全部删除，并不能清空候选词。
而且好的设计希望能一步实现关闭，任何两步都会拖累使用体验

**Comment by rocka** [comment]
左划退格键清空预测候选词的功能已经在 c638e40 实现。请更新到最新 Release 版本 https://github.com/fcitx5-android/fcitx5-android/releases/latest

**Comment by LiuGaoRui** [comment]
> 左划退格键清空预测候选词的功能已经在[c638e40](https://github.com/fcitx5-android/fcitx5-android/commit/c638e408008a06eaa54e4e90b521c4eb6404f626)实现。请更新到最新发布版本https://github.com/fcitx5-android/fcitx5-android/releases/latest

感谢提醒，但是仍没解决我提得问题，重点是一步关闭输入法。

**Comment by mokapsing** [comment]
三键点返回，全面屏手势就侧划

**Comment by rocka** [comment]
如果你真的非常需要“随时”关闭键盘，建议关闭预测。

> 希望可以优化设计，做到随时可以关闭输入法。
> 此事会极大优化我的体验，感谢
> 而且好的设计希望能一步实现关闭，任何两步都会拖累使用体验
> 感谢提醒，但是仍没解决我提得问题，重点是一步关闭输入法。

希望你能给出具体的解决方案，“好的设计”是什么样的，比如如何设计键盘，在哪添加按钮，在什么情况下按哪个按钮会达到什么效果。我自己不用预测功能所以这个功能对我来说无所谓。

**Comment by LiuGaoRui** [comment]
> 如果你真的非常需要“随时”关闭键盘，建议关闭预测。
> 
> > 希望可以优化设计，实现随时可以关闭输入法。
> > 这会极大地提高我的体验，感谢
> > 并且良好的优化设计希望能够一次实现关闭，任何两步都会拖累使用疲惫的体验
> > 感谢提醒，但仍然没有解决我提的问题得问题，重点是一步关闭输入法。
> 
> 希望你能给出具体的解决方案，“好的设计”考虑的，比如如何设计键盘，在哪添加按钮，在什么情况下按哪个按钮会达到什么效果。我自己不用预测功能所以这个功能对我来说无所谓。

看了搜狗的方案，建议预测候选词改为左右滑动，右侧箭头取消展开面板功能，保持关闭输入法功能

**Comment by rocka** [comment]
> 预测候选词改为左右滑动，右侧箭头取消展开面板功能，保持关闭输入法功能

这样会使同一种候选词界面拥有两种完全不同的操作逻辑，显然也不能算是“好的设计”。另外，现在输入法前端没有能力区分候选词是来自用户输入，还是预测。

**Comment by LiuGaoRui** [comment]
> > 预测候选词改为左右滑动，右侧箭头取消展开面板功能，保持关闭输入法功能
> 
> 这样使得同一个候选词界面拥有两种不同的操作逻辑，显然也不能完全“好的设计”。另外，现在输入法前置没有能力区分候选词是来自用户输入，还是预测。

另一个方案，右上角的箭头按钮增加下滑直接关闭功能，可行吗

**Comment by rocka** [comment]
> 另一个方案，右上角的箭头按钮增加下滑直接关闭

这个方案还可以，顺便也能解决语音输入按钮和收起键盘互斥的问题

**Comment by Tarlafic** [comment]
可以给空格键安排一个下滑收起输入法
swiftkey在键盘全区域下滑均可收起输入法，不过这样会跟下滑输入标点符号冲突

**Comment by rocka** [comment]
8b4c3a7
