### ISSUE TITLE
希望增加读写权限，方便rime的多设备同步

### ISSUE THREAD

**Issue by HuangTD1995** [fcitx5-android/fcitx5-android#487]
### 摘要 / Summary

目前rime的同步文件夹只能在应用对应的文件夹里面，不能设在其他地方，而应用文件夹其他应用不能够访问，这样就不能进行多设备同步了，每次只能手动同步，希望能够增加该功能，应该就是个权限申请的问题

### 系统版本 / OS Version

android 13

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by rocka** [comment]
首先，其它应用可以访问到数据目录，请使用支持 SAF 的文件管理器或系统自带的 Documents UI ，参见： https://github.com/fcitx5-android/fcitx5-android/issues/171#issuecomment-1370562893

另外，也有类似 [FolderSync](https://foldersync.io) 等支持 SAF 的文件同步工具。

最后，高版本 Android 中，申请访问某个目录的权限也需要通过 SAF 并使用 Java API 访问文件，然而 librime 的同步目录需要一个路径，申请了也没法用。

**Comment by HuangTD1995** [comment]
谢谢，我对安卓这块不是特别清楚
