### ISSUE TITLE
rime插件将繁简模式切换成简体中文模式后，重新部署后又自动变成默认的繁体模式

### ISSUE THREAD

**Issue by qiuzhiqian** [fcitx5-android/fcitx5-android#492]
### 摘要 / Summary

rime插件将繁简模式切换成简体中文模式后，重新部署后又自动变成默认的繁体模式。

由于我的linux上面，也是使用的fcitx5+rime的方案，但是并没有遇到这个问题，所以我看了一下两者的差异，发现linux上面，设置了简体中文后，会在user.yaml中添加`simplification: true`的option
实际情况如下：

```
$ cat ~/.local/share/fcitx5/rime/user.yaml 
var:
  last_build_time: 1714285469
  option:
    simplification: true
  previously_selected_schema: double_pinyin_flypy
  schema_access_time:
    double_pinyin_flypy: 1714285229
    luna_pinyin: 1714285184
```
而对应的安卓版本并没有生成simplification: true，我手动在安卓的user.yaml中添加这个option后，重新部署后就能够正常保持住之前设置的繁简模式了。

### 重现步骤 / Steps to Reproduce

1、打开输入法输入界面
2、点击右侧的三个点(...)
3、切换繁简模式为 汉字 -> 漢字 模式
4、点击重载配置

### 预期行为 / Expected Behavior

重载配置后繁简模式应该保持为汉字 -> 漢字 模式

### 系统版本 / OS Version

HMOS 4.0

### 应用版本 / App Version

0.0.8-0-g4c8399ad-release

### 插件版本 / Plugins Version

rime 0.0.8-0-g4c8399ad

**Comment by rocka** [comment]
显然是 librime bug: https://github.com/rime/librime/issues/760

更新到 0.0.9 ，已经 patch 过了
