### ISSUE TITLE
F-droid上 0.0.9 版本安装时系统提示有风险

### ISSUE THREAD

**Issue by gmg137** [fcitx5-android/fcitx5-android#493]
### 摘要 / Summary

在华为手机上使用F-droid更新fcitx-android 到0.0.9版本时提示有风险，风险类型是a.gray.BulimiaTGen.h。

### 重现步骤 / Steps to Reproduce

在华为手机通过F-drid安装

### 预期行为 / Expected Behavior

正常安装

### 系统版本 / OS Version

鸿蒙4.0

### 应用版本 / App Version

0.0.9

**Comment by PapainTea** [comment]
安装报毒就关wifi/流量，在无网络环境下安装。安装完成后手机管家病毒扫描中给予Fcitx5-Android应用白名单，避免支付报毒

**Comment by LatticeLadder** [comment]
> 目前我是忽略提醒直接安装的，建议还是能治标又治本的解决问题。

这是腾讯病毒库报毒，要申诉的话不好搞，备案难。开源软件用爱发电，还倒贴钱钱备案，对人就太不厚道了

**Comment by wxyzh** [comment]
我的建议是，信任就用。

**Comment by gmg137** [comment]
不是信不信任的问题，前段xz被植入后门就是太让人信任了。0.0.8的时候是没有提示的，搜了下好像说是打包的问题gi不一定对，如果能解决问题也是造福更多的人，对软件的推广有利无弊，让更多的人能用到对作者来说也是一种助力。 如果不能给出有价值的建议，就不要阴阳怪气。

**Comment by wengxt** [comment]
这是开源项目，你可以自己编译，逻辑上都是不明来源，你确实没有道理非要信任某个来源，编译难度并不大

你可以把风险类型丢到搜索引擎里搜一下了解一下，看看别人写app被报是怎么解决的，就知道我们没这种条件去搞，没有公司也没有备案

就算跟随那些途径的办法也不是一天就能给你变出来的
