### ISSUE TITLE
切换输入法时重置大写锁定状态 / Reset CapsLock When Switching Between IMEs

### ISSUE THREAD

**Issue by shanoaice** [fcitx5-android/fcitx5-android#496]
### 摘要 / Summary

有时在输入英语缩写时为了方便会开启大写锁定，但输入完缩写词后切换回中文输入法需要手动关闭大写锁定才能正常输入，有些不便。希望能增加设置，允许在输入法之间切换时重置大写锁定状态。

Sometimes when typing abbreviations, one would enable CapsLock for convenience. However, after the input of abbreviations, switching back to Chinese (or similarly any other IMEs) does not reset CapsLock status. This adds an extra step of operation before you can start typing in another language. I suggest to add a setting allowing the automatic reset of CapsLock status after switching between IMEs, to simplify the typing experience.

### 系统版本 / OS Version

Android 14 (Xiaomi HyperOS 1.0.7.0)

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
done in https://github.com/fcitx5-android/fcitx5-android/commit/d70ca7a312166f4d32512d22b33e99d2e9b08af6
