### ISSUE TITLE
编译错误 "fcitx5" not an existing 

### ISSUE THREAD

**Issue by YX-G** [fcitx5-android/fcitx5-android#497]
### 摘要 / Summary

 

> Task :lib:fcitx5:configureCMakeDebug[arm64-v8a] FAILED
C/C++: CMake Warning at CMakeLists.txt:23 (find_package):
C/C++:   By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "fmt", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "fmt" with any of
C/C++:   the following names:
C/C++:     fmtConfig.cmake
C/C++:     fmt-config.cmake
C/C++:   Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
C/C++:   to a directory containing one of the above files.  If "fmt" provides a
C/C++:   separate development package or SDK, be sure it has been installed.
C/C++: CMake Warning at CMakeLists.txt:27 (find_package):
C/C++:   By not providing "FindLibIntl.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "LibIntl", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "LibIntl" with any
C/C++:   of the following names:
C/C++:     LibIntlConfig.cmake
C/C++:     libintl-config.cmake
C/C++:   Add the installation prefix of "LibIntl" to CMAKE_PREFIX_PATH or set
C/C++:   "LibIntl_DIR" to a directory containing one of the above files.  If
C/C++:   "LibIntl" provides a separate development package or SDK, be sure it has
C/C++:   been installed.
C/C++: CMake Warning at CMakeLists.txt:31 (find_package):
C/C++:   By not providing "Findlibuv.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "libuv", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "libuv" with any of
C/C++:   the following names:
C/C++:     libuvConfig.cmake
C/C++:     libuv-config.cmake
C/C++:   Add the installation prefix of "libuv" to CMAKE_PREFIX_PATH or set
C/C++:   "libuv_DIR" to a directory containing one of the above files.  If "libuv"
C/C++:   provides a separate development package or SDK, be sure it has been
C/C++:   installed.
C/C++: CMake Error at fcitx5/CMakeLists.txt:9 (add_custom_target):
C/C++:   add_custom_target cannot create target "cmake" because another target with
C/C++:   the same name already exists.  The existing target is a custom target
C/C++:   created in source directory
C/C++:   "D:/code/fcitx5-android/lib/fcitx5/src/main/cpp".  See documentation for
C/C++:   policy CMP0002 for more details.
C/C++: CMake Error at fcitx5/CMakeLists.txt:11 (add_custom_target):
C/C++:   add_custom_target cannot create target "notifications" because another
C/C++:   target with the same name already exists.  The existing target is a custom
C/C++:   target created in source directory
C/C++:   "D:/code/fcitx5-android/lib/fcitx5/src/main/cpp".  See documentation for
C/C++:   policy CMP0002 for more details.
C/C++: CMake Warning at fcitx5/CMakeLists.txt:23 (find_package):
C/C++:   By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "fmt", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "fmt" with any of
C/C++:   the following names:
C/C++:     fmtConfig.cmake
C/C++:     fmt-config.cmake
C/C++:   Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
C/C++:   to a directory containing one of the above files.  If "fmt" provides a
C/C++:   separate development package or SDK, be sure it has been installed.
C/C++: CMake Warning at fcitx5/CMakeLists.txt:27 (find_package):
C/C++:   By not providing "FindLibIntl.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "LibIntl", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "LibIntl" with any
C/C++:   of the following names:
C/C++:     LibIntlConfig.cmake
C/C++:     libintl-config.cmake
C/C++:   Add the installation prefix of "LibIntl" to CMAKE_PREFIX_PATH or set
C/C++:   "LibIntl_DIR" to a directory containing one of the above files.  If
C/C++:   "LibIntl" provides a separate development package or SDK, be sure it has
C/C++:   been installed.
C/C++: CMake Warning at fcitx5/CMakeLists.txt:31 (find_package):
C/C++:   By not providing "Findlibuv.cmake" in CMAKE_MODULE_PATH this project has
C/C++:   asked CMake to find a package configuration file provided by "libuv", but
C/C++:   CMake did not find one.
C/C++:   Could not find a package configuration file provided by "libuv" with any of
C/C++:   the following names:
C/C++:     libuvConfig.cmake
C/C++:     libuv-config.cmake
C/C++:   Add the installation prefix of "libuv" to CMAKE_PREFIX_PATH or set
C/C++:   "libuv_DIR" to a directory containing one of the above files.  If "libuv"
C/C++:   provides a separate development package or SDK, be sure it has been
C/C++:   installed.
C/C++: CMake Error at fcitx5/CMakeLists.txt:34 (include):
C/C++:   include could not find requested file:
C/C++:     D:/code/fcitx5-android/lib/fcitx5/src/main/cpp/fcitx5/cmake/Fcitx5AndroidInstallDirs.cmake
C/C++: CMake Error at fcitx5/CMakeLists.txt:51 (add_subdirectory):
C/C++:   add_subdirectory given source "fcitx5" which is not an existing directory.
 

### 重现步骤 / Steps to Reproduce

after build run app

### 预期行为 / Expected Behavior

in log

### 系统版本 / OS Version

win10   Android Studio Jellyfish | 2023.3.1 Build #AI-233.14808.21.2331.11709847, built on April 13, 2024 Runtime version: 17.0.10+0--11572160 amd64 VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o. Windows 11.0 GC: G1 Young Generation, G1 Old Generation Memory: 2048M Cores: 12 Non-Bundled Plugins:   dev.polek.adbwifi (1.2.5)   cn.yiiguxing.plugin.translate (3.5.6)            

### 应用版本 / App Version

lastest

**Comment by rocka** [comment]
Please follow "How to set up development environment" section in README.md:
https://github.com/fcitx5-android/fcitx5-android#how-to-set-up-development-environment

Enable symlink support, fetch all submodules, regenerate symlinks to submodules, and install build dependencies with MSYS2. All those steps are necessary.
