### ISSUE TITLE
text to Unicode Encoded/Decoded

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [fcitx5-android/fcitx5-android#499]
### 摘要 / Summary

Encrypt or decrypt text
* [Unicode](https://dencode.com/en/string/unicode-escape) 
> Supports encryption and decryption of text in multiple languages
* [Morse Code](https://dencode.com/en/string/morse-code)
> Single language only Encryption or decryption
* [Base64](https://dencode.com/en/string/base64)
> Single language only Encryption or decryption
* [Hex](https://dencode.com/en/string/hex)
> Single language only Encryption or decryption

### 附加信息 / Additional Context

It's like Gboard's translation input box.

<img width="432" alt="Screenshot_20240510-122229" src="https://github.com/fcitx5-android/fcitx5-android/assets/169121286/6bdfd1cc-ad89-4480-91d3-f0202cc36260">

### 系统版本 / OS Version

GrapeneOS Android 14

### 应用版本 / App Version

0.0.9-0

**Comment by rocka** [comment]
You can longpress the comma key and swipe left to activate Unicode addon: it would display unicode for every character in your clipboard; and you can type `u+abcd` or `0xabcd` to input character from its unicode.

As for morse code, base64 and hex, consider writing a lua imeapi extension
