### ISSUE TITLE
rime plugin 支持删词

### ISSUE THREAD

**Issue by tyf2018** [fcitx5-android/fcitx5-android#501]
### 摘要 / Summary

长按候选词的删词功能，不生效

### 重现步骤 / Steps to Reproduce

长按候选词，无法删词，松开手指后反而会继续上屏

### 预期行为 / Expected Behavior

长按候选词，忘掉或删掉候选词

### 系统版本 / OS Version

HarmonyOS 4.0

### 应用版本 / App Version

android-0.0.9-0-g8dc51356-arm64-v8a

### 插件版本 / Plugins Version

android.plugin.rime-0.0.9-0-g8dc51356-arm64-v8a

**Comment by rocka** [comment]
rime 插件目前不支持忘记词汇，只有自带的拼音/双拼和码表输入法才支持

**Comment by rocka** [comment]
- #517 

- https://github.com/fcitx/fcitx5-rime/pull/108

- https://github.com/fcitx5-android/fcitx5-android/commit/7ded3e7f237a638500a53bd4321665c4e3fe0d14

- https://github.com/rime/librime/issues/899
