### ISSUE TITLE
拼音输入的分词支持

### ISSUE THREAD

**Issue by Hentioe** [fcitx5-android/fcitx5-android#502]
### 摘要 / Summary

例如，打「饥饿」二字，默认是 jie（皆）的拼音，而不是 ji'e。

![Screenshot_2024-05-14-20-06-44-26_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/fcitx5-android/fcitx5-android/assets/13946976/0d3e11a2-86e1-4311-97ee-a648bf47c973)

参考 Gboard 在输入拼音时，大小写键会变成分词键，就可以打出 ji'e 的拼音了：

![Screenshot_2024-05-14-20-09-40-75_9d26c6446fd7bb8e41d99b6262b17def](https://github.com/fcitx5-android/fcitx5-android/assets/13946976/bee0463d-7718-478d-943a-229310c32354)

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9

**Comment by CoelacanthusHex** [comment]
> @CoelacanthusHex 原来如此。有点误导性，我一直以为那是一个会被打出来的符号。

这个用法是从桌面上的 Fcitx5 继承过来的，沿袭物理键盘上的习惯用法。
