### ISSUE TITLE
输入英文有时不方便选词

### ISSUE THREAD

**Issue by Junzz0** [fcitx5-android/fcitx5-android#503]
### 摘要 / Summary

当我输入 Flatpak 时，没出现在候选列表中，点击上面那个 Flatpak 会隐藏输入法；

但偶然发现可以通过空格选词来解决这个问题；

不知是不是原本就是这样设计的呢？

### 重现步骤 / Steps to Reproduce

输入 Flatpak。

### 预期行为 / Expected Behavior

候选列表中出现 Flatpak。

### 截图 / Screenshot

![1](https://github.com/fcitx5-android/fcitx5-android/assets/24819084/81749dbd-916b-469c-a2e6-8994d24f288c)

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
这个情况，应该是从旧版本升级上来的吧，建议在输入法设置 - 全局选项中，启用“在程序中显示预编辑文本”，让英文输入法直接在输入框中显示 composing text。另外目前英文输入法是不存在“空格选词”这个功能的，输入空格只是把 composing text 原样提交到输入框中，然后再加上一个空格。
