### ISSUE TITLE
希望支持9键或者18键等

### ISSUE THREAD

**Issue by qiangu2020** [fcitx5-android/fcitx5-android#506]
### 摘要 / Summary

希望能支持9键、14、16或者18键，，因为实际体验过，26键对于手机来说太容易误触，而且对单手不友好，实际是难以使用的

### 系统版本 / OS Version

安卓

### 应用版本 / App Version

最新

### 插件版本 / Plugins Version

rime

**Comment by rocka** [comment]
#377
