### ISSUE TITLE
开启键盘字母保持大写后英文键盘保持小写

### ISSUE THREAD

**Issue by An-gao** [fcitx5-android/fcitx5-android#507]
### 摘要 / Summary

开启键盘字母保持大写后英文键盘也会变为大写，
使用英文输入的时候这并不符合直觉，能不能改成仅在使用中文键盘键盘字母保持大写

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

.

**Comment by rocka** [comment]
“键盘字母保持大写”就是一个妥协的功能，应该等到 #377 一起实现。
