### ISSUE TITLE
对非定码长的方案自动上屏优化。

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#508]
### 摘要 / Summary

我使用是中码五笔方案，这个方案单字码长与词组码并不定长。也就是与王码五笔的最长4码定长不同。在开启方案设置中的`自动选择候选词`将`没有匹配时自动选择`也开启后。自动选择的总不是全码的词，而是当前分段匹配到的词+新入输的字符，而不是像Rime中自动选择的全码词。

### 替代方案 / Alternative Solution

挂在内置Rime插件中可以上正常选择上屏完整匹配的词

### 附加信息 / Additional Context

![Screenshot_20240518_142019_Fcitx5 for Android](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/c2f08639-15a3-4f6b-a03c-3cca26833cfb)
![Screenshot_20240518_142031_Fcitx5 for Android](https://github.com/fcitx5-android/fcitx5-android/assets/43703941/920e191a-3022-4c70-b119-3bcca431eb36)

### 系统版本 / OS Version

Android13操作系统

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by rocka** [comment]
请整理一下你的具体需求，你想输入什么，预期达到什么效果，现在能实现什么效果，然后去 https://github.com/fcitx/fcitx5-chinese-addons 提一个正经的 feature request
