### ISSUE TITLE
rime 版本需要升级

### ISSUE THREAD

**Issue by dongfengweixiao** [fcitx5-android/fcitx5-android#509]
### 摘要 / Summary

https://github.com/iDvel/rime-ice/issues/836
https://github.com/fcitx5-android/fcitx5-android/discussions/491

参考之前的讨论，在 0.0.9 版本中使用的 librime 1.11 对 translator/enable_correction 的支持有问题，需要更新 rime 版本解决。

### 重现步骤 / Steps to Reproduce

None

### 预期行为 / Expected Behavior

None

### 系统版本 / OS Version

None

### 应用版本 / App Version

None

**Comment by rocka** [comment]
#483
