### ISSUE TITLE
Add Japanese Handwriting

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [fcitx5-android/fcitx5-android#511]
### 摘要 / Summary

Request support for Japanese Handwriting input

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-0

**Comment by oldherl** [comment]
Do you know any existing free-software Japanese handwriting engine that could possibly integrated into?

**Comment by Zig-Rust-Odin** [comment]
> Do you know any existing free-software Japanese handwriting engine that could possibly integrated into?

https://kiang.org/jordan/software/hanzilookup/
https://github.com/tegaki/tegaki
https://github.com/gugray/HanziLookupJS
https://gitee.com/hebinq/shuoxie
https://github.com/quen/kanjirecog/tree/android
https://github.com/Saren-Arterius/google-chinese-handwriting-ime
https://popolon.org/gblog3/?p=447&lang=en

**Comment by rocka** [comment]
#399
