### ISSUE TITLE
RIME 插件：新增不了速成

### ISSUE THREAD

**Issue by Kaillis** [fcitx5-android/fcitx5-android#512]
### 摘要 / Summary

導入 RIME 版的速成輸入法失敗

### 重现步骤 / Steps to Reproduce

測試了 RIME 版的 [速成](https://github.com/rime/rime-quick) 和 [倉頡](https://github.com/rime/rime-cangjie) 這種只有 YAML 碼表格式的輸入法都不成功，但是 [薄荷输入法](https://github.com/Mintimate/oh-my-rime) 這種本身包含很多檔案的就有導入成功，好像是部署沒辦法成功創建 BIN 檔的原因

### 预期行为 / Expected Behavior

嘗試多次部署都沒辦法成功新增速成輸入法

### 系统版本 / OS Version

Android 13

### 应用版本 / App Version

0.0.9 和 0.0.8 都一樣

### 插件版本 / Plugins Version

0.0.9 和 0.0.8 都一樣

**Comment by rocka** [comment]
连点日志都没有，让别人怎么帮你呢。

**Comment by Kaillis** [comment]
非常抱歉，現補上日誌，以下是我重新安裝 0.0.9 版本再重新部署失敗的日誌，請幫忙看看，謝謝

[org.fcitx.fcitx5.android-2024-05-26T11_07_45Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/15447189/org.fcitx.fcitx5.android-2024-05-26T11_07_45Z.txt)

**Comment by rocka** [comment]
这日志里跟 rime 有关的只有一句话

```
I/fcitx5  (23605): addonmanager.cpp:193] Loaded addon rime
```

没用任何有效信息

**Comment by Kaillis** [comment]
我改成詳細的了，請幫忙再看看，謝謝。

我發現日誌裡沒有提到任何關於速成輸入法（quick）相關的資訊，會不會是沒有識別到我導入的那兩個檔案（quick5.dict.yaml & quick5.schema.yaml），所以才沒有部署成功呢？

[org.fcitx.fcitx5.android-2024-05-26T12_21_20Z.txt](https://github.com/fcitx5-android/fcitx5-android/files/15447447/org.fcitx.fcitx5.android-2024-05-26T12_21_20Z.txt)

**Comment by mokapsing** [comment]
要自己编辑default.custom.yaml，添加速成輸入法

![image](https://github.com/fcitx5-android/fcitx5-android/assets/39441028/f5d1c9e4-a24d-4d46-a6a8-2f819c9a7362)

**Comment by Kaillis** [comment]
> 要自己编辑default.custom.yaml，添加速成輸入法
> 
> ![image](https://private-user-images.githubusercontent.com/39441028/333928348-f5d1c9e4-a24d-4d46-a6a8-2f819c9a7362.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTAyNzIsIm5iZiI6MTcxNjgwOTk3MiwicGF0aCI6Ii8zOTQ0MTAyOC8zMzM5MjgzNDgtZjVkMWM5ZTQtYTI0ZC00ZDQ2LWE2YTgtMmY4MTljOWE3MzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDExMzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MDI2YTA2MDcxYTEzMGI1NzdjYzQ4OTE5MWQ3ODBjMTI2YmMzYjc3MzI0YWUxNTg0OWVmYjQ1NDQwMGMxMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NiJJw-5US6M7H5_TMMYZdZ1HiR4P4BgucHD7Se0B7-s)

成功了，非常感謝 😊
