### ISSUE TITLE
请问输入字母的过程中可以手动移光标修正拼音吗？

### ISSUE THREAD

**Issue by harry10086** [fcitx5-android/fcitx5-android#513]
### 摘要 / Summary

如题。
试了很多选项，也没试出该功能，如果不能在输入过程中修正拼音的话，那就得删除一部分再重新输入字母，比较浪费时间，不是很方便，其他输入法好像都有这个功能。
如有，希望能教我一下，在哪里实现？
谢谢！

### 系统版本 / OS Version

Android14

### 应用版本 / App Version

0.0.9

**Comment by wengxt** [comment]
@harry10086 滑动空格

**Comment by harry10086** [comment]
> @harry10086 滑动空格

刚刚我也发现了，试了半天。
🙏！
