### ISSUE TITLE
支持“他”“她”“它”的替换

### ISSUE THREAD

**Issue by wanzh5** [fcitx5-android/fcitx5-android#518]
### 摘要 / Summary

例如，“他说”“她说”“它说”在词库中是三个词，词频不一样。或者是一些比较冷门的词，输入法需要分别记住包含三种“ta”的版本。可以支持直接在含有“ta”的词后面附上另外两种“ta”的版本，类似于emoji显示在词语后面的方式。

### 系统版本 / OS Version

安卓10

### 应用版本 / App Version

0.0.9-4-gfaf44b61

**Comment by oldherl** [comment]
反对。因为很多词汇不能如此替换。
比如：其他：其她？他信（人名）？利他主义？

**Comment by eagleoflqj** [comment]
它说 和 他说 本来频率不一样也是正常的，因为动物一般不说话

**Comment by wengxt** [comment]
不是一种需要特别支持的功能，如果你输入长句的话，nbest已经很有可能进行了类似的预测

例如
![Screenshot_20240602-085944_Telegram~2](https://github.com/fcitx5-android/fcitx5-android/assets/259684/34063df8-bec2-4deb-bc3a-3682ae81baa9)
