### ISSUE TITLE
付费求助功能修改

### ISSUE THREAD

**Issue by lcm1475** [fcitx5-android/fcitx5-android#522]
### 摘要 / Summary

不好意思各位 这个帖子确实不太合适放在这里
但是实在是找不到人了， 想定制化这个键盘 ，付费修改 ，能做的可以回复一下

### 系统版本 / OS Version

1

### 应用版本 / App Version

1

### 插件版本 / Plugins Version

1

**Comment by oldherl** [comment]
温馨提醒：修改的本项目须遵守 LGPL 协议

**Comment by rocka** [comment]
你可以具体说一下想实现什么功能（~~以及愿意出多少钱~~）

**Comment by lcm1475** [comment]
就把这个项目集成到我目前的项目中 几乎没什么改动 预算3k

**Comment by oldherl** [comment]
你的什么项目？你打算遵守 LGPL 吗？

**Comment by lcm1475** [comment]
是一个聊天的项目
肯定要遵守LGPL

**Comment by lcm1475** [comment]
上架应用商店的正经项目

**Comment by lcm1475** [comment]
> 你可以具体说一下想实现什么功能（~以及愿意出多少钱~）

给你发过邮件 你没回
大佬帮帮忙

**Comment by LatticeLadder** [comment]
@lcm1475
