### ISSUE TITLE
建议将中文输入面板锁定为大写，而英文跟随输入状态切换

### ISSUE THREAD

**Issue by amzxyz** [fcitx5-android/fcitx5-android#523]
### 摘要 / Summary

目前的全局大写开关会导致英文输入时极其不舒服，而在中文输入时，大写的面板有更大的视觉识别度，因此，建议将中文输入面板锁定为大写，而英文跟随输入状态切换。中文输入时最好除了字母大写提升视觉范围外，还应该对皮肤改进，明确和增大可点击的边际，从而让输入更加放松。
![微信图片_20240609083451](https://github.com/fcitx5-android/fcitx5-android/assets/129564993/2bf23647-b6bb-4f89-944f-45e81ff9849c)

### 系统版本 / OS Version

14

### 应用版本 / App Version

0.09

### 插件版本 / Plugins Version

rime

**Comment by oldherl** [comment]
Duplicate of #507
