### ISSUE TITLE
在小窗聊天时长按“L”键崩溃

### ISSUE THREAD

**Issue by QianJiu233** [fcitx5-android/fcitx5-android#525]
### 摘要 / Summary

横屏在小窗聊天时长按“L”键崩溃

### 重现步骤 / Steps to Reproduce

1 横屏状态下打开小窗某个app
2 点击聊天栏
3 长按“L”键

### 预期行为 / Expected Behavior

崩溃

### 日志 / Log

[org.fcitx.fcitx5.android-2024-06-09T18_23_00Z.txt](https://github.com/user-attachments/files/15759190/org.fcitx.fcitx5.android-2024-06-09T18_23_00Z.txt)

### 系统版本 / OS Version

鸿蒙2.0/Android10

### 应用版本 / App Version

0.09-12-g1865b15f-release

**Comment by rocka** [comment]
和 #252 有点类似

**Comment by rocka** [comment]
should be fixed by d34dc17
