### ISSUE TITLE
使用中州韵rime输入时只能用空格键移动光标修正拼音输入

### ISSUE THREAD

**Issue by harry10086** [fcitx5-android/fcitx5-android#526]
### 摘要 / Summary

之前没有找到方法怎么移动光标，后来发现使用小企鹅拼音输入时，可以通过空格和手指点击两种方法。
但中州韵rime只能通过空格键移动光标，手动点击无效。
请问是功能缺失还是我使用方法问题？
谢谢！

### 重现步骤 / Steps to Reproduce

1.启用rime
2.设置-高级-忽略系统光标位置，关闭
3.输入法中州韵设置，预编辑-编辑中文本
此时只能通过空格键移动光标

如果启用小企鹅拼音时：
1.设置-高级-忽略系统光标位置，关闭
2.拼音输入法设置-预编辑模式-拼音串
可以空格键移动，也可以手动点击

### 预期行为 / Expected Behavior

因为空格键移动光标非常不方便，不仅难控制一两次移动到想要的位置，还有空格可能用来切换输入法，还有在滑动空格键时可能和系统的屏幕底部控制重合，光标没移动，整个屏幕页面切换了。

### 系统版本 / OS Version

Android14

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
直接原因： https://github.com/fcitx/fcitx5-rime 没有实现 [invokeAction](https://github.com/fcitx/fcitx5/blob/120a0ee9b128d17089a2d115730a1e28fd91812b/src/lib/fcitx/inputmethodengine.h#L197)

根本原因： librime 没有提供“设置经过输入法处理后的光标位置”的 API 。[set_caret_pos](https://github.com/rime/librime/blob/a735e42cf9d62d89301bc8a2f7c8d96ebed3d4f6/src/rime_api.h#L438) 仅能设置光标相对于原始用户输入的位置，而不能处理拼音分节，或者手动选字后使一部分拼音变成汉字的情况。

**Comment by harry10086** [comment]
> 直接原因： https://github.com/fcitx/fcitx5-rime 没有实现 [invokeAction](https://github.com/fcitx/fcitx5/blob/120a0ee9b128d17089a2d115730a1e28fd91812b/src/lib/fcitx/inputmethodengine.h#L197)
> 
> 根本原因： librime 没有提供“设置经过输入法处理后的光标位置”的 API 。[set_caret_pos](https://github.com/rime/librime/blob/a735e42cf9d62d89301bc8a2f7c8d96ebed3d4f6/src/rime_api.h#L438) 仅能设置光标相对于原始用户输入的位置，而不能处理拼音分节，或者手动选字后使一部分拼音变成汉字的情况。

感谢回复。希望能够早日实现，现在空格键移动只能说凑合能用。

**Comment by rocka** [comment]
如果你真的很需要这个功能，建议去 https://github.com/rime/librime 提一个 feature request 。这边其实什么都做不了。
