### ISSUE TITLE
划動輸入標點及數字，失誤率高

### ISSUE THREAD

**Issue by jared-chen** [fcitx5-android/fcitx5-android#529]
### 摘要 / Summary

建議參考 juloo.keyboard2 的 source code。

### 重现步骤 / Steps to Reproduce

划動輸入標點及數字

### 预期行为 / Expected Behavior

順利輸入標點及數字

### 系统版本 / OS Version

14

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
我觉得成功率挺高的，基本不会失误。方便发个录屏看看吗？

**Comment by rocka** [comment]
无回应故关闭。
