### ISSUE TITLE
標點設定基點

### ISSUE THREAD

**Issue by jared-chen** [fcitx5-android/fcitx5-android#530]
### 摘要 / Summary

以按鍵上的英文字母為標點設定的基點，而非對應英文標點。

### 系统版本 / OS Version

14

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
目前仅支持 https://github.com/fcitx/fcitx5-chinese-addons 中 [punctuation](https://github.com/fcitx/fcitx5-chinese-addons/tree/master/modules/punctuation) 模块的标点映射，其它输入法如 rime 等不支持。

本质上还是需要 #377
