### ISSUE TITLE
重新导入码表无法更新码表

### ISSUE THREAD

**Issue by yueduz** [fcitx5-android/fcitx5-android#533]
### 摘要 / Summary

码表输入法：删除码表输入法，再导入同名码表输入法，使用的还是删除前的码表。需要清除软件存储和缓存，然后再导入码表才能更新码表。

### 重现步骤 / Steps to Reproduce

  1. 配置附加组件
  2. 码表
  3. 管理码表输入法
  4. +号
  5. 从单独文件导入
  6. 输入法配置文件格式为 .conf ,码表词典为 .txt

### 预期行为 / Expected Behavior

使用新的码表

### 系统版本 / OS Version

android 14

### 应用版本 / App Version

0.0.7-0-gac5720a1-release

**Comment by LatticeLadder** [comment]
@yueduz 工具栏里面的三点菜单，“重新配置”点了吗

**Comment by rocka** [comment]
请更新到 GitHub Release 中的最新版本
