### ISSUE TITLE
Anthy: Add Space type "Half"

### ISSUE THREAD

**Issue by RAVENz46** [fcitx5-android/fcitx5-android#534]
### 摘要 / Summary

Currently, Space type option in Anthy has "Follow mode" and "Wide", but I need Half option.

### 系统版本 / OS Version

11

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
Maybe it can be done in https://github.com/fcitx/fcitx5-anthy

https://github.com/fcitx/fcitx5-anthy/blob/021e6355eadfe8fec9f3902da92401d7a8bc23a6/src/state.cpp#L603-L613

**Comment by RAVENz46** [comment]
Oh, sorry about that.
I submit issue upstream instead.
Feel free to close it.

**Comment by rocka** [comment]
Moved to https://github.com/fcitx/fcitx5-anthy/issues/14
