### ISSUE TITLE
使用rime，同步之后就记不住自造词了

### ISSUE THREAD

**Issue by CussiusKon** [fcitx5-android/fcitx5-android#535]
### 摘要 / Summary

用的rime插件，使用的薄荷拼音的配置，发现同步前可以记住自造词，同步之后就记不住了，打过的词怎么打都出不来

### 重现步骤 / Steps to Reproduce

安装应用，安装rime插件，导入薄荷配置，部署，选择薄荷全拼，此时拼写词语，可以记住。 
之后同步两次，再拼写新的词语，选择，再拼记不住

### 预期行为 / Expected Behavior

正确记录拼过的词

### 系统版本 / OS Version

13

### 应用版本 / App Version

0.0.9-0-g8dc51356-release

### 插件版本 / Plugins Version

同上

**Comment by CussiusKon** [comment]
不确定是app问题还是rime或者方案配置有问题

**Comment by rocka** [comment]
未能复现。有没有更改其它配置，比如 rime 的 sync_dir

**Comment by CussiusKon** [comment]
> 未能复现。有没有更改其它配置，比如 rime 的 sync_dir
> 
> ---
> 
> 不要把这个目录改到外面，输入法没有存储权限，改了也没用，反而会导致同步失败

没有配置syncdir那项，好奇怪哦，难受

**Comment by CussiusKon** [comment]
我是多台设备同步,好像只要同步某个设备的就出问题,哎,清除数据重新配置了一下,不同步那个设备的了,没问题了,先这样吧
谢谢
