### ISSUE TITLE
能否增加新的开关选项以开启或关闭emoji的输入？

### ISSUE THREAD

**Issue by warglaive6046** [fcitx5-android/fcitx5-android#536]
### 摘要 / Summary

对于一个平时不使用emoji表情的人来说，备选栏里的emoji数量太多了，影响到了正常的输入

### 系统版本 / OS Version

android14

### 应用版本 / App Version

0.0.9-0-g8dc51356

**Comment by rocka** [comment]
是否在使用内置的“拼音/双拼”输入法？如果是，请在“拼音/双拼”设置中关闭“启用符号”。

**Comment by warglaive6046** [comment]
居然这个地方还可以设置，是我没找到的问题，感谢您的回复与贡献

> 是否在使用内置的“拼音/双拼”输入法？如果是，请在“拼音/双拼”设置中关闭“启用符号”。
