### ISSUE TITLE
输入法插件：重启后插件会消失

### ISSUE THREAD

**Issue by mrliu714** [fcitx5-android/fcitx5-android#537]
### 摘要 / Summary

设备重启后添加好的插件输入法会消失，但是点击插件发现所有插件都是已加载的，我在两台设备上使用该输入法，只有其中一台Android9设备出现这样的问题，应用权限已检查，都已开启。

### 重现步骤 / Steps to Reproduce

安装插件
输入法设置点击输入法，添加输入法
使用无异常
重启系统
发现输入法消失

### 预期行为 / Expected Behavior

完成步骤后插件列表插件正常加载。

### 系统版本 / OS Version

Android9.0

### 应用版本 / App Version

0.0.9-0-g8dc51356

### 插件版本 / Plugins Version

0.0.9-0-g8dc51356

**Comment by rocka** [comment]
这两台设备都是应该至少有一台不是原生 Android 吧，是哪个厂商的什么魔改 OS 吗？

类似问题： #410

**Comment by mrliu714** [comment]
> 这两台设备都是应该至少有一台不是原生 Android 吧，是哪个厂商的什么魔改 OS 吗？
> 
> 类似问题： #410

出问题的那台Android9设备是一部使用LineageOS16的平板，没问题的是一部MIUI13、Android12的手机。
不过那台平板我使用了thanox用作后台管理以及权限管理，不知道有没有关系。
