### ISSUE TITLE
拼音导入 libime 文本格式词库失败

### ISSUE THREAD

**Issue by ivysrono** [fcitx5-android/fcitx5-android#538]
### 摘要 / Summary

文档来自：https://fcitx5-android.github.io/faq/#_9
测试了 `.dict` 格式是成功的

### 重现步骤 / Steps to Reproduce

导入 [rime-essay-simp/essay-zh-hans.txt](https://github.com/rime/rime-essay-simp/blob/master/essay-zh-hans.txt)

### 预期行为 / Expected Behavior

预期应该生成一个相当大的 .dict 文件

### 日志 / Log

但事实上生成的 `essay-zh-hans.dict` 体积只有 339b ，显然导入失败，同时UI上却显示导入成功，迷惑性很强。

### 系统版本 / OS Version

Android14

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
![image](https://github.com/fcitx5-android/fcitx5-android/assets/13914967/f9a5bb24-3618-4979-803a-5d54f28f7eba)

虽然 libime 支持导入 txt 格式的词库，但并不是从哪里随便拉来一个 txt 都能导入的，要按照一定的格式。参加文档： https://fcitx5-android.github.io/faq/#_10

libime 文本格式，一个 .txt 文件，其中单词、全拼和权重按照

```
拼音 pin'yin 0
词条 全拼  权重
```

排成三列

**Comment by rocka** [comment]
那你打算怎么处理多音字？排列组合枚举所有可能的读音吗？同音的词组怎么排序？

**Comment by jujubeja** [comment]
我使用 深蓝词库转换 导入 fcitx5-android 词库也失败了。就特殊符号原因 你很难处理几百万行的.txt。 如果你删除词库符号也失去了它的特性 如 颜文字  文字加符号

**Comment by CoelacanthusHex** [comment]
> 我使用 深蓝词库转换 导入 fcitx5-android 词库也失败了。就特殊符号原因 你很难处理几百万行的.txt。 如果你删除词库符号也失去了它的特性 如 颜文字 文字加符号

如果这里有某种自动化提供某个含有特殊符号的词的编码的方式，那完全可以在转换词库的时候自动加上编码，不需要 fcitx5 做任何变动；如果不存在这种算法，那么 fcitx5 也什么都做不了，一个没有对应编码的词即使被加到词库里也是无意义的，因为根本无法输入。
