### ISSUE TITLE
切换输入法时,rime addon 会重新部署

### ISSUE THREAD

**Issue by LastFlydragon** [fcitx5-android/fcitx5-android#546]
### 摘要 / Summary

我英语用gboard,中文用fcitx安卓版和rime插件来实现双拼音形输入.
切换到英语然后切换回fcitx时,中文输入会重新部署,所以每次要延迟10秒以上.
不知道是fcitx还是rime的原因,所以先发到这里看看.

### 重现步骤 / Steps to Reproduce

fcitx安卓版和rime插件,rime里部署了墨奇音形
切换到其它输入法比如gboard,然后切换回fcitx时,中文输入会重新部署,所以每次要延迟10秒以上.

### 预期行为 / Expected Behavior

切换到其它输入法比如gboard,然后切换回fcitx时,中文输入能不能不要重新部署?

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by rocka** [comment]
实际上和 #531 是同一个问题
