### ISSUE TITLE
快速划掉剪切板内容后撤销功能失效

### ISSUE THREAD

**Issue by Zpcola** [fcitx5-android/fcitx5-android#552]
### 摘要 / Summary

短时间内多次划掉剪切板内容后点击撤销按钮无作用

### 重现步骤 / Steps to Reproduce

1.打开剪切板
2.一次性划掉两条剪切板历史记录
3.点击撤销

### 预期行为 / Expected Behavior

是否应该调整为点击撤销后回退5秒删除的所有内容?

### 系统版本 / OS Version

MIUI14 A13

### 应用版本 / App Version

0.0.9-28-g25bdee19

**Comment by rocka** [comment]
should be fixed by [`20af29`](https://github.com/fcitx5-android/fcitx5-android/commit/a20af29d44b9cb01f209e69f2adeda409a039578)
