### ISSUE TITLE
请求增加悬浮键盘

### ISSUE THREAD

**Issue by Jastmaskerrr** [fcitx5-android/fcitx5-android#556]
### 摘要 / Summary

平板上更适合使用悬浮键盘
![Screenshot_20240804_140208_Simplenote](https://github.com/user-attachments/assets/07c96f94-d642-4152-96ee-c25837983e8c)

### 系统版本 / OS Version

Android14

### 应用版本 / App Version

0.0.9-0-g8dc51356-release

**Comment by oldherl** [comment]
Duplicate of #106

**Comment by rocka** [comment]
悬浮键盘是 #115
