### ISSUE TITLE
rime自动同步？

### ISSUE THREAD

**Issue by keeper402** [fcitx5-android/fcitx5-android#558]
我在使用rime方案。
目前私人网盘+folderSync可以完全胜任文件同步。然而只能达成半自动同步。毕竟文件同步完还要在输入法里点同步。
所以只需要有个自动执行输入法的同步就行了。
Windows上是通过计划任务执行同步命令完成sync文件夹的更新同步。
而安卓无法实现这个功能，app内增加一个等效于定时自动点击同步的功能就可以完成双端无感同步了。
不知道同步期间输入是不是个问题。

_Originally posted by @keeper402 in https://github.com/fcitx5-android/fcitx5-android/issues/545#issuecomment-2274117456_

**Comment by wengxt** [comment]
@keeper402 fcitx的保存每半个小时运行一次会触发rime sync

**Comment by keeper402** [comment]
就是说rime自动同步已经是实现的了？
还有同步的内容是固定的还是可配的，我发现sync目录下的rime_ice.schema.yaml不会同步。
试了好几次后我手动移动文件覆盖才解决。
这个是rime的问题吗。

**Comment by dreamflandre** [comment]
@keeper402 f5a只负责触发rime插件同步，同步的细节是rime插件自己实现的

**Comment by keeper402** [comment]
@dreamflandre 非常感谢！
