### ISSUE TITLE
求求啦，真的很需要9键布局呀

### ISSUE THREAD

**Issue by xcc3306** [fcitx5-android/fcitx5-android#559]
### 摘要 / Summary

输入法9键布局的用户还是很多的，我本人也是习惯使用9键的。
自从用上小企鹅输入法后，我就喜欢上了这个输入法，但是用了20多年的9键布局，现在在去适应26键，多少是有些难受的。
所以我很希望咱们小企鹅也可以出一个9键的布局，求求啦(≧口≦)

### 替代方案 / Alternative Solution

在我了解的所有输入法中，我个人认为，微信输入法的界面布局是最好看，最简洁大方的，我们可以借鉴一下它的样式。

### 附加信息 / Additional Context

![微信图片编辑_20240808170513](https://github.com/user-attachments/assets/10689556-729b-4ebf-9144-59e1be5ab30c)
![微信图片编辑_20240808170542](https://github.com/user-attachments/assets/b4557024-67fb-43e6-abdc-840733a6ca98)

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

中州韵 0.0.9

**Comment by oldherl** [comment]
Duplicate of #109

**Comment by mokurin000** [comment]
@LatticeLadder 还是不够真心，真心应该拿出打赏价格

**Comment by xcc3306** [comment]
@LatticeLadder 好吧，也是，毕竟是开源软件能做到这样已经是挺好的了

**Comment by danjian** [comment]
额。我也是受不了26.然后我实现了一个 基于29键改的。后端用的方案是雾凇拼音。

![Image](https://github.com/user-attachments/assets/384919b5-dd9d-484b-966a-eb2526ad2fe0)

**Comment by danjian** [comment]
就我自己使用体验看基本没太大问题了。可能还有一点就是左侧的候选一般会加上候选拼音选择。但是能力有限。先这么用着了打算。

**Comment by danjian** [comment]
就我自己使用体验看基本没太大问题了。可能还有一点就是左侧的候选一般会加上候选拼音选择。但是能力有限。先这么用着了打算。
