### ISSUE TITLE
在安卓版中使用 rime 插件怎么做简繁切换？

### ISSUE THREAD

**Issue by Ltjwork** [fcitx5-android/fcitx5-android#562]
### 摘要 / Summary

在安卓版中使用 rime 插件怎么做简繁切换？

### 系统版本 / OS Version

one plus 9t

### 应用版本 / App Version

0.9

**Comment by rocka** [comment]
点击虚拟键盘左上角 <kbd>></kbd> 按钮展开工具栏，再点击工具栏最右侧 <kbd>···</kbd> 按钮展开 Status Area，在其中选择 `汉字 -> 漢字`

**Comment by Ltjwork** [comment]
![Screenshot_2024-08-14-03-30-10-01_d365b52accad0f47adbc08c16219827d](https://github.com/user-attachments/assets/62c8144f-d8cb-46ab-a13c-27d0225c5e09)

就是因为没有才问的。。。在拼音下是有的，切换到 rime 就没了

**Comment by mokapsing** [comment]
> ![Screenshot_2024-08-14-03-30-10-01_d365b52accad0f47adbc08c16219827d](https://private-user-images.githubusercontent.com/751531/357547699-62c8144f-d8cb-46ab-a13c-27d0225c5e09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ0OTEsIm5iZiI6MTcyMzU5NDE5MSwicGF0aCI6Ii83NTE1MzEvMzU3NTQ3Njk5LTYyYzgxNDRmLWQ4Y2ItNDZhYi1hMTNjLTI3ZDAyMjVjNWUwOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTAwMmY2NDdmNDZiMzVlNzcwMzk4NWFhMzJiMjA4MjgwZjRjZTU3NmU2MTczMzU4Njk0ZTkwNzcwOTIyY2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7gEezswnISd7eRh3YSUEx8_7Tl6OEioJ9HwRASzDeFI)
> 
> 就是因为没有才问的。。。在拼音下是有的，切换到 rime 就没了

只能说这个是因为你的方案没有这部分配置导致的，在你的方案schema.yaml里面，需要有对应的switches

**Comment by Ltjwork** [comment]
> > ![Screenshot_2024-08-14-03-30-10-01_d365b52accad0f47adbc08c16219827d](https://private-user-images.githubusercontent.com/751531/357547699-62c8144f-d8cb-46ab-a13c-27d0225c5e09.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1OTQ0OTEsIm5iZiI6MTcyMzU5NDE5MSwicGF0aCI6Ii83NTE1MzEvMzU3NTQ3Njk5LTYyYzgxNDRmLWQ4Y2ItNDZhYi1hMTNjLTI3ZDAyMjVjNWUwOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNFQwMDA5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTAwMmY2NDdmNDZiMzVlNzcwMzk4NWFhMzJiMjA4MjgwZjRjZTU3NmU2MTczMzU4Njk0ZTkwNzcwOTIyY2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7gEezswnISd7eRh3YSUEx8_7Tl6OEioJ9HwRASzDeFI)
> > 就是因为没有才问的。。。在拼音下是有的，切换到 rime 就没了
> 
> 只能说这个是因为你的方案没有这部分配置导致的，在你的方案schema.yaml里面，需要有对应的switches

谢谢！
