### ISSUE TITLE
使用码表输入时左滑删除键清空候选会将编码上屏

### ISSUE THREAD

**Issue by Morgal106** [fcitx5-android/fcitx5-android#563]
### 摘要 / Summary

使用自带的五笔字形和自己导入的虎码都会遇到这种情况，拼音输入和rime正常

### 重现步骤 / Steps to Reproduce

1. 在输入法中启用五笔字形输入法
2. 打一些字
3. 左滑删除键清空候选，会看到编码上屏

### 预期行为 / Expected Behavior

清空候选同时清空编码，不会将编码上屏

### 系统版本 / OS Version

Android 14 / color os14

### 应用版本 / App Version

0.0.9-43

**Comment by rocka** [comment]
在五笔设置中关闭“取消激活输入法时提交输入缓冲区”
