### ISSUE TITLE
如何正常使用词语联想功能

### ISSUE THREAD

**Issue by puerjiang** [fcitx5-android/fcitx5-android#564]
### 摘要 / Summary

首先感谢作者的努力，目前最顺手的手机输入法。
目前使用最新的编译版，日常使用自带的五笔拼音编码表，设定里已开户“预测启用”，但联想出来的词完全驴头不对马嘴，比如我输入“早”，正常联想出来的应该类似“上，晨”这样的，而现在联想出来的是“的，是，了，中，被，已经。。。”，并且我测试连续输入多次“早”和“晨”，也不会出现在联想词里，求助如何解决这个问题，谢谢

### 系统版本 / OS Version

14

### 应用版本 / App Version

0.0.9-52-gc4a07bbb

**Comment by LatticeLadder** [comment]
@puerjiang 我发现能正常使用啊，“最新”可以联想到“的”、“优惠活动”、“发布”、“章节”、“排行榜”等。应该是你的输入字太少了，一个字不行的

**Comment by rocka** [comment]
目前的预测效果就是这样的，拼音可以预测词库里的词，但是码表不行，而且码表也不能单独设置预测候选的数量。

方便透露一下为什么用五笔还要开预测吗？一般码表输入法的用户的目标都是为了减少选词吧。

**Comment by puerjiang** [comment]
电脑上我也是使用五笔，但从不用联想的候选词。
手机上当时还是想减少输入，提高速度了。
