### ISSUE TITLE
咨询Gradle plugin的详细信息或源码地址

### ISSUE THREAD

**Issue by wangjun19951014** [fcitx5-android/fcitx5-android#566]
### 摘要 / Summary

plugins {
    id("org.fcitx.fcitx5.android.app-convention")
    id("org.fcitx.fcitx5.android.native-app-convention")
    id("org.fcitx.fcitx5.android.build-metadata")
    id("org.fcitx.fcitx5.android.data-descriptor")
    id("org.fcitx.fcitx5.android.fcitx-component")
}
在https://jitpack.io  https://dl.google.com/dl/android/maven2/  https://repo.maven.apache.org/maven2/ 中没有找到相关插件的信息，能否提供一下可以查看上述插件的信息的网址
        

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

无

### 插件版本 / Plugins Version

Gradle 8.5

**Comment by rocka** [comment]
在插件模板仓库里有 
https://github.com/fcitx5-android/plugin-scaffold/blob/d7d77ef0f57275081f8696964b44c6bfefcf2247/data/templates/settings.gradle.kts.mustache#L3

https://maven.libido.workers.dev/fcitx5-android/fcitx5-android/

实际上是 https://github.com/fcitx5-android/fcitx5-android/packages 的反代，因为读取 maven package 需要 token
