### ISSUE TITLE
形码方案触发`快速输入`后会显示`以：回车以：：`

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#568]
### 摘要 / Summary

请问可以去掉吗/关掉？应该不是设置的问题。
![Screenshot_20240817_234523_Via](https://github.com/user-attachments/assets/317261b7-9e5e-4746-8d81-0e1ca9a925d5)

### 系统版本 / OS Version

Android操作系统

### 应用版本 / App Version

最新版

**Comment by rocka** [comment]
明显就是设置问题啊，不要“快速输入的触发键” 设置成 <kbd>:</kbd> 就好了
