### ISSUE TITLE
请求恢复charset_filter插件

### ISSUE THREAD

**Issue by linzianabc** [fcitx5-android/fcitx5-android#577]
### 摘要 / Summary

现有的字符集过滤功能严重依赖lua。但是一来lua配置繁琐，二来容易导致性能下降，打字卡顿，影响效率。而Rime旧有的charset_filter插件，完全可以恢复，便利用户，何乐而不为呢？

### 系统版本 / OS Version

Manufacturer: Xiaomi OS Version: 4.19.113-perf-g591bf45845ee (V13.0.2.0.SLMCNXM)

### 应用版本 / App Version

Version Name: 0.0.9-64-gb381b414

**Comment by rocka** [comment]
虽然我看不懂，但你大概来错地方了

https://github.com/rime/librime/issues

**Comment by linzianabc** [comment]
> 虽然我看不懂，但你大概来错地方了
> 
> https://github.com/rime/librime/issues

没有走错，librime一直有这个插件。隔壁的同文也有这个功能。

**Comment by rocka** [comment]
我是没找到这个插件， librime 自己的 release ci 就只有 lua octagram predict 三个插件

https://github.com/rime/librime/blob/72564a763f1c897475667da5c81fa49986b1ca81/.github/workflows/release-ci.yml#L23

我们也是这三个

https://github.com/fcitx5-android/prebuilder/blob/f06763ae55435e0dc681a364cf964abf433e6ad9/src/Rules/LibRime.hs#L26-L28

**Comment by linzianabc** [comment]
> 我是没找到这个插件， librime 自己的 release ci 就只有 lua octagram predict 三个插件
> 
> https://github.com/rime/librime/blob/72564a763f1c897475667da5c81fa49986b1ca81/.github/workflows/release-ci.yml#L23
> 
> 我们也是这三个
> 
> https://github.com/fcitx5-android/prebuilder/blob/f06763ae55435e0dc681a364cf964abf433e6ad9/src/Rules/LibRime.hs#L26-L28
但是佛振说，一直都有：
https://github.com/rime/librime/blob/72564a763f1c897475667da5c81fa49986b1ca81/src/rime/gear/charset_filter.cc

**Comment by rocka** [comment]
https://github.com/rime/librime/blob/72564a763f1c897475667da5c81fa49986b1ca81/src/rime/gear/gears_module.cc#L82-L84

这是写在 librime 里面的 gears_module ，跟插件也没有关系啊？我们又不会去改动 librime 的代码，还能专门把这个 module 给你去掉吗？

**Comment by linzianabc** [comment]
> https://github.com/rime/librime/blob/72564a763f1c897475667da5c81fa49986b1ca81/src/rime/gear/gears_module.cc#L82-L84
> 
> 这是写在 librime 里面的 gears_module ，跟插件也没有关系啊？我们又不会去改动 librime 的代码，还能专门把这个 module 给你去掉吗？

好的，还是谢谢你。
