### ISSUE TITLE
部分应用不显示悬浮候选框

### ISSUE THREAD

**Issue by calico-cat-3333** [fcitx5-android/fcitx5-android#578]
### 摘要 / Summary

在使用最新的 CI 构建中，使用物理键盘输入时，部分应用无法显示悬浮候选框。
我目前发现的应用有：
Acode
闲鱼
Fennec F-droid（有时可以有时不行）

### 重现步骤 / Steps to Reproduce

连接物理键盘并在 设置-系统-语言和输入法-实体键盘 中关闭“使用屏幕键盘”
打开有问题的应用（例如 Acode）
开始打字
英文模式可以正常输入，但是按 ctrl-空格 切换到中文后，按键不会出现候选框，但是此时按空格或数字可以打出字来，看起来应该是候选框显示不出来。

### 预期行为 / Expected Behavior

正常显示候选框

### 日志 / Log

[org.fcitx.fcitx5.android-2024-08-30T07_51_27Z.txt](https://github.com/user-attachments/files/16813889/org.fcitx.fcitx5.android-2024-08-30T07_51_27Z.txt)

### 系统版本 / OS Version

Crdroid 9.10 (Android 13）

### 应用版本 / App Version

0.0.9-64-gb381b414-release

**Comment by rocka** [comment]
应用不报告光标位置，没办法显示候选框

**Comment by calico-cat-3333** [comment]
在应用不报告光标位置时，能否在固定位置（比如说屏幕左上角或者左下角）显示候选框？这样虽然效果不好但是至少能用。

**Comment by calico-cat-3333** [comment]
在最新 CI 构建（0.0.9-75-g9c4ad624-release）中，这些应用会在左下角固定位置显示候选框，已经能用了。感谢作者修复。
