### ISSUE TITLE
连接实体键盘之后虚拟键盘也能用

### ISSUE THREAD

**Issue by alan42521** [fcitx5-android/fcitx5-android#579]
### 摘要 / Summary

像是gboard或者swift它可以在物理键盘输入时自动隐藏屏幕键盘显示候选框，这样在接入物理键盘时屏幕键盘也是可用的

### 系统版本 / OS Version

Android11

### 应用版本 / App Version

0.0.9-64-gb381b414-release

**Comment by yizhimengxin2233** [comment]
是“连接实体键盘之后虚拟键盘也能用”吧 标题好像打错了

**Comment by alan42521** [comment]
> 是“连接实体键盘之后虚拟键盘也能用”吧 标题好像打错了

一样的，连接实体键盘后打开屏幕键盘选项虚拟键盘可用，实体键盘无候选框，关闭屏幕键盘后实体键盘可用，虚拟键盘不可用了。

**Comment by FEI352** [comment]
在andriod14上，会自带一个屏幕键盘是切换按钮。

**Comment by yizhimengxin2233** [comment]
> 在andriod14上，会自带一个屏幕键盘是切换按钮。

切换不能把屏幕键盘切出来吧？ 除非另外装一个输入法

**Comment by rocka** [comment]
系统设置或者输入法选择框里面自己开关虚拟键盘就行了

![Screenshot_1726567060](https://github.com/user-attachments/assets/0700166b-7879-4211-a9f7-e893802dd98f)

**Comment by rocka** [comment]
> 可是这样还是实现不了同时使用啊

虚拟键盘显示的时候，物理键盘也是可以按的，也就是说可以先按一下虚拟键盘，再按一下物理键盘。不知道你说的“同时”使用是不是指这个。

**Comment by alan42521** [comment]
不是的，是说屏幕键盘打开时物理键盘的候选框也可以使用，来避免使用蓝牙键盘的时候离开了键盘打不了字的问题

**Comment by alan42521** [comment]
当然主动切换也可以，但是还是想能不用主动切换让输入法自行判断
