### ISSUE TITLE
请求双拼功能支持纠错

### ISSUE THREAD

**Issue by Marukon** [fcitx5-android/fcitx5-android#582]
### 摘要 / Summary

现在，全拼功能已经支持基本纠错(0.09更新日志提到 basic error correction support for adjacent keys in the same row)，请求让这个功能也支持双拼。

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-64-gb381b414(72)

**Comment by rocka** [comment]
来这提吧 https://github.com/fcitx/fcitx5-chinese-addons/issues

这个功能也不是 Android 实现的

**Comment by eagleoflqj** [comment]
双拼纠错已进入 master

**Comment by Marukon** [comment]
> 双拼纠错已进入 master

感谢，已更新，非常好用
