### ISSUE TITLE
rime 插件目录删不掉了

### ISSUE THREAD

**Issue by JUST-INTJ** [fcitx5-android/fcitx5-android#583]
### 摘要 / Summary

rime目录，想要删除时里面有几个文件好像有特殊权限，权限不足导致无法删除/修改。使用电脑mtp连接也是一样。
希望能够授予用户写入权限、以便能够删除。

Uploading Screen_Recording_20240905_102324_MiXplorer_1.mp4…

### 重现步骤 / Steps to Reproduce

位于：/storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime

### 预期行为 / Expected Behavior

希望有删除权限

### 系统版本 / OS Version

android 13

### 应用版本 / App Version

0.0.9.64

### 插件版本 / Plugins Version

0.0.9.64

**Comment by JUST-INTJ** [comment]
https://github.com/user-attachments/assets/1d56fe6d-8518-4ac9-9799-1a5eb5e825b5

**Comment by JUST-INTJ** [comment]
手机没有root权限，估计只能用adb 来去删除了。

**Comment by JUST-INTJ** [comment]
adb 也删不掉

**Comment by rocka** [comment]
显然是 rime 自己的问题 ¯\_(ツ)_/¯

然后建议通过系统的 DocumentsUI 操作 DocumentsProvider 来删除文件，而不是用第三方文件管理器打开 data 目录。不过 Mixplorer 也可以用 DocumentsProvider ，侧边栏菜单 添加存储 第一个就是。

最后，你永远可以通过 导出数据 - 卸载应用 来删除所有数据，然后修改导出的 zip 并删掉不需要的文件，重新导入。

**Comment by JUST-INTJ** [comment]
导入错误了，MIXplorer DocumentsProvider看不到data目录，使用卸载安装导入数据出现了。报错
![Screenshot_20240905_210146_Fcitx5 for Android](https://github.com/user-attachments/assets/ba08db3b-93cf-4018-a379-8297d963b7e5)

**Comment by JUST-INTJ** [comment]
是这样的，清楚fcitx5 Android 应用数据后 导入数据 看到了文件恢复了修改权限。
