### ISSUE TITLE
请增加英文记忆功能

### ISSUE THREAD

**Issue by biange200** [fcitx5-android/fcitx5-android#588]
### 摘要 / Summary

请增加英文记忆功能和剪切板分词拆封功能

### 系统版本 / OS Version

iqoo neo9 pro  android14

### 应用版本 / App Version

fcitx5 0.9

**Comment by rocka** [comment]
duplicate of #262 #542

发 issue 前建议先搜索一下现有 issue

**Comment by biange200** [comment]
> duplicate of #262 #542
> 
> 发 issue 前建议先搜索一下现有 issue
安卓手机上能用？
