### ISSUE TITLE
加入码表输入法的数字键选重功能

### ISSUE THREAD

**Issue by LemonixElaina** [fcitx5-android/fcitx5-android#590]
### 摘要 / Summary

Fcitx5 中，选重只能通过点击候选项来实现，或者只能在设置中选择前三个候选的选重键。

但这对于多重的方案并不友好（如 092 五笔或九重魔鹤等方案），只能用 Fcitx-Rime 的方法来实现，可我并不是一个愿意研究 Rime 的人，所以这对我造成了困扰。

希望可采纳我的建议。

### 系统版本 / OS Version

HyperOS 1.0.8.0

### 应用版本 / App Version

0.0.9.0

**Comment by rocka** [comment]
现在键盘上并没有数字键，需要 #377

以后自然就有了，并不是需要特别支持的东西
