### ISSUE TITLE
"Enable key border" does not work in symbol ?123 tab

### ISSUE THREAD

**Issue by vietdht** [fcitx5-android/fcitx5-android#592]
### 摘要 / Summary

When I enable key border in Themes->Configure, it works only for the main keyboard, but not the symbol tab

### 重现步骤 / Steps to Reproduce

1. Open Themes -> Configure
2. Set "Enable key border"  = true
3. Back the keyboard
4. Press "?123"

### 预期行为 / Expected Behavior

Expects that "?123" keyboard layout also have key border same as main keyboard

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-0

**Comment by rocka** [comment]
#489

please upgrade to latest CI build: https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/
