### ISSUE TITLE
适配 "URI/URL" 及 "Email" 输入类型以快速输入常见域名后缀 / Support "Email" and "URI/URL" Input Types With Shortcut for Common TLDs

### ISSUE THREAD

**Issue by mgrddsj** [fcitx5-android/fcitx5-android#593]
### 摘要 / Summary

在输入框的输入类型为 Email 或 URI/URL 时，长按 26 键布局右下角的句号按钮时，弹出 ".com", ".org", ".net" 等常见域名后缀供用户快速输入。

---

When the input field has a type of email or URI/URL, the popup for long-pressing the period button on the lower-right corner should provide common TLDs like ".com", ".org", and ".net" for quick input.

### 替代方案 / Alternative Solution

在设计和实现 #377 时，可以将此功能加入考虑中。

---

This can be a feature to keep in mind when designing and implementing issue #377 

### 附加信息 / Additional Context

相关信息：
根据 Android 文档 (https://developer.android.com/reference/android/text/InputType)，需要实现该功能的输入类型应该是：
- `TYPE_TEXT_VARIATION_URI`
- `TYPE_TEXT_VARIATION_EMAIL_ADDRESS`
- `TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS`

---

参考截图：
以下是 GBoard 实现该功能的截图：
![Screenshot_20240925-113828](https://github.com/user-attachments/assets/fa1d0758-6c84-4674-9233-da82ba572a6a)
![Screenshot_20240925-114426](https://github.com/user-attachments/assets/af5bb919-3f84-473b-8c0b-8a0a4d02dd43)

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-0-g8dc51356

**Comment by rocka** [comment]
duplicate of #565
