### ISSUE TITLE
能否增加对物理键盘输入的模拟功能，实现类似trime的硬输入功能。

### ISSUE THREAD

**Issue by CamWam** [fcitx5-android/fcitx5-android#594]
### 摘要 / Summary

# 描述：
如 https://github.com/artisticat1/obsidian-latex-suite/issues/52 ，所示
当前插件能够快速识别并将输入内容转换为代码片段（snippets）。通常，这种功能只能通过物理键盘实现，而传统的输入法（如搜狗输入法、讯飞输入法、Gboard输入法和小企鹅输入法）无法实现这一点。

然而，Trime输入法可以通过模拟物理键盘输入来实现这一功能。

# 请求：

希望插件能够增加类似Trime输入法的功能，通过模拟物理键盘输入来实现快速转换内容为代码片段的功能。

# 参考：

类似功能的实现可以参考Trime输入法的工作方式。

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

0.0.7.0-gac5720a1-release

**Comment by rocka** [comment]
某个编辑器某个插件的 bug ，应该让那个插件自己去修，而不是到输入法这里来找 workaround

**Comment by rocka** [comment]
那个插件“需要使用physical keyboard识别“就是它的问题。如果需要在 Android 上使用，就需要遵守“安卓的输入机制”
