### ISSUE TITLE
建议把大写字母放在第一个候选词

### ISSUE THREAD

**Issue by choicky** [fcitx5-android/fcitx5-android#595]
### 摘要 / Summary

首先感谢大佬们的无私奉献与投入。

目前，在双音输入法下，如果输入大写的字母例如 `P` ，第一个候选词是汉字，第二个候选词才是 `P`。  我觉得该候选词的设置不够合理，如果用户输入大写字母的话，其本意很可能是想输入该大写字母。希望能做一些改进。 

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

fcitx-android-0.0.9

**Comment by rocka** [comment]
- https://github.com/fcitx/fcitx5-chinese-addons/issues/194
- https://github.com/fcitx/fcitx5-chinese-addons/pull/193
