### ISSUE TITLE
The "A" and "L" 's side area should be clickable.

### ISSUE THREAD

**Issue by jackyzy823** [fcitx5-android/fcitx5-android#599]
### 摘要 / Summary

I hope that 1) the area left of "A" 's border should also be able to trigger "A" . 2) the area left of "L" 's border should also be able to trigger "L"  which will be helpful for single hand input.

### 附加信息 / Additional Context

![fcitx_border](https://github.com/user-attachments/assets/9b909637-d2fb-4d5b-84c3-81f0db950a00)

Some other information: 
Gboard and Google Pinyin have already done this.

### 系统版本 / OS Version

14

### 应用版本 / App Version

0.0.9

**Comment by oldherl** [comment]
It would increase the rate of mistyping

**Comment by eagleoflqj** [comment]
The option `Expand keypress area to the edge` in keyboard setting is exactly what you want.

**Comment by jackyzy823** [comment]
Sorry, i didn't check settings carefully. :(

Thank you!
