### ISSUE TITLE
关于实体键盘悬浮候选框的宽度。

### ISSUE THREAD

**Issue by Hhsy083212** [fcitx5-android/fcitx5-android#600]
### 摘要 / Summary

最近看到F5A适配了实体键盘，真是喜出望外，特意体验了一番，完成度比想象的好很多，其中有个小细节，请求开发者大神改动一下，当使用实体键盘打字时，悬浮候选栏的宽度和高度会随着候选项变化，请问能否设定为固定宽度呢？因为长篇大论的打字，候选栏大小变来变去，会很晃眼睛，本人散光挺严重的，有点影响聚焦，建议设置为固定长宽比，比如我看到目前就有候选项数量设定，可以以这个为基准，或者可以长度固定，高度变化也行，这样不会晃来晃去，大概就是这样，恳请开发者考虑一下，再次感谢。

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

最新构建版本

**Comment by sbxlmdsl** [comment]
不仅仅是实体键盘需要悬浮窗，不用实体键盘时也是需要悬浮窗的，比如同文就是支持悬浮窗的，而且用的人很多，因为悬浮窗是支持自动换行进行多行显示的，因此建议支持类似同文的悬浮窗作为一个选项，不与实体键盘挂钩。

**Comment by rocka** [comment]
done in 5de607a
