### ISSUE TITLE
期望增加悬浮窗和横排与竖排功能

### ISSUE THREAD

**Issue by leisure365** [fcitx5-android/fcitx5-android#601]
### 摘要 / Summary

期望增加以下两个功能和功能开关：
        一直关注fcitx5安卓版，最近用上了修改键盘布局的最新构建版本，流畅度和功能都不错。听说键盘自定义键盘和增加更多主题配色设置已经在计划中，真的非常开心。但目前使用中，发现一些问题，期望能增加下述两个功能：
（1）增加悬浮窗及相关设置开关
        因通过中州韵插件实现rime方案在fcitx5安卓版上使用，方案中是多个字词作为一组出现，单字和两字词候选还能在候选栏一行显示，但在更多的字词（比如4字词组合）候选中会显示不全，必须通过倒三角点开才能查看到，但这样就牺牲了原方案的优势，且也有不少方案在rime上也是多选的。故期望能实现候选显示不全时，能通过类似悬浮窗自动换行等功能实现完整的候选；同时考虑到并不是所有人都需要或喜欢类似悬浮窗的功能，故期望同时增加一个设置开关。
（2）增加横排和竖排切换功能及相关设置
        在实际使用中，有时想使用竖排显示候选，但fcitx5安卓版目前还不可以设置，期望能够增加该功能及相关设置。除了个人喜好不同外，也期望能通过竖排设置后，能实现期望（1）中的完整显示候选词条。

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

最新构建版本

**Comment by Hhsy083212** [comment]
太棒了，太棒了，用了最新的构建版，设置选项里增加了一个单独的【悬浮候选项菜单】，目前还是英文的，不过已经可以设置横竖排显示了，改成了竖排显示，简直完美，而且这个输入法还可以设置【悬浮窗始终在光标最开始的地方】，不会随着编码一直往后移动，我这散光的近视眼真是哭死，已经无限接近PC上的输入体验了，就差【悬浮窗设置固定长或宽】和【迷你状态栏】了，除此之外别无所求。
![Screenshot_2024-11-08-01-43-40-037_com miui mediaviewer](https://github.com/user-attachments/assets/911cf676-ce35-4f94-9429-e82d49e05ead)
