### ISSUE TITLE
添加开关取消长按确定键进入表情界面

### ISSUE THREAD

**Issue by alan42521** [fcitx5-android/fcitx5-android#603]
### 摘要 / Summary

在微信、qq一些app里，长按确定键可以换行，但是小企鹅长按确定键会进入表情界面，希望可以添加开关取消

### 系统版本 / OS Version

Android11

### 应用版本 / App Version

0.0.9-64-gb381b414-release

**Comment by geol** [comment]
这么久了，现在有解决方案吗？我发现最近fcitx android有一次更新，更新完仍然也没有长按回车。
