### ISSUE TITLE
增加单手模式

### ISSUE THREAD

**Issue by ssrbasic** [fcitx5-android/fcitx5-android#604]
### 摘要 / Summary

手机输入法没有单手模式始终是一个遗憾

### 替代方案 / Alternative Solution

如果实现麻烦，那么能不能分别设置键盘左右边距来变相达到目的？

### 系统版本 / OS Version

安卓 14

### 应用版本 / App Version

0.09.80

**Comment by rocka** [comment]
duplicate of #154
