### ISSUE TITLE
功能请求：集成输入实时翻译功能

### ISSUE THREAD

**Issue by MUTED64** [fcitx5-android/fcitx5-android#608]
### 摘要 / Summary

希望能在输入法中集成一个类似于 Gboard 的实时翻译功能，可以通过接入免费的 Google 翻译 API 或其他类似服务来实现。

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-0-g8dc51356

**Comment by rocka** [comment]
不会加联网权限，不会集成第三方 non-free API

**Comment by Infinifar** [comment]
希望可以通过插件的形式来实现这个实时翻译> 不会加联网权限，不会集成第三方 non-free API
