### ISSUE TITLE
物理键盘的浮动候选词调整字体大小和边距

### ISSUE THREAD

**Issue by ZhangTianrong** [fcitx5-android/fcitx5-android#609]
### 摘要 / Summary

目前貌似字号和边距是在 `LabeledCandidateItemUI` 里默认设置成 16 和 3 的样子，在外接显示器上和 Gboard 的候选词相比小不少，而且明显更加紧凑，看上去比较吃力。希望可以允许用户调整这两个参数。

### 附加信息 / Additional Context

在手机本身屏幕上的候选词对比：
![PixPin_2024-11-06_21-58-13](https://github.com/user-attachments/assets/a1f70b72-42f5-4f7b-9710-fc8b414238f2)
在外接显示器上的候选词对比：
![PixPin_2024-11-06_21-56-24](https://github.com/user-attachments/assets/b89c7525-6638-4f64-bc06-2d39ab4a4161)
和虚拟键盘的候选词对比：
![PixPin_2024-11-06_21-54-03](https://github.com/user-attachments/assets/6524c325-cceb-4ce6-8eeb-f56aa781a935)
实际使用上观感差别还是很大的，只是局部放大后也许感觉没有那么明显，但是我认为至少允许用户选择保持和虚拟键盘的候选词大小、紧密程度一致总归是合理的。

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.0.9-85-g782aa110-release

**Comment by rocka** [comment]
done in 5de607a
