### ISSUE TITLE
请求添加键盘消失按钮

### ISSUE THREAD

**Issue by xyfgfhd** [fcitx5-android/fcitx5-android#611]
### 摘要 / Summary

添加键盘消失按钮按下后键盘消失

### 替代方案 / Alternative Solution

键盘隐藏按钮

### 系统版本 / OS Version

安卓

### 应用版本 / App Version

0.0.9-0-g8dc51356

**Comment by Hendrix4858** [comment]
> 开启“显示语音输入按钮”后，若系统中安装了其他语音输入法，语音输入按钮会替换收起键盘按钮。这时候可以使用下划语音输入按钮的方式收起键盘。

这应该提示一下吧,我开启了语音输入找不到收起按钮,还以为没开发,直到看到你的评论才知道.
