### ISSUE TITLE
请求剪贴板搜索功能

### ISSUE THREAD

**Issue by UNTRIVAL** [fcitx5-android/fcitx5-android#613]
### 摘要 / Summary

希望剪贴板中增加搜索按钮，当我复制了很多内容时，想找以前的东西就不是很方便了

### 系统版本 / OS Version

Flyme 10.5.0.2G

### 应用版本 / App Version

0.0.9-85-g782aa110

**Comment by oldherl** [comment]
剪贴板不是记事本或待办列表

**Comment by rocka** [comment]
> 那剪贴板数量不设限又有啥意义呢

有限制，默认 10

https://github.com/fcitx5-android/fcitx5-android/blob/5de607ab7f70870fcb823a1a8326315b314a313a/app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt#L315-L318

> 这样的话前面有人提议“类似gboard的那种定期清理剪贴板”也可以搞起来了

没有人力，欢迎来写代码

> 文件目录在哪里呢？起码给个导出吧

输入法设置 - 高级 - 导出用户数据，导出的压缩包里 `databases/clbdb` 就是全部剪贴板数据的 sqlite 数据库文件
