### ISSUE TITLE
使用rime插件无法加载rime-ice的模糊音配置

### ISSUE THREAD

**Issue by EnderAvaritia** [fcitx5-android/fcitx5-android#618]
### 摘要 / Summary

使用rime插件加载rime-ice的字库，字库可以正常读取，但是模糊音设置无效

### 重现步骤 / Steps to Reproduce

1. 修改rime-ice的配置，在 `rime_ice.schema.yaml` 和 `double_pinyin.schema.yaml` 中合适位置添加
```
    ### 模糊音
    # 声母
    - derive/^([zcs])h/$1/          # zh* ch* sh* 派生出 z* c* s*
    - derive/^([zcs])([^h])/$1h$2/  # z* c* s*    派生出 zh* ch* sh*
    # 韵母
    - derive/eng$/en/
    - derive/en$/eng/
    - derive/in$/ing/
    - derive/ing$/in/
```
2. 在fcitx中测试双拼，无效

### 预期行为 / Expected Behavior

fcitx可以识别双拼配置

### 截图 / Screenshot

![Snipaste_2024-11-16_22-32-09](https://github.com/user-attachments/assets/0d56f33a-cf7a-429b-a796-5a79b1955162)
![Snipaste_2024-11-16_22-32-21](https://github.com/user-attachments/assets/6b2026a4-f87a-4e50-9772-451f66e59235)
![Snipaste_2024-11-16_22-32-50](https://github.com/user-attachments/assets/c4136e65-2c12-482f-b89b-d33a562d203f)

### 系统版本 / OS Version

android14

### 应用版本 / App Version

0.0.9.0-g8dc51356

### 插件版本 / Plugins Version

rime plugin：0.0.9.0-g8dc51356

**Comment by eagleoflqj** [comment]
No code written in this repo is reading the yaml files you modified. Please discuss your misconfiguration at iDvel/rime-ice or rime/home.

**Comment by EnderAvaritia** [comment]
> No code written in this repo is reading the yaml files you modified. Please discuss your misconfiguration at iDvel/rime-ice or rime/home.

well, what is the problem lead to this problem ,i think it is because of the rime plugin failling to load the configuration so I put the issue in this repo
i dont really know what lead to this problem but i think i write the configuration correctly because the configuration i modified comes from the example of the configuration from iDvel/rime-ice
i hope to use the ambiguous spell when i use double spell 
does the problem blame to rime ,if it does i will put the issue to rime

**Comment by EnderAvaritia** [comment]
> [iDvel/rime-ice#631 (comment)](https://github.com/iDvel/rime-ice/issues/631#issuecomment-1905650941)

thanks a lot , but it no use
i summon three files :
![Snipaste_2024-11-17_01-08-56](https://github.com/user-attachments/assets/cdef9a02-6b32-4fdb-94b0-198543131e9b)
![Snipaste_2024-11-17_01-09-12](https://github.com/user-attachments/assets/96dcb021-7707-41aa-a527-6233c95ec7fd)
![Snipaste_2024-11-17_01-09-24](https://github.com/user-attachments/assets/f2505685-2617-4409-80a9-f010f22a9f46)
it seems nothing change
i will go to ask iDvel

**Comment by EnderAvaritia** [comment]
> [iDvel/rime-ice#631 (comment)](https://github.com/iDvel/rime-ice/issues/631#issuecomment-1905650941)

sorry , it works 
it blame to me that i forget to save before i send the file to my phone
thanks a lot
