### ISSUE TITLE
微信中偶发jkl按不出来

### ISSUE THREAD

**Issue by yanhan0123** [fcitx5-android/fcitx5-android#619]
### 摘要 / Summary

基本上是好用的，这个问题遇见过两次，键盘右侧jkl三个键按完没有反应（按键反馈也没有）。不清楚原因，不知道怎么复现。很抱歉无法提供其他有效信息

### 重现步骤 / Steps to Reproduce

大概是在拼音输入法输入数字或符号后出现

### 预期行为 / Expected Behavior

"j""k""l"这一块区域按下无反应

### 系统版本 / OS Version

android14

### 应用版本 / App Version

0.0.9-89

**Comment by rocka** [comment]
录屏看看

**Comment by yanhan0123** [comment]
> 录屏看看

很难录到，不是很常见的情况，再遇到我录一下
