### ISSUE TITLE
c/b开头的词组误输为v时无法进行qwerty自动纠错

### ISSUE THREAD

**Issue by Seterplus** [fcitx5-android/fcitx5-android#623]
### 摘要 / Summary

c/b开头的词组误输为v时无法进行qwerty自动纠错
（顺便问一句，我经常把i/j输错，但这两个键不在同一行所以无法自动纠错，是否有选项可以解决？）

### 重现步骤 / Steps to Reproduce

1. 关闭v进入快速输入模式。
2. 输入"veshi"（“测试”）等本应由c开头的词组。
3. 在输入至"ve"时，可以显示“测”字，但输入"ves"至"veshi"时无法显示“测试”这个词组。其他平台上的fcitx可以正常显示。
4. 若不关闭v进入快速输入模式，则因进入了快速输入模式，更加无法进行自动纠错。

### 预期行为 / Expected Behavior

与其他平台一样，"veshi"也可以纠错出“测试”这个词组。最好“veshj”也可以，以及误进入快速输入模式也可以。

### 系统版本 / OS Version

HyperOS 1.0

### 应用版本 / App Version

org.fcitx.fcitx5.android-0.0.9-0-g8dc51356-arm64-v8a-release

**Comment by Seterplus** [comment]
对于ij误输入，似乎应该由libime管……我发了个 https://github.com/fcitx/libime/issues/86#issue-2702255743

**Comment by rocka** [comment]
无法复现

![Screenshot_1732952214](https://github.com/user-attachments/assets/a5a70da8-343a-4aea-985c-29166017baae)

**Comment by Seterplus** [comment]
好的，谢谢！估计就是版本问题，我等下个版本试试吧～

**Comment by wengxt** [comment]
这个问题是默认v是进入快速输的，就离开了拼音环境了。

拼音配置里面修改一下，去掉 v 进入快速输入

![图片](https://github.com/user-attachments/assets/9bbde999-388f-46b9-a71a-2c4604017f54)

**Comment by Seterplus** [comment]
@wengxt 您好，我在“重现步骤-1”中已经关闭了v进入快速输入模式。更新1.0.0后该问题已经消失～
