### ISSUE TITLE
我从release里面下了code，用Android studio运行，怎么一直报错插件找不到呢

### ISSUE THREAD

**Issue by chenyuwulu** [fcitx5-android/fcitx5-android#625]
### 摘要 / Summary

Plugin [id: 'org.gradle.kotlin.kotlin-dsl', version: '4.4.0'] was not found in any of the following sources

kotlin-dsl启动失败找不到资源，可我的gradle版本也没错啊

### 重现步骤 / Steps to Reproduce

build-logic/convention/build.gradle.kts的插件一栏有报错

### 预期行为 / Expected Behavior

想要正常运行起来

### 系统版本 / OS Version

windows

### 应用版本 / App Version

0.0.9

**Comment by rocka** [comment]
请按照 README.md 中记述的 How to set up development environment 步骤进行。
