### ISSUE TITLE
横向候选词的左右滑动选词

### ISSUE THREAD

**Issue by 0Negentropy0** [fcitx5-android/fcitx5-android#628]
### 摘要 / Summary

选词框的词如果不是想要的每次还要点小三角箭头打开所有候选词，可不可以加一个让上面一排的候选词可以左右滑动来选词。

### 系统版本 / OS Version

Android 12

### 应用版本 / App Version

org.fcitx.fcitx5.android-0.0.9-0-g8dc51356-arm64-v8a-release

**Comment by rocka** [comment]
不能。横向划动和展开没法兼容。

**Comment by buddingworld** [comment]
哎其实我也好想要，很多输入法都可以😵😵😵

**Comment by lilydjwg** [comment]
我挺不喜欢滑动的，操作起来比较麻烦，尤其是手机没拿在手上的时候。展示的内容也比较少，而且更容易留油脂印。
