### ISSUE TITLE
剪贴板过滤插件不生效

### ISSUE THREAD

**Issue by My-Responsitories** [fcitx5-android/fcitx5-android#629]
### 摘要 / Summary

剪贴板过滤器无法删除url中的跟踪参数
例如: `https://example.com?utm_source=newsletter1&utm_medium=email&utm_campaign=sale`
长按复制, 输入法复制均保留了跟踪参数

### 重现步骤 / Steps to Reproduce

1. 安装输入法本体和`plugin.clipboard_filter`
2. 设为默认输入法
3. 复制`https://example.com?utm_source=newsletter1&utm_medium=email&utm_campaign=sale`
4. 查看剪贴板, 未删除跟踪参数
5. 查看日志, 没有`ClearURLs`标签

### 预期行为 / Expected Behavior

剪贴板里删除了跟踪参数

### 日志 / Log

```shell
adb logcat -s ClearURLs:D ClearURLsService:D
```

```
--------- beginning of crash
--------- beginning of system
--------- beginning of main
12-01 14:51:25.344 *** *** D ClearURLsService: Bind to fcitx remote
```

### 系统版本 / OS Version

11

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by Kevin-2483** [comment]
我也发现了这个问题,我本来依照剪贴板过滤插件的代码,希望写一个shell hook的插件,在剪贴板变动时完成一些自动化操作.但是它不工作,剪贴板过滤也不工作,我怀疑是IClipboardEntryTransformer出了问题,但是我能力有限,没办法知道解决方法

**Comment by eagleoflqj** [comment]
https://t.me/fcitx5_android_group/140182
看看这个能解决吗，我之前也是没启动后台服务

**Comment by rocka** [comment]
works fine for me ™

**Comment by mokapsing** [comment]
这个应用要挂后台，国产的系统ui要设置电池优化为不优化，允许自启，关联启动等
