### ISSUE TITLE
How do I install plugins like Anthy?

### ISSUE THREAD

**Issue by mirroredwang** [fcitx5-android/fcitx5-android#630]
### 摘要 / Summary

Inside plugins is a missing + button

### 重现步骤 / Steps to Reproduce

.

### 预期行为 / Expected Behavior

.

### 日志 / Log

.

### 截图 / Screenshot

.

### 附加信息 / Additional Context

.

### 系统版本 / OS Version

Android

### 应用版本 / App Version

current

**Comment by eagleoflqj** [comment]
https://github.com/fcitx5-android/fcitx5-android/releases/tag/0.1.0
