### ISSUE TITLE
在语言切换按键添加切换到其他输入法的功能（其他输入法指输入法app，而不是内置输入引擎）

### ISSUE THREAD

**Issue by TJNOV** [fcitx5-android/fcitx5-android#631]
### 摘要 / Summary

在语言切换按键添加切换到其他输入法的功能（其他输入法指输入法app，而不是内置输入引擎）
设备安装多个输入法app是比较常见的。在用fcitx5后，无法很方便的切换到其他输入法，如Gboard。但当使用其他输入法的时候，很容易切换到fcitx5。希望能添加这个功能。

### 替代方案 / Alternative Solution

建议的解决方案：增加全面屏适配。在输入法下面增加一栏，左侧切换输入法，右侧为剪贴板。
图为iPhone输入法示例
![图片](https://github.com/user-attachments/assets/04738d36-4547-4e22-8349-62a9e0b96485)

### 系统版本 / OS Version

hypeos

### 应用版本 / App Version

0.1.0

**Comment by eagleoflqj** [comment]
![Screenshot_2024-12-01-19-46-04-16_984e1414ae90666a90f12ff17ec14a7f](https://github.com/user-attachments/assets/1d7e91c3-fb02-4e29-889c-f8afc31d8a67)

长按地球即可

**Comment by TJNOV** [comment]
设置的是“切换到下一个输入法应用”，但是手机自带的搜狗输入法可以显示，雨燕输入法无法显示，即无法显示所有的输入法。已经保证输入法在手机设置中属于开启状态。

**Comment by rocka** [comment]
> 雨燕输入法无法显示，即无法显示所有的输入法。已经保证输入法在手机设置中属于开启状态。

有没有可能，是它自己设置的 exported=false ，不允许被其他输入法检测到

https://github.com/gurecn/YuyanIme/blob/2425d161191084c920a9dc0e4ef66164cfb61f24/app/src/main/AndroidManifest.xml#L12

**Comment by gurecn** [comment]
没明白您的意思，您是说从小企鹅输入法长按切换输入法时，不显示雨燕输入法吗？我没遇到这种情况。我特意试了一下如截图是可以切换的。
![Uploading Screenshot_2024-12-05-14-49-06-843_com.miui.notes.jpg…]()

**Comment by TJNOV** [comment]
> > 雨燕输入法无法显示，即无法显示所有的输入法。已经保证输入法在手机设置中属于开启状态。
> 
> 有没有可能，是它自己设置的 exported=false ，不允许被其他输入法检测到
> 
> https://github.com/gurecn/YuyanIme/blob/2425d161191084c920a9dc0e4ef66164cfb61f24/app/src/main/AndroidManifest.xml#L12

看样子我不太确定是这个软件什么原因，还是雨燕的问题。或许是个bug，但这个bug出现的频率太高了（有时候也能显示雨燕），还没有总结出出现的规律。
https://github.com/gurecn/YuyanIme/issues/194

**Comment by gurecn** [comment]
看小企鹅的输入法选择界面截图，雨燕输入法应该是没有被成功启用或是雨燕输入法启用前，小企鹅已经缓存输入法选择界面，雨燕输入法启用后没有及时更新界面。

**Comment by rocka** [comment]
@gurecn

> 看小企鹅的输入法选择界面截图，雨燕输入法应该是没有被成功启用或是雨燕输入法启用前，小企鹅已经缓存输入法选择界面，雨燕输入法启用后没有及时更新界面。

首先并没有缓存输入法列表。把 `android:exported="false"` 改成 true 就完事了，之前 gboard 检测不到 fcitx 就是这么处理的

https://github.com/fcitx5-android/fcitx5-android/commit/278c820ac4ab2f590ea39c97e1d2db0f0a44b8b4#diff-7fa6aef292187a049f7a4d6060d8df3ba212d838789c78940bd363344b1c38cd
