### ISSUE TITLE
允许用户添加额外的ClearURLs规则

### ISSUE THREAD

**Issue by My-Responsitories** [fcitx5-android/fcitx5-android#632]
### 摘要 / Summary

用户无法修改assets里的ClearURLs规则, 应将其放到`Android/data`中

https://github.com/fcitx5-android/fcitx5-android/blob/f8503f269b5c64539fc49e33196418f3139e539e/plugin/clipboard-filter/src/main/java/org/fcitx/fcitx5/android/plugin/clipboard_filter/ClearURLs.kt#L36-L43

### 系统版本 / OS Version

11

### 应用版本 / App Version

0.0.9

### 插件版本 / Plugins Version

0.0.9

**Comment by rocka** [comment]
... 没必要吧
