### ISSUE TITLE
候选词界面不能返回键盘

### ISSUE THREAD

**Issue by carefreedays** [fcitx5-android/fcitx5-android#633]
### 摘要 / Summary

候选词界面点击删除后不会返回键盘

### 重现步骤 / Steps to Reproduce

1.输入文字
2.展开候选词界面，点击删除键，删除输入文字
3.候选词界面不会返回键盘

### 预期行为 / Expected Behavior

卡在候选词界面

### 截图 / Screenshot

![Screenshot_2024-12-03-01-02-14-141_mark via](https://github.com/user-attachments/assets/82311b58-cc63-4d2f-95a8-aebea66e3483)

### 系统版本 / OS Version

hyper 1.0.19

### 应用版本 / App Version

0.1.0

**Comment by rocka** [comment]
should be fixed by 5ea3da3
