### ISSUE TITLE
点击“忘记候选词”后，不清除拼音、候选自动补位

### ISSUE THREAD

**Issue by UNTRIVAL** [fcitx5-android/fcitx5-android#634]
### 摘要 / Summary

点击“忘记候选词”后，不清除拼音、候选自动补位

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

0.1.0-0-g78c03d12

**Comment by rocka** [comment]
请到 https://github.com/fcitx/fcitx5-chinese-addons/issues 报告

**Comment by rocka** [comment]
upstream fix: https://github.com/fcitx/fcitx5-chinese-addons/commit/f4a165ec6cad608cdd9348648e1de62b4453e4d6
