### ISSUE TITLE
删除键上滑删除输入框内所有内容，下滑撤回

### ISSUE THREAD

**Issue by biqiguhexuenai** [fcitx5-android/fcitx5-android#635]
### 摘要 / Summary

如题，可以参考安卓搜狗输入法，另外弱弱问下候选栏可以左右滑动选择候选词吗，好像只能固定着

### 系统版本 / OS Version

android14

### 应用版本 / App Version

0.1.0-0-g78c03d12

**Comment by rocka** [comment]
建议使用退格键左划选择删除的功能
