### ISSUE TITLE
横屏时虚拟键盘下部空间过大

### ISSUE THREAD

**Issue by Ardenet** [fcitx5-android/fcitx5-android#637]
### 摘要 / Summary

将“虚拟键盘”->“键盘底部边距”的横屏底部边距设置为 0 仍然有过大的边距

### 重现步骤 / Steps to Reproduce

1. 将“虚拟键盘”->“键盘底部边距”的横屏底部边距设置为 0
![Screenshot_20241204_010803](https://github.com/user-attachments/assets/25a46a4b-9db3-4a22-9c46-45cb9ae65b14)
2. 横屏输入文本

### 预期行为 / Expected Behavior

输入法底部应紧贴屏幕底边

### 日志 / Log

[org.fcitx.fcitx5.android-2024-12-03T17_22_46Z.txt](https://github.com/user-attachments/files/17996741/org.fcitx.fcitx5.android-2024-12-03T17_22_46Z.txt)

### 截图 / Screenshot

![Screenshot_20241204_005853](https://github.com/user-attachments/assets/de1f83fd-4cd4-4c23-bb75-8e40484eea44)

与之对比的gboard
![Screenshot_20241204_010646](https://github.com/user-attachments/assets/8136f5fb-f308-4f4d-8aad-84fbb88fdf3c)

### 系统版本 / OS Version

Android 15; Origin OS 5(PD2408E_A_15.0.17.1.W10.V0101L11); iqoo 13

### 应用版本 / App Version

0.1.0-0-g78c03d12-release

**Comment by rocka** [comment]
系统问题，输入法收到了错误的 mandatorySystemGestures 导致键盘被抬高。请更新到最新 CI 构建版本，并在高级设置中开启"Ignore system WindowInsets"

https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/
