### ISSUE TITLE
小企鹅崩了

### ISSUE THREAD

**Issue by linzianabc** [fcitx5-android/fcitx5-android#638]
### 摘要 / Summary

软件是正常使用，但是一看后台日志，有了很多的错误。

### 重现步骤 / Steps to Reproduce

难以重现，因为没有提示

### 预期行为 / Expected Behavior

正常

### 日志 / Log

[org.fcitx.fcitx5.android-2024-12-04T15_48_34Z.txt](https://github.com/user-attachments/files/18015160/org.fcitx.fcitx5.android-2024-12-04T15_48_34Z.txt)

### 系统版本 / OS Version

Model (product): 22021211RC (munch) Manufacturer: Xiaomi

### 应用版本 / App Version

Version Name: 0.1.0-6-g5ea3da39 --------- Build Info

**Comment by rocka** [comment]
先贴个 ndk-stack 结果，有空再仔细看

[ndk-stack.txt](https://github.com/user-attachments/files/18026575/ndk-stack.txt)

**Comment by linzianabc** [comment]
> 先贴个 ndk-stack 结果，有空再仔细看
> 
> [ndk-stack.txt](https://github.com/user-attachments/files/18026575/ndk-stack.txt)
> 
> https://github.com/fcitx5-android/fcitx5-android/blob/5ea3da39/app/src/main/cpp/jni-utils.h#L67 https://github.com/fcitx5-android/fcitx5-android/blob/5ea3da39/app/src/main/cpp/object-conversion.h#L40 https://github.com/fcitx5-android/fcitx5-android/blob/5ea3da39/app/src/main/cpp/native-lib.cpp#L672

谢谢

**Comment by rocka** [comment]
should be fixed by https://github.com/fcitx5-android/fcitx5-android/commit/32bea57f762a3e946cf8549622fa6153e6de85a4
