### ISSUE TITLE
最新每夜版崩了重启却没有相应日志

### ISSUE THREAD

**Issue by linzianabc** [fcitx5-android/fcitx5-android#641]
### 摘要 / Summary

近期更新到最新版（0.1.0-9）使用过程中发现崩了的两种情况，却没有相应日志。

### 重现步骤 / Steps to Reproduce

1.使用Rime插件，方案拼音带有辅助码（lua)。在选择辅助码时 碰到过崩了。
2.也是Rime插件，自定义方案，输入时也崩了。但是没有使用lua插件，就是正常的方案输入。
无论怎么样，崩了后小企鹅自动重启。但是在崩了之后，查看小企鹅日志，只有崩了后重新启动后的日志，没有崩了启动前的日志。所以无从定位问题是什么。
具体崩了后表现为：键盘收起；点击输入框，小企鹅弹出，提示正在部署；查看日志，只有启动后的日志。
### 预期行为 / Expected Behavior

解决崩了的问题

### 系统版本 / OS Version

Model (product): 22021211RC (munch) Manufacturer: Xiaomi

### 应用版本 / App Version

Version Name: 0.1.0-9

**Comment by rocka** [comment]
可以尝试使用 https://github.com/F0x1d/LogFox 在后台收集一下日志

**Comment by linzianabc** [comment]
> 可以尝试使用 https://github.com/F0x1d/LogFox 在后台收集一下日志

好的。更新了最新版，发现这个问题好像没有出现了。我先关了这个。
