### ISSUE TITLE
连接物理键盘时QQ无法在回车后发送消息

### ISSUE THREAD

**Issue by PILIHU2022** [fcitx5-android/fcitx5-android#643]
### 摘要 / Summary

当连接到物理键盘时，在QQ的输入框中按下回车键只能换行而不能发送
使用rime插件 雾凇拼音方案

### 重现步骤 / Steps to Reproduce

[视频](https://pilihu2023-my.sharepoint.com/:v:/g/personal/pilihu_pilihu2023_onmicrosoft_com/Ece1rZpjcyhMkvLjYRhV1iMBn7xNTVNxMmay_3txB5Z1tQ?e=DkXknj)

### 预期行为 / Expected Behavior

当连接到物理键盘时，在QQ的输入框中按下回车键能发送消息

### 系统版本 / OS Version

Android 14

### 应用版本 / App Version

0.1.00.1.0-0-978c03d12-release

### 插件版本 / Plugins Version

rime 0.0.9-0-g8dc51356

**Comment by WhiredPlanck** [comment]
毕竟不是电脑版 QQ，QQ 定义了编辑框按下回车键的行为就是换行。连了物理键盘不能直接代入电脑端的行为。

**Comment by PILIHU2022** [comment]
> 毕竟不是电脑版 QQ，QQ 定义了编辑框按下回车键的行为就是换行。连了物理键盘不能直接代入电脑端的行为。

但是我之前用0.9版本的连接实体键盘时是可以这样的

**Comment by rocka** [comment]
> 之前用0.9版本的连接实体键盘时是可以这样的

“之前”具体是指哪个版本？虽然 0.0.9 到 0.1.0 新增了物理键盘显示候选框的功能，但是按键处理以及发送按键到程序的逻辑应该是没变的

**Comment by PILIHU2022** [comment]
> > 之前用0.9版本的连接实体键盘时是可以这样的
> 
> “之前”具体是指哪个版本？虽然 0.0.9 到 0.1.0 新增了物理键盘显示候选框的功能，但是按键处理以及发送按键到程序的逻辑应该是没变的

[这个](https://github.com/fcitx5-android/fcitx5-android/releases/tag/0.0.9)

**Comment by rocka** [comment]
方便降级测试一下吗？输入法的高级设置中可以导入/导出用户数据

**Comment by expoli** [comment]
这个应该是qq的问题，我尝试了一下系统自带的输入法，也是无法回车发送消息（不连接物理键盘的时候行为正常）。

qq在连接物理键盘的时候在设置里面开启的回车键发送消息会变成无效。
