### ISSUE TITLE
rime插件 使用数字键盘 预编辑中’1‘无法正确显示问题

### ISSUE THREAD

**Issue by xuennai** [fcitx5-android/fcitx5-android#645]
### 摘要 / Summary

文件为雾凇的小鹤双拼：
[double_pinyin_flypy.schema.zip](https://github.com/user-attachments/files/18063336/double_pinyin_flypy.schema.zip)

如以下视频，正确行为是1也应该在预编辑文本里,我实测同样配置给Windows小狼毫就正常

https://github.com/user-attachments/assets/4a55eb40-d7ba-4a85-8e4b-60ce8776b6ed

### 重现步骤 / Steps to Reproduce

1.在某个输入框，先输入几个字母，如‘ni’
2.紧接输入‘1’，发现未正确显示，输入其他数字正常显示，在小狼毫中1也正常显示

### 预期行为 / Expected Behavior

应显示‘ni1’

### 截图 / Screenshot

![IMG_20241209_230728](https://github.com/user-attachments/assets/cee505c1-8e5e-466c-9df3-079870d3af35)

### 系统版本 / OS Version

android14

### 应用版本 / App Version

0.1.0-14-g66994206

### 插件版本 / Plugins Version

0.1.0-0-g78c03d12

**Comment by rocka** [comment]
数字键盘里的 <kbd>1</kbd> 对应到桌面物理键盘上其实是小键盘的数字键 `KP_1` ，而不是主键盘区字母键上面的数字键。可以测试一下桌面端使用数字小键盘数字键是否也是相同行为。
