### ISSUE TITLE
手机竖屏下空间变大

### ISSUE THREAD

**Issue by linGinc** [fcitx5-android/fcitx5-android#648]
### 摘要 / Summary

更新0.1.0后，手机下方空间变大，已经隐藏小白条，之前使用0.9.4没有问题
手机 荣耀magic 7 系统：MagicOS 9.0
![微信图片_202412111630151](https://github.com/user-attachments/assets/ae1e1d07-3aa0-4579-9b7f-8613e810ba32)

![微信图片_20241211163015](https://github.com/user-attachments/assets/2bc1a48b-f9be-4471-9cb6-fd5e825c07f7)

![微信图片_20241211163013](https://github.com/user-attachments/assets/b198e1d2-8ca0-491e-85bc-255612a6c1d2)
![a3f4ab85b98aedc5ede0998ca94567d](https://github.com/user-attachments/assets/4712b921-a897-457d-be95-ae2ea36bb831)

### 重现步骤 / Steps to Reproduce

0.1.0有空白
0.9.4没有，插件一样，粘贴版插件及rime插件，版本和程序版本对应

### 预期行为 / Expected Behavior

无空白空间

### 系统版本 / OS Version

MagicOS 9.0.0.128

### 应用版本 / App Version

0.1.0.12

**Comment by shenghuang147** [comment]
https://github.com/fcitx5-android/fcitx5-android/issues/637#issuecomment-2515183715

**Comment by rocka** [comment]
可以尝试使用最新 CI 构建版本，并在高级设置中开启“Ignore system WindowInsets”

https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/

我放弃了，不存在一种可以适配所有魔改 UI 的方法，修一处 bug ，就会导致其他 UI 出现新的 bug ，所以弄个选项让用户自己调去吧
