### ISSUE TITLE
`Haptic feedback on keypress` does not consider `Use vibration and haptics` system setting

### ISSUE THREAD

**Issue by DokterKaj** [fcitx5-android/fcitx5-android#651]
### 摘要 / Summary

`Haptic feedback on keypress` only considers `Touch feedback` system setting. If `Use vibration and haptics` as a whole is turned off but `Touch feedback` was previously turned on, Fcitx5 will still provide haptic feedback.

### 重现步骤 / Steps to Reproduce

1. Go to `Vibration and haptics` in system settings
2. Turn on `Touch feedback`
3. Turn off `Use vibration and haptics`
4. Go to `Virtual Keyboard` in Fcitx5 settings
5. Set `Haptic feedback on keypress` to `Follow system settings`

### 预期行为 / Expected Behavior

Fcitx5 should not provide haptic feedback

### 系统版本 / OS Version

LineageOS 21

### 应用版本 / App Version

0.1.0

**Comment by rocka** [comment]
I'm not sure how to determine whether "Use vibration & haptics" is disabled in system settings. When disabled, [Vibrator#vibrate](https://developer.android.com/reference/android/os/Vibrator#vibrate(android.os.VibrationEffect)) does nothing, but [View#performHapticFeedback](https://developer.android.com/reference/android/view/View#performHapticFeedback(int)) still works.

Which means it would follow "Use vibration & haptics", as long as you set custom vibration duration in Fcitx5 virtual keyboard settings.

**Comment by DokterKaj** [comment]
Could you make default vibration duration use `vibrator.vibrate` as well, or is there a reason it must use `view.performHapticFeedback`?
https://github.com/fcitx5-android/fcitx5-android/blob/78cfe81769f673e9c9ec8e1e3557342106843fd4/app/src/main/java/org/fcitx/fcitx5/android/data/InputFeedbacks.kt#L86-L93

**Comment by rocka** [comment]
Then what is the "system default" vibration duration and amplitude?

**Comment by DokterKaj** [comment]
Maybe [`VibrationEffect.createPredefined`](https://developer.android.com/reference/android/os/VibrationEffect#createPredefined(int)) with [`EFFECT_CLICK`](https://developer.android.com/reference/android/os/VibrationEffect#EFFECT_CLICK) could work?

**Comment by rocka** [comment]
Should be fixed by 34a22f
