### ISSUE TITLE
按键触感反馈的类型似乎有问题

### ISSUE THREAD

**Issue by CrSjimo** [fcitx5-android/fcitx5-android#654]
### 摘要 / Summary

现在键盘的触感反馈类型是 `HapticFeedbackConstants.KEYBOARD_TAP` ，但是我在实际使用时感觉震动的强度过高，比手机自带的输入法和 Gboard 都更高。我发现 Gboard 所使用的触感反馈类型是`KEYBOARD_RELEASE`，关于这个问题有没有什么说法？

### 重现步骤 / Steps to Reproduce

1. 使用 `adb logcat` 读取日志
2. 在 fcitx5-android 中启用按键时振动，设置按键振动时长为系统默认，按下一个按键
3. 在 Gboard 中启用按键触感反馈，设置触感反馈强度为系统默认，按下一个按键

### 预期行为 / Expected Behavior

在 fcitx5-android 中按下一个按键时，输出
```
HapticFeedbackUtil: 3,2,true
```
在 Gboard 中按下一个按键时，输出
```
HapticFeedbackUtil: 7,2,true
```

### 系统版本 / OS Version

Xiaomi HyperOS 1.0.18.0.UNLCNXM

### 应用版本 / App Version

0.1.0-0-g78c03d12-release

**Comment by rocka** [comment]
我并不知道这些反馈类型有什么区别。但从文档上来看， [HapticFeedbackConstants#KEYBOARD_TAP](https://developer.android.com/reference/android/view/HapticFeedbackConstants#KEYBOARD_TAP) 的描述为 

> The user has pressed a soft keyboard key.
>
> Constant Value: 3 (0x00000003)

[HapticFeedbackConstants#KEYBOARD_RELEASE](https://developer.android.com/reference/android/view/HapticFeedbackConstants#KEYBOARD_RELEASE) 的描述为

> The user has released a virtual keyboard key.
>
> Constant Value: 7 (0x00000007)

而默认情况下，虚拟键盘的 haptic feedback 是只在按下按键的时候触发的，使用 `KEYBOARD_TAP` 更符合语义。
