### ISSUE TITLE
请问“双拼”可否加入辅码功能？

### ISSUE THREAD

**Issue by andeaker** [fcitx5-android/fcitx5-android#656]
### 摘要 / Summary

比如我用双拼（自然码），然后只要我长按某个键，就可以激活用自然码辅码规则逐个选字。
或者，已经有了类似的功能，还请说明一下，谢谢！

### 系统版本 / OS Version

android 15

### 应用版本 / App Version

0.1.0-0-g78c03d12-release

**Comment by eagleoflqj** [comment]
反引号（长按z左划）启用笔画过滤
笔画之外的辅码功能可能需要用 rime 插件以及相应的方案，比如 https://github.com/rimeinn/rime-moran

**Comment by wengxt** [comment]
把辅助码用自定义短语导入

例如小鹤的

https://github.com/fanqi/sogou-flypy/blob/master/sogou-flypy.txt

**Comment by andeaker** [comment]
> 把辅助码用自定义短语导入
> 
> 例如小鹤的
> 
> https://github.com/fanqi/sogou-flypy/blob/master/sogou-flypy.txt

这个工程量有点大……我试试用插件看看，谢谢
