### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by Kimiar** [fcitx5-android/fcitx5-android#657]
### 摘要 / Summary

CMake Error at D:/AndroidProject/fcitx5-android/lib/fcitx5/src/main/cpp/cmake/Fcitx5Utils/Fcitx5Macros.cmake:1:
Parse error.  Expected a command name, got unquoted argument with text
"../../../cpp/fcitx5/src/lib/fcitx-utils/Fcitx5Macros.cmake".

### 重现步骤 / Steps to Reproduce

gradle sync

### 预期行为 / Expected Behavior

/

### 系统版本 / OS Version

win10

### 应用版本 / App Version

/

**Comment by eagleoflqj** [comment]
You missed some steps on Windows to fix symlinks. Read README.md carefully and click to expand instructions.

**Comment by DEAN-Cherry** [comment]
You should run gradle sync first and make sure you get all extra package installed.
