### ISSUE TITLE
vivo手机频繁重新部署

### ISSUE THREAD

**Issue by ypxun** [fcitx5-android/fcitx5-android#659]
### 摘要 / Summary

大概从Jenkins上216版本开始，小企鹅会频繁突然重新部署。

### 重现步骤 / Steps to Reproduce

无触发范式，比较随机出现。输入时有可能重新部署，不输入看视频或刷网页时也会。

### 预期行为 / Expected Behavior

小企鹅花大概5-10s重新部署完毕后，又可正常使用。

### 日志 / Log

--------- Device Info
OS Name: PD2309_A_14.0.25.12.W10.V000L1
OS Version: 6.1.57-android14-11-maybe-dirty (eng.compil.20241029.202207)
OS API Level: 34
Device: PD2309
Model (product): V2309A (PD2309)
Manufacturer: vivo
Tags: release-keys
Screen Size: 1260 x 2800
Screen Density: 3.5
Screen orientation: Portrait
--------- Package Info
Package Name: org.fcitx.fcitx5.android
Version Code: 82
Version Name: 0.1.0-19-gb10bff30
--------- Build Info
Build Type: release
Build Time: 2024-12-16T15:54:13Z
Build Git Hash: b10bff30ad531690115a382dd06347741fcfe810
--------- beginning of main
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
W/RemoteInputConnection(23197): requestCursorUpdates() was cancelled.
W/AndroidFuture(23197): Remote result com.android.internal.infra.AndroidFuture@e639b51[Completed normally] ignored, as local future is already completed: com.android.internal.infra.AndroidFuture@b61ffb6[Completed exceptionally: java.util.concurrent.CancellationException]
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
I/ScrollIdentify(23197): on fling
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
W/WindowOnBackDispatcher(23197): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@c213833
I/.fcitx5.android(23197): dgc_arg: has_act=1, state=1
I/PowerHalWrapper(23197): PowerHalWrapper.getInstance 
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/.fcitx5.android(23197): dgc_arg: has_act=1, state=1
I/.fcitx5.android(23197): dgc_arg: 4096KB,16MB
W/WindowOnBackDispatcher(23197): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(23197): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
I/.fcitx5.android(23197): Open vivo delay for GC JIT .
I/.fcitx5.android(23197): Close vivo delay for GC JIT .
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
W/WindowOnBackDispatcher(23197): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@3723e5a
I/ScrollIdentify(23197): on fling
W/RemoteInputConnection(23197): requestCursorUpdates() was cancelled.
W/AndroidFuture(23197): Remote result com.android.internal.infra.AndroidFuture@fd2466b[Completed normally] ignored, as local future is already completed: com.android.internal.infra.AndroidFuture@fbec5c8[Completed exceptionally: java.util.concurrent.CancellationException]
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/.fcitx5.android(23197): dgc_arg: 4096KB,16MB
I/.fcitx5.android(23197): dgc_arg: request backgroud gc, has_act=1, state=0
I/.fcitx5.android(23197): dgc_arg: 2048KB,8192KB
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
W/View    (23197): requestLayout() improperly called by androidx.recyclerview.widget.RecyclerView{bb3ff91 VFEDH.... ......ID 0,0-1071,804 #ffff5e} during layout: running second layout pass
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/.fcitx5.android(23197): dgc_arg: 2048KB,8192KB
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
W/RemoteInputConnection(23197): requestCursorUpdates() was cancelled.
W/AndroidFuture(23197): Remote result com.android.internal.infra.AndroidFuture@10ddedb[Completed normally] ignored, as local future is already completed: com.android.internal.infra.AndroidFuture@530cd78[Completed exceptionally: java.util.concurrent.CancellationException]
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/ScrollIdentify(23197): on fling
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/ScrollIdentify(23197): on fling
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/.fcitx5.android(23197): dgc_arg: has_act=1, state=1
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
I/.fcitx5.android(23197): dgc_arg: 4096KB,16MB
I/.fcitx5.android(23197): dgc_arg: has_act=1, state=1
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
W/WindowOnBackDispatcher(23197): OnBackInvokedCallback is not enabled for the application.
W/WindowOnBackDispatcher(23197): Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
W/WindowOnBackDispatcher(23197): sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda17@c0c00fd
I/.fcitx5.android(23197): Open vivo delay for GC JIT .
I/.fcitx5.android(23197): Skip GC, current heap: 15MB(0B), current native: 70MB(0B)
I/.fcitx5.android(23197): dgc_arg: 4096KB,16MB
D/BufferQueueConsumer(23197): [](id:5a9d0000003f,api:0,p:-1,c:23197) connect: controlledByApp=false
E/OpenGLRenderer(23197): Unable to match the desired swap behavior.
D/BLASTBufferQueue(23197): [VRI[LogActivity]#63](f:0,a:1) acquireNextBufferLocked size=1260x2800 mFrameNumber=1 applyTransaction=true mTimestamp=171473912305989(auto) mPendingTransactions.size=0 graphicBufferId=99630356365545 transform=0
V/ImeFocusController(23197): onWindowFocus: DecorView@15369af[LogActivity] softInputMode=STATE_UNSPECIFIED|ADJUST_RESIZE|IS_FORWARD_NAVIGATION

### 系统版本 / OS Version

安卓14 vivo OriginOS 4

### 应用版本 / App Version

Jenkins上最新的228版本

### 插件版本 / Plugins Version

rime也是Jenkins上最新的31版本，剪贴板插件是最新的28版本

**Comment by rocka** [comment]
从 https://jenkins.fcitx-im.org/job/android/job/fcitx5-android/216 以来， fcitx5-rime 与 librime 都几乎没有进行运行逻辑上的更新

https://github.com/fcitx5-android/fcitx5-android/compare/2c0c4c98220c91ea3ae208a5b9a3ac53272171d0...de5bc3bb42bd224b0d936bcf72e3233a31a36a4d

无从排查

**Comment by Z46I4W5476SJA** [comment]
我也遇到了这样的情况 也是vivo x 200pro  基本上就是正常使用手机的时候  然后就提示重新部署
