### ISSUE TITLE
华为mate30的rime插件在同步时报错

### ISSUE THREAD

**Issue by tiantangzhixia** [fcitx5-android/fcitx5-android#660]
### 摘要 / Summary

在使用雾凇拼音配置文件后，使用小鹤双拼输入法，此时使用rime插件的sync同步功能报错，默认的sync目录下的yaml文件为0B，txt文件不为0，但是也没有同步进去用户词库。

### 重现步骤 / Steps to Reproduce

1. 安装完rime插件后，导入GitHub中雾凇拼音的配置文件
2. 修改installation中的id
3. 在rime设置中重新部署
4. 设置小鹤双拼
5. 在rime设置中点击同步

### 预期行为 / Expected Behavior

点击同步后会提示rime遇到问题，此时默认的sync同步目录下的文件大小异常，并且没有按预期生成错误日志。
![sync](https://github.com/user-attachments/assets/24930983-b6e2-487a-b350-ddc87e1ea13c)

### 系统版本 / OS Version

HarmonyOS 4.2.0

### 应用版本 / App Version

0.1.0-0-g78c03d12-release

### 插件版本 / Plugins Version

0.1.0-0-g78c03d12

**Comment by eagleoflqj** [comment]
同步报错一般是lua没写好，没能释放打开的用户词典。问题并不出在这个仓库。

**Comment by tiantangzhixia** [comment]
[org.fcitx.fcitx5.android-2024-12-20T08_21_12Z.txt](https://github.com/user-attachments/files/18207961/org.fcitx.fcitx5.android-2024-12-20T08_21_12Z.txt)
这是复现错误后生成的日志，请问有知道这是什么问题的吗？

**Comment by rocka** [comment]
日志里只说了 "error backing up file ..."，并没有记录原因。建议打开“实时日志”下面的“详细记录日志”选项，然后重新记录日志。

推测可能是文件权限问题，可以尝试使用系统 DocumentsUI ，侧边栏找到“小企鹅输入法”，在这里进行文件操作

**Comment by tiantangzhixia** [comment]
好的吧，抱歉我不太懂这个，我又开了详细日志记录，这是新的日志。
[org.fcitx.fcitx5.android-2024-12-20T08_55_11Z.txt](https://github.com/user-attachments/files/18208507/org.fcitx.fcitx5.android-2024-12-20T08_55_11Z.txt)

**Comment by rocka** [comment]
还是一样，并没更有详细的报错信息

**Comment by tiantangzhixia** [comment]
那确实不好搞了。可能就是之前说的权限问题，我在文件管理器里复制移动都没问题，但是程序的同步却出问题

**Comment by gostsdmitry** [comment]
> 那确实不好搞了。
按照视频中的说明进行操作。保存日志并在此处附加包含此日志的文件。

https://github.com/user-attachments/assets/6d659789-45ff-40a3-b54a-50ad89daf0b8

**Comment by tiantangzhixia** [comment]
我后来拿不同的手机试了下，确定是系统问题，具体应该是权限问题。安卓13的手机运行没问题，但是鸿蒙4.2的手机不行，可能鸿蒙把某些权限或者api改了，导致了rime插件无法完成同步，目前只能凑合着用了

**Comment by emptylight370** [comment]
ColorOS14也有同样的问题，在同步时提示报错，日志显示不能写入文件。
日志中显示进程一直持有数据库的锁，导致不能同步数据库。
不过文件无法复制应该与权限或锁无关，我尝试给了777权限，之后重试同步依然报错。有可能是插件处理同步事件时文件复制操作不为强制覆盖导致。
下面是导出的日志。
[org.fcitx.fcitx5.android-2024-12-29T01_10_54Z.txt](https://github.com/user-attachments/files/18268136/org.fcitx.fcitx5.android-2024-12-29T01_10_54Z.txt)

**Comment by rocka** [comment]
@emptylight370 

日志中显示

.temp.userdb/LOCK: already held by process

请自行检查方案中的 lua 脚本

**Comment by emptylight370** [comment]
> @emptylight370 
> 
> 日志中显示
> 
> .temp.userdb/LOCK: already held by process
> 
> 请自行检查方案中的 lua 脚本

没排查出来要使用锁的脚本，使用的配置是在薄荷的基础上改的，没动lua脚本，也没有增加什么内容，所以才想着在这里反馈的时候提一句。

**Comment by expoli** [comment]
> > @emptylight370
> > 日志中显示
> > .temp.userdb/LOCK: already held by process
> > 请自行检查方案中的 lua 脚本
> 
> 没排查出来要使用锁的脚本，使用的配置是在薄荷的基础上改的，没动lua脚本，也没有增加什么内容，所以才想着在这里反馈的时候提一句。

是你所使用的方案的 lua 脚本存在问题。向上游反馈吧。可以先删除这个文件夹，能够暂时恢复

**Comment by emptylight370** [comment]
> @expoli 
> 是你所使用的方案的 lua 脚本存在问题。向上游反馈吧。可以先删除这个文件夹，能够暂时恢复

感谢解答。不过删除lua脚本后测试中仍然出现上述报错。请问我应该向fcitx-rime反馈还是向薄荷方案反馈

**Comment by emptylight370** [comment]
> @expoli 
> 是你所使用的方案的 lua 脚本存在问题。向上游反馈吧。可以先删除这个文件夹，能够暂时恢复

感谢解答。不过删除lua脚本后测试中仍然出现上述报错。请问我应该向fcitx-rime反馈还是向薄荷方案反馈

**Comment by expoli** [comment]
> > @expoli 
> > 是你所使用的方案的 lua 脚本存在问题。向上游反馈吧。可以先删除这个文件夹，能够暂时恢复
> 
> 感谢解答。不过删除lua脚本后测试中仍然出现上述报错。请问我应该向fcitx-rime反馈还是向薄荷方案反馈

删除那个文件夹，向方案作者反馈

**Comment by emptylight370** [comment]
我重新检查了问题，在有lua的情况下我报错也不影响文件生成，就是单纯的出现报错，我看词频文件挺完整的。也没有看见什么文件为空的情况。
报错信息和之前提供的一致。

**Comment by ypxun** [comment]
> 我重新检查了问题，在有lua的情况下我报错也不影响文件生成，就是单纯的出现报错，我看词频文件挺完整的。也没有看见什么文件为空的情况。 报错信息和之前提供的一致。

兄弟解决没？我也发生了同步报错：
```
E/rime.fcitx-rime(17585): Error opening db '.temp' read-only.
E/rime.fcitx-rime(17585): error backing up user dict '.temp'.
E/rime.fcitx-rime(17585): failed synchronizing 1/3 user dicts.
```
我和你类似的是在大版本升级后出现的，从vivo OriginOS 4升级到了5（安卓大版本从14->15），区别是我用的是rime-ice方案。

**Comment by 217heidai** [comment]
修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
```
04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
```

**Comment by expoli** [comment]
> 修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
> ```
> 04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
> 04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
> 04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
> 04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
> 04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
> 04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
> 04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
> 04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
> 04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
> 04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
> 04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
> ```

删除这个 lock 文件夹，再同步

**Comment by 217heidai** [comment]
> > 修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
> > ```
> > 04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
> > 04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
> > 04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
> > 04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
> > 04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
> > 04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
> > 04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
> > 04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
> > 04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
> > 04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
> > 04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
> > ```
> 
> 删除这个 lock 文件夹，再同步
没权限，删不掉。。。

**Comment by dreamflandre** [comment]
@expoli 正常，公共文件夹的文件 ，小企鹅只有自己写入的文件的权限，别的软件的创建的文件没有权限读取。

**Comment by dreamflandre** [comment]
> 修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
> 
> ```
> 04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
> 04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
> 04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
> 04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
> 04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
> 04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
> 04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
> 04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
> 04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
> 04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> 04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
> 04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
> ```

公共文件夹的文件 ，小企鹅只有自己写入的文件的权限，别的软件的创建的文件没有权限读取。只能在默认私有目录，小企鹅才能读写

**Comment by 217heidai** [comment]
> > 修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
> > ```
> > 04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
> > 04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
> > 04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
> > 04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
> > 04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
> > 04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
> > 04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
> > 04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
> > 04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
> > 04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > 04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
> > 04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
> > ```
> 
> 公共文件夹的文件 ，小企鹅只有自己写入的文件的权限，别的软件的创建的文件没有权限读取。只能在默认私有目录，小企鹅才能读写

这样的话，有什么多端同步方案吗

**Comment by dreamflandre** [comment]
> > > 修改`installation.yaml`可以正常同步文件到制定目录，但是同目录下通过syncthing同步过来PC端的数据，却没法合并到手机。
> > > ```
> > > 04-01 15:04:16.051  8063 15169 E rime.fcitx-rime: Error opening db 'tips': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/tips.userdb/LOCK: already held by process
> > > 04-01 15:04:16.052  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Android-MEIZU20/tips.userdb.txt
> > > 04-01 15:04:16.092  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.094  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/tips.userdb.txt
> > > 04-01 15:04:16.124  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.126  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/tips.userdb.txt
> > > 04-01 15:04:16.155  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.157  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/tips.userdb.txt
> > > 04-01 15:04:16.158  8063 15169 E rime.fcitx-rime: Error opening db 'tips' read-only.
> > > 04-01 15:04:16.159  8063 15169 E rime.fcitx-rime: error backing up user dict 'tips'.
> > > 04-01 15:04:16.257  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.259  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/CachyOS/zc.userdb.txt
> > > 04-01 15:04:16.290  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.292  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/MacMini/zc.userdb.txt
> > > 04-01 15:04:16.331  8063 15169 E rime.fcitx-rime: Error opening db '.temp': IO error: lock /storage/emulated/0/Android/data/org.fcitx.fcitx5.android/files/data/rime/.temp.userdb/LOCK: already held by process
> > > 04-01 15:04:16.333  8063 15169 E rime.fcitx-rime: failed to merge snapshot file: /sdcard/Download/Rime/Win10-PD/zc.userdb.txt
> > > 04-01 15:04:16.361  8063 15169 E rime.fcitx-rime: failed synchronizing 2/2 user dicts.
> > > ```
> > 
> > 
> > 公共文件夹的文件 ，小企鹅只有自己写入的文件的权限，别的软件的创建的文件没有权限读取。只能在默认私有目录，小企鹅才能读写
> 
> 这样的话，有什么多端同步方案吗

可以考虑使用支持 SAF 的文件同步工具，如 https://foldersync.io/
