### ISSUE TITLE
工具栏能否增加常用语功能？

### ISSUE THREAD

**Issue by tiantangzhixia** [fcitx5-android/fcitx5-android#661]
### 摘要 / Summary

目前工具栏已经有了剪切板功能，能否增加常用语功能？这样在输入一些经常使用的短语或句子时可以节省不少时间。

### 系统版本 / OS Version

Android 13

### 应用版本 / App Version

0.1.0-0-g78c03d12-release

**Comment by eagleoflqj** [comment]
输入法 -> 拼音 -> 管理自定义词组

**Comment by Meavel** [comment]
常用语已经在我的码表里面了，如果你的软件有预制常用语，有可能会被认为是老人输入法的特色，最好尽量避免被人发现。

**Comment by tiantangzhixia** [comment]
> 输入法 -> 拼音 -> 管理自定义词组

好像对我不太适用，我用的rime插件，所以拼音的自定义词组用不了。不过我后来捣鼓了下，发现剪切板的置顶功能可以实现类似目的。通过在剪切板中置顶几个短语，后续可以直接当作常用语使用，还是比较方便的。就是不能太多，要不然会影响临时粘贴内容的使用。
