### ISSUE TITLE
自定义词组的‘键’支持数字

### ISSUE THREAD

**Issue by UNTRIVAL** [fcitx5-android/fcitx5-android#662]
### 摘要 / Summary

比如手机号123456789，可以输入123出联想
比如邮箱123456789@gmail.com, 可以输入123出联想

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

0.1.0-18-g78cfe817

**Comment by wengxt** [comment]
自定义词组是基于合法的拼音输入的字符的

你可以用快速输入
