### ISSUE TITLE
没有次选按键

### ISSUE THREAD

**Issue by 107295472** [fcitx5-android/fcitx5-android#664]
### 摘要 / Summary

想把逗号和.号放在右边

### 系统版本 / OS Version

安卓14

### 应用版本 / App Version

0.1.0

### 插件版本 / Plugins Version

0.1.0

**Comment by 107295472** [comment]
想把逗号，改成次选，在输入时是次选

**Comment by rocka** [comment]
> 想把逗号和.号放在右边

目前不支持自定义键盘布局 #377

> 想把逗号，改成次选，在输入时是次选

输入法设置界面 - 高级 - 隐藏快捷键配置 关闭，就可以在码表输入法的设置界面中找到“选择第二个候选词”“选择第三个候选词”的选项。分别设置为英文逗号 , 或者句号 . 就可以了。注意不要设置成中文全角标点符号，只能是英文标点。

**Comment by 107295472** [comment]
谢谢，真的好用，比同文好
