### ISSUE TITLE
连接物理键盘时保持隐藏软键盘 / Keep virtual keyboard invisible when physical keyboard connected

### ISSUE THREAD

**Issue by loichyan** [fcitx5-android/fcitx5-android#666]
### 摘要 / Summary

能否添加一个选项，在连接物理键盘时保持隐藏软键盘，或者只显示工具栏？

目前对物理键盘的支持已经相当好了♥️，但是有些时候，当焦点快速来回切换的时候，软键盘会反复弹出：

https://github.com/user-attachments/assets/86b77f88-2523-4ce5-a146-c1a67fde29bb

### 附加信息 / Additional Context

我找一个类似的请求 #605

### 系统版本 / OS Version

One UI 6.1.1, Android 14

### 应用版本 / App Version

0.1.0-0-g78c03d12

### 插件版本 / Plugins Version

Rime Plugin 0.1.0-0-g78c03d12

**Comment by rocka** [comment]
输入法并不能知道到底有没有连接物理键盘。

请将选项“输入法设置 - 候选窗口 - 显示候选词窗口”更改为“系统默认”，然后使用系统设置中隐藏虚拟键盘的选项来控制这个行为。
