### ISSUE TITLE
[BUG]中文输入法下，[会变成·

### ISSUE THREAD

**Issue by zzzsyyy** [fcitx5-android/fcitx5-android#71]
githash：9697ce0
system：android 12

**Comment by rocka** [comment]
这是 fcitx5-chinese-addons 的默认标点映射
https://github.com/fcitx/fcitx5-chinese-addons/blob/5.0.12/modules/punctuation/punc.mb.zh_CN#L17

可以在 设置-输入法-拼音-标点 内修改
