### ISSUE TITLE
微软双拼没有ing

### ISSUE THREAD

**Issue by kpzhao** [fcitx5-android/fcitx5-android#73]
一般使用;代替ing，但是找不到ing的键位

好像在J上，但是要长按qaq，

**Comment by rocka** [comment]
下划也可以输入符号 ... 自定义键盘布局的功能还没~开始~做。

目前的建议是先用自然码双拼代替微软双拼。在 fcitx5 的双拼实现里面，微软双拼和自然码双拼的映射只有三处不同：

https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L21-L30

https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L76-L85

总共有四个按键不完全相同：

|按键|<kbd>y</kbd>|<kbd>v</kbd>|<kbd>t</kbd>|<kbd>;</kbd>|
|:-|:-|:-|:-|:-|
|**自然码**|**ing**|ui **v**|ue **ve**|/|
|**微软**|**v** **ve**|ui|ue|**ing**|


而且 fcitx5 的自然码双拼也可以用 o 当零声母，切换一下应该不难 ...

**Comment by kpzhao** [comment]
> 下划也可以输入符号 ... 自定义键盘布局的功能还没~开始~做。
> 
> 目前的建议是先用自然码双拼代替微软双拼。在 fcitx5 的双拼实现里面，微软双拼和自然码双拼的映射只有三处不同：
> 
> https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L21-L30
> 
> https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L76-L85
> 
> 总共有四个按键不完全相同：
> 按键 	y 	v 	t 	;
> **自然码** 	**ing** 	ui **v** 	ue **ve** 	/
> **微软** 	**v** **ve** 	ui 	ue 	**ing**
> 
> 而且 fcitx5 的自然码双拼也可以用 o 当零声母，切换一下应该不难 ...

感谢回复，我去试试。谢谢为安卓带来fcitx5

**Comment by YukinoHayakawa** [comment]
感觉打开 in→ing的模糊音可能更方便一点

**Comment by TongHua1688** [comment]
现在还是没有解决方案吗？

> 下划也可以输入符号...自定义键盘布局的功能还没有~开始~做。
> 
> 目前的建议是先用自然码双拼代替微软双拼。在 fcitx5 的双拼实现里面，微软双拼和自然码双拼的映射只有三处不同：
> 
> https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L21-L30
> 
> https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L76-L85
> 
> 总共有四个按键不一个：
> 
> 克	y	v	t	;
> **自然码**	**ing**	ui **v**	ue **ve**	/
> **微软**	**非常** **​**	用户界面	ue	**ing**
> 而且fcitx5的自然码双拼也可以用o当零声母，切换一下应该不难...

现在还是没有解决方案吗？我今天在安卓手机上下载了fcitx5, 微软双拼的ing是用；，但是fcitx5的；要在。中找到，没法直接点击；

可以多做几个键盘布局的方案让用户选，甚至设置自定义布局。

**Comment by expoli** [comment]
> 现在还是没有解决方案吗？
> 
> > 下划也可以输入符号...自定义键盘布局的功能还没有~开始~做。
> > 
> > 目前的建议是先用自然码双拼代替微软双拼。在 fcitx5 的双拼实现里面，微软双拼和自然码双拼的映射只有三处不同：
> > 
> > https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L21-L30
> > 
> > https://github.com/fcitx/libime/blob/1.0.11/src/libime/pinyin/shuangpindata.h#L76-L85
> > 
> > 总共有四个按键不一个：
> > 
> > 克	y	v	t	;
> > **自然码**	**ing**	ui **v**	ue **ve**	/
> > **微软**	**非常** **​**	用户界面	ue	**ing**
> > 而且fcitx5的自然码双拼也可以用o当零声母，切换一下应该不难...
> 
> 现在还是没有解决方案吗？我今天在安卓手机上下载了fcitx5, 微软双拼的ing是用；，但是fcitx5的；要在。中找到，没法直接点击；
> 
> 可以多做几个键盘布局的方案让用户选，甚至设置自定义布局。

https://www.expoli.tech/articles/2025/06/23/Practice-of-Customizing-Fcitx5-Android-Keyboard-Layout-Based-on-the-Modified-Version-by-fxliang

根据这个文章尝试一下 fxliang 的 fork 版本，能实现一定程度上的自定义

**Comment by s5unty** [comment]
> 需要长按 `。` 选择 `;` 才能输入 `ing`

感谢 #786
