### ISSUE TITLE
[功能请求] 夜间模式

### ISSUE THREAD

**Issue by sukanka** [fcitx5-android/fcitx5-android#74]
希望能够在主题设置里面选择两套主题，亮色和暗色，然后能够按照系统的主题进行切换，或者定时（或者按日出到日落）进行自动切换。

**Comment by rocka** [comment]
已经在 todo 里了

https://trello.com/c/CBgaSORs/43-%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%8D%A2%E4%B8%BB%E9%A2%98

**Comment by sukanka** [comment]
> 已经在 todo 里了
> 
> https://trello.com/c/CBgaSORs/43-%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%8D%A2%E4%B8%BB%E9%A2%98

谢谢，原来各种todo在这，我还奇怪怎么没有在roadmap看到这个。
