### ISSUE TITLE
Dedicated number row / 键盘单独数字行

### ISSUE THREAD

**Issue by wuhgit** [fcitx5-android/fcitx5-android#75]
开发者您好，有没有设置开启输入法键盘单独的数字行？当前键盘的数字输入依赖于QWERT这一行字母，能否提供相关设置，开启键盘单独的数字行进行数字输入？

谢谢

**Comment by wuhgit** [comment]
大早上的果然是傻了……

词典上左滑就是移除，然后再添加就可以了……

😅

**Comment by rocka** [comment]
Customizable keyboard haven't been implemented yet, for now there's only a hardcoded qwerty layout.

---

可配置的键盘布局目前还没实现，只有一种写死的 qwerty 布局。~问就是在做了~

**Comment by wuhgit** [comment]
@rocka 

感谢解疑

如果是写死的，那我本来想问的第二个问题也不用问了，我之前还想知道如何才能反转 “短按是句号长按才是逗号”，总感觉这个输入方式不符合日常输入的使用频率。
