### ISSUE TITLE
每次开机后会崩溃一次

### ISSUE THREAD

**Issue by lisansas** [fcitx5-android/fcitx5-android#76]
--------- Build Info
Build Time: 2022-05-13T17:07:57Z
Build Git Hash: b2a5f3b
Build Version Name: 0.0.2-2-gb2a5f3b-release
--------- Device Info
App Package Name: org.fcitx.fcitx5.android
App Version Name: 0.0.2-2-gb2a5f3b
App Version Code: 2
OS Name: RQ3A.211001.001
OS Version: 4.19.217-Arrow-g60e77b7089e0 (12510)
OS API Level: 30
Device: apollo
Model (product): M2007J3SC (arrow_apollo)
Manufacturer: Xiaomi
Tags: release-keys
Screen Size: 1080 x 2310
Screen Density: 2.75
Screen orientation: Portrait
--------- beginning of main
W/InputConnectionWrapper( 4481): requestUpdateCursorAnchorInfo() didn't respond in 2000 msec. Returning default: 0
E/CustomActivityOnCrash( 4481): App has crashed, executing CustomActivityOnCrash's UncaughtExceptionHandler
E/CustomActivityOnCrash( 4481): java.lang.RuntimeException: Alive checking failed! The job didn't get run after 8000 ms!
E/CustomActivityOnCrash( 4481): 	at org.fcitx.fcitx5.android.core.FcitxDispatcher$AliveChecker$install$1.invokeSuspend(FcitxDispatcher.kt:73)
E/CustomActivityOnCrash( 4481): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/CustomActivityOnCrash( 4481): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/CustomActivityOnCrash( 4481): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CustomActivityOnCrash( 4481): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CustomActivityOnCrash( 4481): 	at java.lang.Thread.run(Thread.java:923)
I/Process ( 4481): Sending signal. PID: 4481 SIG: 9

倒是不影响什么 而且只有开机时会这样

**Comment by berberman** [comment]
@lisansas 这是一个已知的问题：fcitx 未响应时间超过了 8 秒。这通常是在手机启动（CPU负载大）时尝试加载拼音词典造成的。我们已有计划移除这个 8 秒的限制。出于好奇——请问您添加了多少拼音词典？

**Comment by lisansas** [comment]
> @lisansas 这是一个已知的问题：fcitx 未响应时间超过了 8 秒。这通常是在手机启动（CPU负载大）时尝试加载拼音词典造成的。我们已有计划移除这个 8 秒的限制。出于好奇——请问您添加了多少拼音词典？

三个，但词条应该超过了150w

**Comment by berberman** [comment]
Closed by [b944d25](https://github.com/fcitx5-android/fcitx5-android/commit/b944d2557f7f4dd23d8b64ef8d9584ff0a74ed72)
