### ISSUE TITLE
Adding support for fcitx5-unikey

### ISSUE THREAD

**Issue by hmtheboy154** [fcitx5-android/fcitx5-android#77]
Hi, I just come across this new project and I am very interested to see the fcitx5 input method ported to Android.
So far I tried the English keyboard and it's a pretty decent keyboard (it's lacking the characters change to normal/CAPS when I press the switch). However since I am a Vietnamese I wonder if the team have any plan to port [fcitx5-unikey](https://github.com/fcitx/fcitx5-unikey) to the app ?

**Comment by hmtheboy154** [comment]
> Currently we only have English and Chinese (via [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons)) support, but we are planning to design some kind of plugin system in order to integrate more input methods, like [fcitx5-chewing](https://github.com/fcitx/fcitx5-chewing), [fcitx5-anthy](https://github.com/fcitx/fcitx5-anthy), [fcitx5-hangul](https://github.com/fcitx/fcitx5-hangul), [fcitx5-unikey](https://github.com/fcitx/fcitx5-unikey) etc. By plugins, I mean split apk for each engine, let the main App discover and load them at runtime, rather than squash all input methods in one apk.

Thanks for the reply, I'll look forward to it.

**Comment by berberman** [comment]
Given that the installation size (regarding transitive dependencies as well) of fcitx5-unikey is considerably small, I think we could give it a first-class support, leaving out the future plugin system.

**Comment by hmtheboy154** [comment]
Close the Issue, the team has successfully ported Unikey.
