### ISSUE TITLE
symbol keyboard & themes from google pinyin ime / 使用来自谷歌拼音输入法的符号键盘与主题

### ISSUE THREAD

**Issue by rhjdvsgsgks** [fcitx5-android/fcitx5-android#87]
google pinyin ime have a wider symbol keyboard. which provided much more symbol than usual gboard. it would be great if possible to used this symbol keyboard replace gboard one.
谷歌拼音有个挺大的符号键盘，提供了比 gboard 多很多的的符号，希望能用这个换掉目前的符号键盘
![pic](https://user-images.githubusercontent.com/26178113/172271532-adcf9cb1-94cf-4b60-8c36-29d99b2bb27e.png)
谷歌拼音还有个几个 gboard 没有的配色，希望能一并加进来

**Comment by rocka** [comment]
We also want a more user friendly symbol/emoji picker, but that's easier said than done.

As for custom themes, you can try our theme designer: https://fcitx5-android.github.io/theme-designer/

**Comment by berberman** [comment]
Closed by #123
