### ISSUE TITLE
will cause "Keyboard cursor control" in lineage unable to use / 会导致 lineage 的音量键控制光标无法使用

### ISSUE THREAD

**Issue by rhjdvsgsgks** [fcitx5-android/fcitx5-android#95]
in lineage os, there is a feature called "Keyboard cursor control". can use Volume up/down keys to move cursor left/right. but after using this ime. that feature not working anymore.
这个输入法好像会导致 lineage 的“音量键当左右键用”的功能用不了

**Comment by rocka** [comment]
You can just hold and swipe the space button to move cursor, no need to use volume keys. Anyway, I would investigate it later.

**Comment by rocka** [comment]
Should be fixed by 51dc3ef

FYI, this is how the feature is implemented: https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/258477
