### ISSUE TITLE
请求添加郑码输入法，或可以添加自定义码表

### ISSUE THREAD

**Issue by gmg137** [fcitx5-android/fcitx5-android#99]
请求添加郑码输入法，或可以添加自定义码表。

**Comment by wengxt** [comment]
自定义码表也就是需要和桌面版一样把文件放到对应的地方即可使用

https://github.com/fcitx/fcitx5-table-extra/ 里有郑码，你也可以从发行版的包里直接抓出文件复制到对应目录下，可以省掉你编译的过程，核心文件就两个
/usr/share/fcitx5/inputmethod/zhengma.conf
/usr/share/fcitx5/table/zhengma.main.dict
（其他郑码拼音等自行选择对应文件）

至于直接装 apk 就有郑码的问题
1、直接集成 table-extra 可能太大他们不想
2、以安装 apk 的方式添加包，则还没有支持

**Comment by gmg137** [comment]
@wengxt 你好，请问在手机上对应的放置码表文件目录在什么位置？

**Comment by rocka** [comment]
码表的 dict 文件（ zhengma.dict ）放到 /Android/data/org.fcitx.fcitx5.android/files/data/table/ 目录里面，没有就新建

conf 文件（ zhengma.conf ）改一下， [Table] File= 的路径改成 table/zhengma.dict ，放到 /Android/data/org.fcitx.fcitx5.android/files/data/inputmethod/

顺便说一下， /Android/data/org.fcitx.fcitx5.android/files/data/ 对应的就是桌面上的 XDG_DATA_HOME

**Comment by gmg137** [comment]
好的，非常感谢
